#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Agdistis

*Agdistis* war ein grausam anzuschauendes Zwitter-Monstrum.

** Ereignisse in Arachneion-Pallashass
   :PROPERTIES:
   :CUSTOM_ID: ereignisse-in-arachneion-pallashass
   :END:

Die Hexe [[file:hippolaya.org][Hippolaya]] erweckt aus der toten
[[file:kybele.org][Kybele]] und dem toten [[file:attis.org][Attis]] mithilfe des
Blutes des Pfaus der [[file:hera.org][Hera]] das Monstrum Agdistis wieder zum
Leben. Als kurz darauf der [[file:hermes.org][Hermes]] den Tempel betritt, wird
dieser Zeuge, wie das Monstrum Agdistis durch die Gänge des Tempels
streift.

Wenig später wird der Hermes von der Hexe Hippolaya in Bestienform
überrascht. Die Hexe tötet den Götterboten. Die Sandalen des Hermes gibt
sie an das Monstrum Agdistis weiter. Dieses ist dadurch in der Lage,
über das [[file:aegaeisches-meer.org][Ägäische Meer]] zu laufen und so das Deck
der [[file:argo.org][Argo]] zu erreichen. Hier kommt es zum Kampf zwischen
[[file:iason.org][Iason]], [[file:asklepios.org][Asklepios]], [[file:athene.org][Athene]],
[[file:hera.org][Hera]], [[file:arachne.org][Arachne]], [[file:padmilos.org][Padmilos]] und
der [[file:colydon.org][Ziege Colydon]]. Hierbei schlägt der Iason dem Monstrum
Agdistis das Gemächt ab. Das Monstrum geht über Bord, reißt jedoch die
Ziege Colydon mit sich in die Tiefe.

## Siehe auch * [[file:kybele-mythos.org][Kybele (Mythos)]]
