#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Arachneion-Pallashass
#+OPTIONS: toc:1

** Personae
   :PROPERTIES:
   :CUSTOM_ID: personae
   :END:

-  Menschen und Tiere
-  [[file:asklepios.org][Asklepios]]: Legendärer Heiler und Teilnehmer der
   Argonautenfahrt.
-  [[file:idmon.org][Idmon]]: Legendärer Seher. Argonaut und Vater der Arachne.
-  [[file:iason.org][Iason]]: Sohn des Aison. Anführer der Argonauten.
-  [[file:arachne.org][Arachne]]: Tochter des Idmon.
-  [[file:colydon.org][Colydon]]: Ziege der Arachne.
-  Götter
-  [[file:zeus.org][Zeus]]: Göttervater und oberster Gott.
-  [[file:hera.org][Hera]]: Seine eifersüchtige Gattin.
-  [[file:hades.org][Hades]]: Herrscher über das Totenreich.
-  [[file:poseidon.org][Poseidon]]: Gott des Meeres.
-  [[file:athene.org][Athene]]: Göttin der Weisheit, der Kunst und des
   Handwerks.
-  Sonstige Begriffe und Fabelwesen
-  [[file:kroniden.org][Kroniden]]: Kinder des Kronos.

   -  [[file:zeus.org][Zeus]]
   -  [[file:hades.org][Hades]]
   -  [[file:poseidon.org][Poseidon]]
   -  [[file:hera.org][Hera]]
   -  [[file:hestia.org][Hestia]]
   -  [[file:demeter.org][Demeter]]

-  [[file:moiren.org][Moiren]]: Schicksalsgöttinnen.

   -  [[file:klotho.org][Klotho]]
   -  [[file:lachesis.org][Lachesis]]
   -  [[file:atropos.org][Atropos]]

-  [[file:aisonide.org][Aisonide]]: Kind des Aison (Iason).
-  Weitere [[file:goetter.org][Götter]] und [[file:fabelwesen.org][Fabelwesen]].

** Zusammenfassung
   :PROPERTIES:
   :CUSTOM_ID: zusammenfassung
   :END:

In Bithynien wird der Heiler Asklepios vom sterbenden Idmon gebeten,
sich seiner Tochter Arachne anzunehmen. Asklepios beschließt, sie nach
Hypaipa zu führen und unter die Fittiche einer alten Bekannten zu geben.

Bevor er die Stadt Kolophon erreicht, die Heimat der Arachne, stößt er
auf den Hades. Hades eröffnet ihm, dass der Frevel des Asklepios nicht
unbemerkt geblieben ist und er gekommen ist, den Asklepios mit sich in
den Hades zu nehmen. Asklepios bittet den Hades darum, wenigstens noch
die Arachne nach Hypaipa führen zu dürfen. Danach will er sich sofort
dem Hades anschließen und ins Totenreich folgen. Als Asklepios gemeinsam
mit der Arachne und dem Jungen Padmilos die Stadt verlässt, kommt es zum
Angriff der Persischen Flotte. Der Angriff wird von Poseidon
niedergeschlagen, um die Perser zu vernichten entfesselt er jedoch den
Ketos, ein schreckliches Meeresungeheuer, welches die Stadt Kolophon
zerstört.

In Myrina treffen sie erneut auf den Hades. Asklepios tötet ihn mit der
Klinge Hadesbrand. Hades schickt daraufhin den Zerberus aus, um sich an
Asklepios zu rächen. Der Zerberus zerreißt den Asklepios, woraufhin sich
dieser im Totenreich wiederfindet.

Im Totenreich erwachen einige tote Argonauten und erinnern sich an ihr
früheres Leben. Ihr Anführer Iason zettelt einen Aufstand an und die
Toten stürmen gegen die Festung des Hades.

Auf dem Olymp ruft Hera Asklepios und den Iason zu sich und beauftragt
sie, Hilfe für den sterbenden Zeus zu beschaffen. Asklepios erinnert
sich an eine alte Bekannte. Gemeinsam machen sie sich auf den Weg zur
Insel Samothrake.

Auf Samothrake eröffnet die Hexe Hippolaya dem Asklepios, dass Zeus
vergiftet wurde und nur Moirenblut in der Lage ist, den Göttervater zu
retten. Asklepios und die anderen machen sich auf den Weg zur Insel der
Moiren.

Auf der Insel der Moiren verschaffen sie sich mit Hilfe der Hexe
Hippolaya gewaltsam das Blut der Moiren. Die Moire Atropos bleibt dabei
nur verstümmelt zurück. Als sie gerade abreisen wollen, stellt sich die
Hexe Hippolaya ihnen in den Weg und fordert das Blut des Zeus. Im
Gegenzug mischt sie das Gegengift zusammen.

Auf dem Rückweg erscheinen Hera und Athene an Deck der Argo und fordern
das Gegenmittel für sich ein. Das Monstrum Agdistis erscheint an Deck
und greift an. Agdistis kann zurückgeworfen werden, reißt jedoch die
Ziege Colydon mit sich in die Tiefe.

In Hypaipa erscheint der Hades und verlangt den Asklepios. Asklepios
übergibt die Arachne ihrer neuen Lehrmeisterin Orke und will zum Hades
zurückkehren. Die Hybris der Arachne ruft die Athene auf den Plan und
sie rufen einen Wettbewerb aus. In diesem Wettstreit soll ermittelt
werden, wer die größte Weberin ist. Arachne kann den Wettstreit mehr
oder weniger für sich entscheiden, woraufhin Athene sie in eine Spinne
verwandelt. Die Hexe Hippolaya erscheint unerkannt und wirft eine Phiole
in den Verwandlungsstrahl der Athene. Die Arachne verwandelt sich
daraufhin in eine gewaltige Spinnenbestie und verschanzt sich im Tempel
der Athene. Die angreifenden Wachen werden von der Spinnenbestie
zermalmt und sie flüchtet ins Innere der Stadt. Doch statt weiterhin für
Tod und Vernichtung zu sorgen, beginnt sie, die Häuser des
Handwerkerviertels in wunderbare Bildnisse einzuspinnen. Der Anblick
schlägt die Bewohner der Stadt dermaßen in ihren Bann, dass nicht wenige
zu verdursten drohen. Der mittlerweile geheilte Zeus erscheint in der
Stadt, um die Spinnenbestie zu zerschmettern. Der Anblick der Bildnisse
nimmt jedoch selbst ihn gefangen. Als das Haus der Orke komplett
eingesponnen ist, bricht die Spinnenbestie tot zusammen. Der Schemen des
Idmon erscheint und trägt die in das Kind Arachne zurückverwandelte
Spinne zum Hades und folgt ihm in das Totenreich. Zeus lässt daraufhin
einen Regen über der Stadt niedergehen, der alle Bewohner erwachen
lässt.

Asklepios verlässt die Stadt und begegnet auf einer Anhöhe außerhalb der
Stadt Hypaipa einem unerkannten Wanderer. Nach kurzer Unterhaltung
erblickt Asklepios den Hades in der Ferne. Als er sich aufmacht, ihm zu
folgen, erscheint ein kleines Mädchen, flüstert ihm etwas ins Ohr, nimmt
ihn bei der Hand und führt ihn weg von der Straße und vom Hades.

** Gesängekatalog
   :PROPERTIES:
   :CUSTOM_ID: gesängekatalog
   :END:

*** PROLOGOS -- Der Bithynische Eber
    :PROPERTIES:
    :CUSTOM_ID: prologos-der-bithynische-eber
    :END:

**** Fluss Sangarios in Bithynien. Reißende Wässer. Ein Wasserfall in
der Nähe, so laut, dass man sein eigenes Wort kaum versteht.
     :PROPERTIES:
     :CUSTOM_ID: fluss-sangarios-in-bithynien.-reißende-wässer.-ein-wasserfall-in-der-nähe-so-laut-dass-man-sein-eigenes-wort-kaum-versteht.
     :END:

ASKLEPIOS DER HEILER steht an seinen Ufern.

Asklepios füllt seinen Wasserschlauch. Ein Schrei ertönt.

**** Lichtung zwischen hohen Tannen unweit des Flusses Sangarios.
     :PROPERTIES:
     :CUSTOM_ID: lichtung-zwischen-hohen-tannen-unweit-des-flusses-sangarios.
     :END:

Ein MANN liegt am Boden und hält sich den blutigen Bauch. Neben ihm
stehen zwei der ARGONAUTEN. Ein riesiger EBER, erstochen und erschlagen
am Grunde. ASKLEPIOS eilt herbei.

Asklepios findet den sterbenden Idmon und verspricht ihm etwas (was,
erfährt man vorerst nicht).

**** Küste Bithyniens.
     :PROPERTIES:
     :CUSTOM_ID: küste-bithyniens.
     :END:

Ein EBER und ein FRISCHLING über dem Feuer. ASKLEPIOS, einige der
ARGONAUTEN lose um das Feuer herum versammelt. In einigem Abstand IASON,
ihr Anführer, mit dem Rücken zu ihnen und über das Meer blickend.

Die Männer sitzen um das Feuer herum, Iason steht abseits und blickt auf
die Wellen hinaus. Als ihm Peleus etwas zu essen reicht, schlägt der
Iason es ihm aus der Hand. Sie diskutieren, wie schwer es dem
Argonatenführer fällt, wenn einer seiner Männer verstirbt.

**** Küste Bithyniens. Etwas später. Nacht. Die Reste der Schweine sind
zu großen Haufen aus Fett, Knochen und Haut als Dank an die Götter
aufgebahrt.
     :PROPERTIES:
     :CUSTOM_ID: küste-bithyniens.-etwas-später.-nacht.-die-reste-der-schweine-sind-zu-großen-haufen-aus-fett-knochen-und-haut-als-dank-an-die-götter-aufgebahrt.
     :END:

Die ersten ARGONAUTEN ziehen sich in ihre Zelte zurück. ASKLEPIOS, am
Feuer sitzend und sich den Bauch haltend. Ein leerer Teller steht neben
ihm.

Iason erklärt dem Asklepios, den Tod des Idmon nicht zu dulden.

*** ERSTER GESANG -- Wo Argonauten längst Legenden sind
    :PROPERTIES:
    :CUSTOM_ID: erster-gesang-wo-argonauten-längst-legenden-sind
    :END:

**** Stadtmauer zu Kolophon. Purpurne Tücher mit wunderschönen Mustern
wehen im Wind.
     :PROPERTIES:
     :CUSTOM_ID: stadtmauer-zu-kolophon.-purpurne-tücher-mit-wunderschönen-mustern-wehen-im-wind.
     :END:

Ein ALTER MANN mit Schlangenstab kommt die Straße noch Kolophon heran.
Zu seiner Linken blickt er über das Ägäische Meer, zu seiner Rechten
erblickt er die Mauern der Stadt Kolophon.

Der alte Mann trifft auf Hades, der ihn wegen der Heilung eines Toten
mit sich nehmen will. Er handelt aus, dass er vorher noch die Botschaft
vom Tod des Vaters der jungen Arachne überbringen will.

**** Agora zu Kolophon. Reges Treiben.
     :PROPERTIES:
     :CUSTOM_ID: agora-zu-kolophon.-reges-treiben.
     :END:

Der ALTE MANN hinkt auf seinem Schlangenstab durch die Menschenmassen.
Fast alle Bewohner sind in purpurnes Tuch gekleidet.

Er erfährt von einem Händler, dass Arachne all die Tücher gewebt hat und
von dem Händler ausgebeutet wird, ohne, dass sie es weiß. Er kauft eine
Stoffbahn Purpurtuch.

**** Brunnen nahe der Agora zu Kolophon.
     :PROPERTIES:
     :CUSTOM_ID: brunnen-nahe-der-agora-zu-kolophon.
     :END:

ALTER MANN. Ein paar ALTE WEIBER sitzen auf dem Rand des Brunnens.

Er unterhält sich mit einem alten Weib über die Arachne und erfährt,
dass die Nachricht vom Tod ihres Vaters der Arachne das Herz brechen
wird und das sie zu einer ziemlichen Furie werden kann.

**** Flußlauf außerhalb der Stadt Kolophon.
     :PROPERTIES:
     :CUSTOM_ID: flußlauf-außerhalb-der-stadt-kolophon.
     :END:

Ein JUNGES MÄDCHEN schöpft Wasser mit einer Schale. Eine kleine Ziege
steht etwas abseits.

Asklepios findet die Arachne und berichtet ihr vom Wunsch des toten
Vaters, sie nach Hypaipa zu führen. Sie packt ihre Sachen und schließt
sich ihm an.

**** Schenke Demeters Tropfen im Hafen zu Myrina.
     :PROPERTIES:
     :CUSTOM_ID: schenke-demeters-tropfen-im-hafen-zu-myrina.
     :END:

Eine Bande STADTBEWOHNER in Prunkgewändern bei verdünntem Wein.

Ein Schenkenbesucher protzt mit seinem neu erlangten Besitz herum.

**** Hafengassen zu Myrina. Finsterste Nacht. Leise rauschen die Wellen.
     :PROPERTIES:
     :CUSTOM_ID: hafengassen-zu-myrina.-finsterste-nacht.-leise-rauschen-die-wellen.
     :END:

Ein EINSAMER ZECHER torkelt durch die Straßen.

Der einsame Zecher wird von einer schwarzen Gestalt getötet.

*** ZWEITER GESANG -- Die rasenden Rosse des Poseidon
    :PROPERTIES:
    :CUSTOM_ID: zweiter-gesang-die-rasenden-rosse-des-poseidon
    :END:

**** Außerhalb Kolophons. Nördlicher Stadtausgang. Unzählige Hütten
säumen das Land, dunkler Rauch steigt aus allen Dächern in den Himmel
auf.
     :PROPERTIES:
     :CUSTOM_ID: außerhalb-kolophons.-nördlicher-stadtausgang.-unzählige-hütten-säumen-das-land-dunkler-rauch-steigt-aus-allen-dächern-in-den-himmel-auf.
     :END:

ARACHNE, ALTER MANN und die Ziege COLYDON folgen dem Weg aus der Stadt.
Padmilos schließt sich ihnen an.

**** Anhöhe außerhalb der Stadt Kolophon. Abenddämmerung. Die ersten
Lichter der Stadt sind zu sehen.
     :PROPERTIES:
     :CUSTOM_ID: anhöhe-außerhalb-der-stadt-kolophon.-abenddämmerung.-die-ersten-lichter-der-stadt-sind-zu-sehen.
     :END:

ARACHNE, die Ziege COLYDON an der Leine führend, und der von PADMILOS
gestützte ASKLEPIOS kämpfen sich die Steigung hinauf.

Beim Blick zurück erblicken sie persische Schiffe.

**** Anhöhe außerhalb der Stadt Kolophon. Nacht. Das kolophonische Heer
strömt aus der Stadt.
     :PROPERTIES:
     :CUSTOM_ID: anhöhe-außerhalb-der-stadt-kolophon.-nacht.-das-kolophonische-heer-strömt-aus-der-stadt.
     :END:

ARACHNE, ihre Ziege COLYDON, ASKLEPIOS und PADMILOS blicken hinunter zur
Küste.

Sie beobachten die Aufstellung des Heeres, Poseidon greift ein und
zerschmettert die persischen Schiffe. Die Brandpfeile der Perser
schlagen ihn in die Flucht, Poseidon entfesselt den Ketos. Dieser
zerstört die persische Flotte und die Stadt, danach stürzt er sich auf
Poseidon.

*** DRITTER GESANG -- Das Leuchten der Okeaniden
    :PROPERTIES:
    :CUSTOM_ID: dritter-gesang-das-leuchten-der-okeaniden
    :END:

**** Lager auf der Rückseite der Anhöhe. Nacht. Feuerschein.
     :PROPERTIES:
     :CUSTOM_ID: lager-auf-der-rückseite-der-anhöhe.-nacht.-feuerschein.
     :END:

ASKLEPIOS legt ein paar Scheite Holz ins Feuer nach. PADMILOS, ARACHNE,
ihre Ziege COLYDON.

Sie errichten ein Lager und legen sich schlafen. Asklepios hält Wache.

**** Dasselbe Lager. Einige Stunden später. Noch immer Nacht. Das Feuer
ist erloschen.
     :PROPERTIES:
     :CUSTOM_ID: dasselbe-lager.-einige-stunden-später.-noch-immer-nacht.-das-feuer-ist-erloschen.
     :END:

ARACHNE erwacht. Der schlafende PADMILOS. Das Böcklein COLYDON unter
ihrer Decke.

Arachne nimmt die Spur des verschwundenen Asklepios auf.

**** Kleines Kiefernwäldchen. Die Nacht ist hier noch finsterer.
     :PROPERTIES:
     :CUSTOM_ID: kleines-kiefernwäldchen.-die-nacht-ist-hier-noch-finsterer.
     :END:

Die an einen Baum heranschleichende ARACHNE.

Arachne beobachtet den Asklepios dabei, wie er ein Ritual mit einem
Messer durchführt. Padmilos überrascht sie. Asklepios behauptet, ein
Operationsbesteck hergestellt zu haben. Arachne misstraut ihm, sie
setzen ihren Weg gemeinsam fort.

**** Dächer der Stadt Myrina in der Nähe des Hafens. Nacht. Vollmond.
     :PROPERTIES:
     :CUSTOM_ID: dächer-der-stadt-myrina-in-der-nähe-des-hafens.-nacht.-vollmond.
     :END:

Ein SCHATTEN balanciert über die Dächer der Stadt. Auf dem Rücken trägt
er einen vollen Sack.

Autolykos erfährt von dem Fluch auf einer Münze, die er mit sich führt.
Ein schwarzer Schatten verfolgt ihn.

**** Lager auf der Rückseite der Anhöhe. Morgengrauen.
     :PROPERTIES:
     :CUSTOM_ID: lager-auf-der-rückseite-der-anhöhe.-morgengrauen.
     :END:

ARACHNE, ASKLEPIOS und PADMILOS sammeln ihre Sachen ein. Die Ziege
COLYDON steht ein Stück abseits und beobachtet das Treiben.

Sie packen ihre Sachen und beschließen, noch einen letzten Blick auf die
gestrige Vernichtung zu werfen.

**** Andere Seite der Anhöhe. Weiter unten die Küste, davor das Meer
voller Trümmer und Leichen. Wrackteile und unidentifizierbare
Gegenstände liegen bereits am Strand verteilt. Am Horizont zeichnet sich
das erste Licht des nahenden Morgens ab.
     :PROPERTIES:
     :CUSTOM_ID: andere-seite-der-anhöhe.-weiter-unten-die-küste-davor-das-meer-voller-trümmer-und-leichen.-wrackteile-und-unidentifizierbare-gegenstände-liegen-bereits-am-strand-verteilt.-am-horizont-zeichnet-sich-das-erste-licht-des-nahenden-morgens-ab.
     :END:

PADMILOS, den Blick aufs Meer gerichtet. ARACHNE kommt herbei.

Sie beobachten, wie die Okeaniden die Toten ins Wasser hinunterziehen.
Hades erscheint und erinnert Asklepios daran, wem seine Seele gehört.
Als er verschwindet, befühlt Asklepios das Messer in seinem Gewand.

*** VIERTER GESANG -- Hadesbrand
    :PROPERTIES:
    :CUSTOM_ID: vierter-gesang-hadesbrand
    :END:

**** Zwei Wochen später. Äolische Straße nach Myrina. Ein Ochsenkarren
liegt mit gebrochener Achse mitten auf dem Weg.
     :PROPERTIES:
     :CUSTOM_ID: zwei-wochen-später.-äolische-straße-nach-myrina.-ein-ochsenkarren-liegt-mit-gebrochener-achse-mitten-auf-dem-weg.
     :END:

ASKLEPIOS, PADMILOS, ARACHNE, die Ziege COLYDON an der Leine führend,
kommen des Weges. Am Ochsenkarren beschimpft ein HÄNDLER seinen DIENER,
der an der Achse rumhantiert.

Sie treffen auf Ixmos und seinen Diener Pondros. Als Ixmos den Asklepios
bittet, seinen toten Ochsen wiederzuerwecken, nimmt sein Diener Reißaus.
Arachne erzählt ihre Geschichte, die Erinnerungen überwältigen sie und
sie rennt davon.

**** Ein verlassenes Wäldchen etwas abseits der Straße.
     :PROPERTIES:
     :CUSTOM_ID: ein-verlassenes-wäldchen-etwas-abseits-der-straße.
     :END:

ARACHNE, mit Tränen in den Augen, kommt herbeigeeilt. Die Ziege COLYDON
direkt hinter ihr.

**** Äolische Straße nach Myrina. Ein Ochsenkarren liegt mit gebrochener
Achse mitten auf dem Weg. Ein Schrei hallt aus der Ferne.
     :PROPERTIES:
     :CUSTOM_ID: äolische-straße-nach-myrina.-ein-ochsenkarren-liegt-mit-gebrochener-achse-mitten-auf-dem-weg.-ein-schrei-hallt-aus-der-ferne.
     :END:

ASKLEPIOS, PADMILOS und IXMOS.

**** Ein verlassenes Wäldchen etwas abseits der Straße.
     :PROPERTIES:
     :CUSTOM_ID: ein-verlassenes-wäldchen-etwas-abseits-der-straße.-1
     :END:

ARACHNE, laut kreischend, COLYDON, sie am Gewande zupfend, PADMILOS als
Erster eintreffend. Sonst ist niemand zu sehen.

Arachne wird von einem schwarzen Schatten überrascht. Ihre Schreie
locken die anderen an. Als nichts mehr zu sehen ist, beschließen sie
weiterzuziehen.

**** Äolische Straße nach Myrina. Einbruch der Nacht. Ein Ochsenkarren
liegt mit gebrochener Achse mitten auf dem Weg. Ein toter Ochse, an
Überanstrengung verendet, mittlerweile auch der andere in seinem Blute.
     :PROPERTIES:
     :CUSTOM_ID: äolische-straße-nach-myrina.-einbruch-der-nacht.-ein-ochsenkarren-liegt-mit-gebrochener-achse-mitten-auf-dem-weg.-ein-toter-ochse-an-überanstrengung-verendet-mittlerweile-auch-der-andere-in-seinem-blute.
     :END:

ASKLEPIOS, PADMILOS, IXMOS, ARACHNE und COLYDON kehren zurück.

Als sie zurückkehren, ist auch der andere Ochse tot. Asklepios
beschließt, ohne den Ixmos weiterzureisen.

**** Stadtmauer zu Myrina. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: stadtmauer-zu-myrina.-nacht.
     :END:

WACHEN auf den Mauern. ASKLEPIOS, PADMILOS, ARACHNE, die Ziege COLYDON
führend, folgen der letzten Biegung des Weges.

Gegen eine Flasche irgendeines Gebräus lassen die Wache Asklepios,
Arachne, Padmilos und Colydon in die Stadt Myrina.

**** Finstere Gassen innerhalb der Stadt Myrina. Nacht. Vollmond.
     :PROPERTIES:
     :CUSTOM_ID: finstere-gassen-innerhalb-der-stadt-myrina.-nacht.-vollmond.
     :END:

ASKLEPIOS, PADMILOS, ARACHNE und die Ziege COLYDON.

Asklepios erwartet seinen Schatten, stattdessen erscheint ein Zecher,
dann der Hades. Der Schatten erscheint und versucht den Hades zu töten.
Dies misslingt, da kein Toter den Gott des Todes verwunden kann.
Asklepios tötet den Hades mit der Klinge Hadesbrand. Die folgende
Explosion wirft die Umstehenden zu Boden, sie verlieren das Bewusstsein.

*** FÜNFTER GESANG -- Der Ansturm des Zerberus
    :PROPERTIES:
    :CUSTOM_ID: fünfter-gesang-der-ansturm-des-zerberus
    :END:

**** Hades. Das Totenreich. Der Asphodeliengrund.
     :PROPERTIES:
     :CUSTOM_ID: hades.-das-totenreich.-der-asphodeliengrund.
     :END:

Unzählige SCHATTEN irren umher, stehen herum oder gehen belanglosen
Tätigkeiten nach.

Drei Schatten irren im Hades umher und werden durch ein Donnergrollen
erweckt. Nach und nach erinnern sie sich an ihr früheres Leben und
werden stofflich. Einer der Schatten erinnert sich an ein Schiff: Die
Argo.

**** Finstere Gasse innerhalb der Stadt Myrina. Nacht. Vollmond. Die
Stadt ist still wie nie zuvor.
     :PROPERTIES:
     :CUSTOM_ID: finstere-gasse-innerhalb-der-stadt-myrina.-nacht.-vollmond.-die-stadt-ist-still-wie-nie-zuvor.
     :END:

ASKLEPIOS, PADMILOS, ARACHNE und die Ziege COLYDON am Boden. Ein ZECHER,
eine FRAU, ein MANN, allesamt bewusstlos. Ein SCHATTEN kommt über die
Dächer, lautlos, geht in die Hocke und blickt zu den Bewusstlosen
hinunter.

Autolykos will sich gerade über die Bewusstlosen hermachen, als Hermes
erscheint. Er weist ihn darauf hin, dass er den Asklepios bereits kennt
und will ihn dazu anhalten, ihm dabei helfen herauszufinden, was in der
Stadt geschehen ist. Es kommt zum Zerwürfnis zwischen den beiden. Athene
erscheint und berichtet vom Tod des Hades. Die Klinge Hadesbrand nimmt
sie an sich und verschwindet wieder. Hermes verschwindet, die anderen
erwachen nach und nach. Asklepios erkennt den Autolykos wieder, als der
Mann und die Frau erwachen, wollen sie Autolykos zur Rechenschaft
ziehen. Autolykos verschwindet. Sie berichten von der Vernichtung der
Stadt Kolophon. Der Mann ergreift daraufhin aus Angst vor den Göttern
die Flucht, die Frau zwingt die anderen, die Stadt zu verlassen und ruft
die Wachen. Als Asklepios und die anderen davongerannt sind, kracht der
Zerberus durch die Gebäude und an ihr vorbei. Der Anblick bringt die
Frau um den Verstand und lässt sie sterben.

**** Ein paar Gassen weiter. Stille liegt über der Stadt.
     :PROPERTIES:
     :CUSTOM_ID: ein-paar-gassen-weiter.-stille-liegt-über-der-stadt.
     :END:

ASKLEPIOS, rennend und den PADMILOS am Arm führend, ARACHNE, die Ziege
COLYDON, beide ebenfalls rennend.

Zerberus zerreißt den Asklepios.

*** SECHSTER GESANG -- Im Totenreich
    :PROPERTIES:
    :CUSTOM_ID: sechster-gesang-im-totenreich
    :END:

**** Eingang zum Totenreich. Dunkelheit. Felsen.
     :PROPERTIES:
     :CUSTOM_ID: eingang-zum-totenreich.-dunkelheit.-felsen.
     :END:

ASKLEPIOS, nur noch ein toter Schatten.

Asklepios erwacht im Totenreich. Hermes erscheint und geleitet ihn
tiefer in das Totenreich.

**** Ufer des Fluss Styx.
     :PROPERTIES:
     :CUSTOM_ID: ufer-des-fluss-styx.
     :END:

ASKLEPIOS, am Arm geführt von HERMES.

Charon ist nirgends zu sehen. Hermes trägt Asklepios über das Wasser. Am
anderen Ufer vermisst Hermes den Zerberus.

**** Totentreich. Pfahl des Zerberus. Ein Stück abgerissene Kette
baumelt daran.
     :PROPERTIES:
     :CUSTOM_ID: totentreich.-pfahl-des-zerberus.-ein-stück-abgerissene-kette-baumelt-daran.
     :END:

HERMES. ASKLEPIOS.

Keine Spur von Zerberus, die abgerissene Kette zeigt in Richtung des
Totenreiches.

**** Totenreich. Eingang zur Halle der Richter. Schummriges Licht. Ein
zerbrochenes Ruder am Boden.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-eingang-zur-halle-der-richter.-schummriges-licht.-ein-zerbrochenes-ruder-am-boden.
     :END:

HERMES. ASKLEPIOS.

Vor der Halle der Richter liegt ein zerbrochenes Ruder am Boden. Hinter
dem Eingang ist alles dunkel.

**** Totenreich. Halle der Richter. Dunkelheit.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-halle-der-richter.-dunkelheit.
     :END:

HERMES. ASKLEPIOS.

Die toten Richter baumeln von der Decke.

**** Durchgang zum Asphodeliengrund. Schlachtenlärm hebt in der Ferne
an.
     :PROPERTIES:
     :CUSTOM_ID: durchgang-zum-asphodeliengrund.-schlachtenlärm-hebt-in-der-ferne-an.
     :END:

HERMES. ASKLEPIOS.

Hermes und Asklepios werden Zeuge einer Schlacht. Die Toten stürmen
gegen die Feste des Hades, Hades wirft sie zurück. Der Zerberus wird von
den Toten bekämpft, Charon wurde als Geisel genommen. Alle Toten sind
stofflich. Sie erblicken Iason, wie er die Toten anführt. Kurz bevor sie
ihn erreichen wird Iason von Hades zu Boden geworfen, er selbst ist
stark geschwächt, bricht zusammen und wird von Athene in die Burg
geführt.

**** Totenreich. Eine Anhöhe über der Ebene im Asphodeliengrund.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-eine-anhöhe-über-der-ebene-im-asphodeliengrund.
     :END:

IASON, am Boden liegend, HERMES, sich über ihn beugend, ASKLEPIOS kommt
auf seinem Gehstab herangehumpelt.

Hades erscheint wie aus dem Nichts und will Asklepios töten. Athene
erscheint, das Geschoss des Hades prallt an ihrem Harnisch ab. Athene
berichtet, dass Zeus im Sterben liegt und Hera nach Asklepios verlangt
hat. Iason soll ihn hierbei begleiten. Athene bringt sie hierzu auf den
Olymp. Hades schwört, sich an Iason und Asklepios (vielleicht auch
Athene) zu rächen.

**** Berg Olymp. Wolken unter ihnen, Wolken über ihnen, starke Winde
wehen. Um sie herum blauer Himmel. Der Schrei eines Adlers ertönt
irgendwo in der Ferne unter ihnen.
     :PROPERTIES:
     :CUSTOM_ID: berg-olymp.-wolken-unter-ihnen-wolken-über-ihnen-starke-winde-wehen.-um-sie-herum-blauer-himmel.-der-schrei-eines-adlers-ertönt-irgendwo-in-der-ferne-unter-ihnen.
     :END:

ATHENE, ASKLEPIOS, IASON erscheinen.

Aus der Ferne erblicken sie die gewaltige Halle der Götter, geschaffen
von Hephaistos.

**** Pantheon auf dem Berg Olympos.
     :PROPERTIES:
     :CUSTOM_ID: pantheon-auf-dem-berg-olympos.
     :END:

ATHENE, den ASKLEPIOS und den IASON durch einen endlosen Säulengang
führend.

Sie betreten das Pantheon. Poseidon und Ares unterhalten sich. Ares geht
mit finsterem Blick an ihnen vorbei. Asklepios stellt den Poseidon zur
Rede, ob es Absicht war, Kolophon zu zerstören. Der Poseidon verweigert
jedes Gespräch, macht der Athene Vorwürfe und erwähnt, dass der
Göttervater sowieso sterben wird.

**** Pantheon auf dem Olymp. Kammer des Zeus hinter dem Thronsaal.
     :PROPERTIES:
     :CUSTOM_ID: pantheon-auf-dem-olymp.-kammer-des-zeus-hinter-dem-thronsaal.
     :END:

ATHENE, ASKLEPIOS, IASON am Eingang zur Kammer. ZEUS auf seinem Lager am
anderen Ende des Raumes, neben ihm seine Gattin HERA, seine Stirn mit
einem nassen Lappen betupfend.

Asklepios untersucht den Zeus, um das Gift zu ermitteln, das ihm
verabreicht wurde. Die Aufgabe übersteigt seine Fähigketen, so dass er
beschließt, eine “alte Freundin” aufzusuchen. Zuvor jedoch, will er die
Arachne abholen. Gemeinsam wollen sie zur Insel Samothrake, südlich von
Thrakien, reisen. Hera verwandelt sie in Menschen zurück, jedoch haben
sie nur zehn Tage Zeit, in den Olymp zurückzukehren, da sie sonst im
Aether landen. Asklepios nimmt das Blut des Zeus mit sich.

*** SIEBTER GESANG -- Die Flechten des Attis
    :PROPERTIES:
    :CUSTOM_ID: siebter-gesang-die-flechten-des-attis
    :END:

**** Dunkle Gasse innerhalb der Stadt Myrina. Nacht. Stille liegt über
der Stadt.
     :PROPERTIES:
     :CUSTOM_ID: dunkle-gasse-innerhalb-der-stadt-myrina.-nacht.-stille-liegt-über-der-stadt.
     :END:

ARACHNE, PADMILOS und die Ziege COLYDON. Sie betrachten die Reste des
Leichnams des Asklepios.

Athene, Asklepios und Iason erscheinen. Sie weihen die drei anderen in
ihre Pläne ein. Sie folgen ihnen.

**** Insel Samothrake südlich von Thrakien. Hexenküche. Es brodelt und
schmurgelt. Dämpfe erfüllen die Luft, die Wände und Tische sind mit
allerlei Krimskrams bedeckt.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake-südlich-von-thrakien.-hexenküche.-es-brodelt-und-schmurgelt.-dämpfe-erfüllen-die-luft-die-wände-und-tische-sind-mit-allerlei-krimskrams-bedeckt.
     :END:

Eine ALTE FRAU mit Haaren wie Spinnweben, behängt mit allerlei
Glitzerkram, ein Messer in der Hand. Vor ihr liegt ein toter
Rattenkörper.

Sie haut den Rattenkörper entzwei und murmelt etwas davon, dass etwas
seinem Kopf entsteige. Vor dem Haus rumpelt etwas. Hippolaya lässt die
Türen mit aller Gewalt aufschwingen und schlägt einen alten Mann zu
Boden. Draußen erblickt sie vier weitere Gestalten und eine Ziege.

**** Insel Samothrake. Vor dem Hexenhaus.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-vor-dem-hexenhaus.
     :END:

ATHENE, ARACHNE, PADMILOS, IASON und die Ziege COLYDON etwas abseits. Am
Boden vor der Tür ASKLEPIOS.

Sie versuchen, Hippolaya zu überreden, ihnen zu helfen. Die Hexe weigert
sich. Nach einigem Zureden öffnet sie die Tür und bittet Asklepios
allein hinein. Im Inneren des Hauses beginnt es zu rumpeln und zu
blitzen.

**** Insel Samothrake. Hexenküche.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenküche.
     :END:

HIPPOLAYA auf ASKLEPIOS sitzend, beide nur das Nötigste mit den Resten
ihrer Kleider bedeckt.

Asklepios erklärt der Hippolaya, dass er sie wegen dem Argonautenzug
verlassen hat. Es kommt zum Streit zwischen den beiden. Hippolaya
erkennt, dass das Blut nicht von einem Menschen stammt und droht die
Phiole zu zerstören. Iason kommt durchs Fenster gesprungen und entreißt
ihr die Phiole. Als sie auf Iason losgehen will, erscheint Athene in der
Tür und wirft sie zurück. Sie beschließen, die Bewusstlose gegen den
Willen Asklepios' zu fesseln.

**** Insel Samothrake. Vor dem Hexenhaus.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-vor-dem-hexenhaus.-1
     :END:

ARACHNE, PADMILOS, die Ziege COLYDON.

Arachne berichtet Padmilos von ihrer Enttäuschung über ihre bisherige
Reise: Überall wo sie aufkreuzen, lassen sie nichts als Zerstörung
zurück. Kurz darauf verschwindet sie, um sich allein durchzuschlagen.
Padmilos folgt ihr.

**** Insel Samothrake. Hexenküche. Totales Durcheinander.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenküche.-totales-durcheinander.
     :END:

ATHENE, IASON, ASKLEPIOS. Auf einem Stuhl die gefesselte und mehr
schlecht als recht angezogene HIPPOLAYA.

Sie fesseln die Hippolaya und verbinden ihr die Augen. Iason befreit ein
Zyklopenauge, die Hexe zertritt es. Sie berichtet von Mächten, größer
als die Götter und dass sie nun einsieht, ihr Leben mit dem Warten auf
Asklepios verschwendet zu haben. Athene droht Hippolaya zu erwürgen,
Asklepios und Iason können Schlimmeres verhindern. Sie tragen die
Bewusstlose in ihr Bett.

**** Insel Samothrake. Kurze Zeit später vor dem Hexenhaus.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-kurze-zeit-später-vor-dem-hexenhaus.
     :END:

ATHENE vor dem Haus, sich umsehend. IASON tritt aus der Tür, sich die
Hände sauberreibend.

Athene und Iason bemerken, dass die Arachne verschwunden ist (gemeinsam
mit Padmilos und der Ziege Colydon). Iason begibt sich auf die Suche
nach ihr.

**** Insel Samothrake. Dichter Wald. Die Sonne steht knapp über dem
Horizont.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-dichter-wald.-die-sonne-steht-knapp-über-dem-horizont.
     :END:

ARACHNE, die Ziege COLYDON mit sich führend.

Arachne und Colydon schleichen durch immer dichter werdende Wälder.
Plötzlich vernehmen sie ein Weinen. Arachne beschließt, sich
anzuschleichen.

**** Insel Samothrake. Verwaister Tempel tief in den Wäldern. Etwas
Weißes ragt aus dem Eingang einer Gruft und bedeckt den Boden.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel-tief-in-den-wäldern.-etwas-weißes-ragt-aus-dem-eingang-einer-gruft-und-bedeckt-den-boden.
     :END:

Eine KRÄFTIG GEBAUTE FRAU mit einer Krone, die wie eine Stadtmauer
geformt ist, und einem Schleier, sitzt auf einem Marmorfindling und
vergräbt das Gesicht in den Händen. Ihr Schluchzen lässt sie immer
wieder erzitten.

Kybele beweint den Attis. Die vier Zwerge Eurymedon, Alkon, Aitnaios und
Onnes erscheinen und betanzen sie mit obszönen Gesten. Als ein Rufen
ertönt, rasen die Zwerge darauf zu. Die Stimme der Kybele verändert sich
und sie verschwindet in der Gruft.

**** Insel Samothrake. Anderer Teil des Waldes. Abenddämmerung.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-anderer-teil-des-waldes.-abenddämmerung.
     :END:

PADMILOS, sich durch die Bäume kämpfend.

Die vier Zwerge überwältigen den Padmilos.

**** Insel Samothrake. Anderer Teil des Waldes. Abenddämmerung.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-anderer-teil-des-waldes.-abenddämmerung.-1
     :END:

IASON, das Schwert in Vorhalte durch den Wald schleichend.

Iason schleicht durch die Wälder, auf der Suche nach Arachne. Athene
überrascht ihn und berichtet ihm von alten Mächten, deren Anwesenheit
sie spürt. Gemeinsam schleichen sie auf die alten Mächte zu.

**** Insel Samothrake. Verwaister Tempel tief in den Wäldern. Nacht. Die
Haare im Eingang der Gruft leuchten hell.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel-tief-in-den-wäldern.-nacht.-die-haare-im-eingang-der-gruft-leuchten-hell.
     :END:

ARACHNE, den COLYDON an sich drückend.

Die Zwerge kehren zurück und schaffen Padmilos in die Gruft. Arachne
erblickt Iason und Athene und schleicht zu ihnen hinüber. Sie
beschließen, dass Iason allein die Gruft betritt, um den Padmilos zu
retten. Athene, Arachne und Colydon kehren derweil ins Hexenhaus zurück.

**** Insel Samothrake. Hexenhaus. Schlafzimmer.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenhaus.-schlafzimmer.
     :END:

ASKLEPIOS am Bett der bewusstlosen HIPPOLAYA harrend.

Hippolaya erwacht. Asklepios fragt sie nach dem Gegengift. Ein finsteres
Lächeln ist die Antwort.

**** Insel Samothrake. Verwaister Tempel. Innerhalb der Gruft. Völlige
Finsternis, lediglich die weißen Haare auf dem Boden geben ein schwaches
Leuchten von sich.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel.-innerhalb-der-gruft.-völlige-finsternis-lediglich-die-weißen-haare-auf-dem-boden-geben-ein-schwaches-leuchten-von-sich.
     :END:

IASON, das Schwert in Vorhalte durch den Gang schleichend.

Iason durchstreift die Gruft auf der Suche nach Padmilos. In der Ferne
hebt ein Singsang an.

**** Insel Samothrake. Hexenküche.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenküche.-1
     :END:

ATHENE, ARACHNE und die Ziege COLYDON betreten den Raum.

Asklepios kommt hinzu und berichtet der Arachne vom einzigen
Gegenmittel: Moirenblut (Athene ist bereits im Nebenzimmer
verschwunden). Nebenan hebt Tumult an. Als Asklepios hinübereilt, liegt
der Raum in völliger Dunkelheit. Hippolaya hat sich in eine Bestie
verwandelt und die Athene niedergeworfen. Sie einigen sich darauf, dass
Athene in den Olymp zurückkehrt und Hippolaya sich zurückverwandelt.

**** Insel Samothrake. Hexenküche. Schlafzimmer. Dunkelheit.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenküche.-schlafzimmer.-dunkelheit.
     :END:

ASKLEPIOS kommt durch die Tür hereingestürzt.

Asklepios wird Zeuge, wie Hippolaya in Bestiengestalt die Athene besiegt
und sie auffordert, sich nie wieder bei ihr blicken zu lassen. Ansonsten
werde sie die Athene töten. Athene gehorcht und verschwindet.

**** Insel Samothrake. Verwaister Tempel. Innerhalb der Gruft. Schwaches
Licht einer Fackel. Der Boden von weißen Haaren bedeckt.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel.-innerhalb-der-gruft.-schwaches-licht-einer-fackel.-der-boden-von-weißen-haaren-bedeckt.
     :END:

IASON, durch den Gang schleichend.

Iason gerät (wie Padmilos) in die Gefangenschaft der Kybele. Athene
rettet beide. Sie öffnen den Altar und betrachten den Attis. Athene
streichelt ihm über die Wange. Iason bringt der Arachne eine lange
Strähne des Haares des Attis mit. Bevor sie gehen, durchschneidet Iason
den Hals des Attis und der Kybele.

**** Insel Samothrake. Verwaister Tempel. Draußen vor dem Eingang der
Gruft.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel.-draußen-vor-dem-eingang-der-gruft.
     :END:

ATHENE, IASON, die aufgewickelte weiße Strähne über der Schulter
tragend, PADMILOS treten aus der Gruft ins Freie.

Athene lässt ihre Waffen verschwinden und verabschiedet sich auf den
Olymp. Vorher weist sie den Padmilos an, sich von seinen Zweifeln zu
verabschieden. Iason fordert ihn anschließend ebenfalls noch einmal
eindringlich auf, mehr an sich zu glauben. Padmilos verspricht, es zu
versuchen.

**** Insel Samothrake. Hexenküche.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenküche.-2
     :END:

ASKLEPIOS, in einer Ecke sitzend, ARACHNE am Tisch, mit dem COLYDON
spielend. IASON betritt den Raum, die aufgewickelten weißen Strähnen
über einen Stuhl werfend, PADMILOS, ihm folgend.

Asklepios berichtet Iason vom Gegengift, dem Moirenblut. Arachne ist
ujnterdessen von den weißen Haaren völlig fasziniert. Iason will die
Argo aus dem Hades bergen, dazu muss Hippolaya ihre Fehde mit Athene
begraben. Asklepios will sich vom Zustand des Zeus überzeugen, daher
beschließen sie, in den Olymp aufzubrechen. Mit Unbehagen lässt
Asklepios Arachne bei der Hexe zurück. Iason berichtet seine
Todesgeschichte. Iason kann alle überzeugen, mit ihm zu kommen. Der
Hippolaya verspricht er, sie darf aus der Festung der Moiren alles
mitnehmen, was sie möchte, solang sie ihnen das Moirenblut lässt. Das
Moirenheim wird als riesige Festung im Westen geschildert.

**** Insel Samothrake. Vor dem Hexenhaus.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-vor-dem-hexenhaus.-2
     :END:

IASON, PADMILOS.

Iason ruft nach Hera. Ein Pfau erscheint zwischen den Bäumen. Kurz
darauf verschwinden sie. Zwischen den Bäumen hinter den Bäumen ertönt
eine Frauenstimme, reißt den Pfau zu sich und entfernt sich. Padmilos
hat das Verschwinden des Pfaus aus dem Inneren des Hauses beobachtet.

*** ACHTER GESANG -- Jenseits des Okeanos
    :PROPERTIES:
    :CUSTOM_ID: achter-gesang-jenseits-des-okeanos
    :END:

**** Unbekannte Höhle. Dunkelheit.
     :PROPERTIES:
     :CUSTOM_ID: unbekannte-höhle.-dunkelheit.
     :END:

IASON und PADMILOS erscheinen.

Athene erscheint (sie schleudert das Schwert des Iason zur Seite) und
erzählt ihnen, dass Hera die Götter selbst für den Anschlag auf Zeus
verdächtigt. Sie verlangt von Asklepios die Phiole mit dem Zeusblut.
Asklepios reicht ihr eine Phiole. Asklepios berichtet von ihrem Plan und
fragt Athene, ob sie sie direkt auf die Moireninsel bringen kann, Athene
verneint, da Götter dort keine Macht besitzen. Athene sagt ihre
Unterstützung zu, soweit es ihr möglich ist. Asklepios schlägt einen
Pakt vor: Sie wollen ihr Leben an das Leben des Zeus koppeln. Sie gehen
zu Hera, um den Schwur ändern zu lassen.

**** Pantheon auf dem Olymp. Kammer des Zeus hinter dem Thronsaal.
     :PROPERTIES:
     :CUSTOM_ID: pantheon-auf-dem-olymp.-kammer-des-zeus-hinter-dem-thronsaal.-1
     :END:

ATHENE, ASKLEPIOS, IASON erscheinen. ZEUS auf seinem Lager, kaum noch
als der mächtige Gott zu erkennen, der er ist. Seine Gattin HERA neben
ihm, die Hände im Schoß gefaltet, im Sitzen schlafend.

Hera koppelt das Leben des Iason und Asklepios an das des Zeus. Nachdem
sie verschwunden sind, brabbelt Zeus ein paar unverständliche Worte.

**** Totenreich. Eine Anhöhe über der Ebene im Asphodeliengrund. Die
Toten stürmen noch immer gegen die Mauern der Hadesfestung, werden vom
auf den Zinnen kauernden Hades Reihe für Reihe zurückgeworfen, sammeln
sich und greifen erneut an. Ein endloses Schauspiel.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-eine-anhöhe-über-der-ebene-im-asphodeliengrund.-die-toten-stürmen-noch-immer-gegen-die-mauern-der-hadesfestung-werden-vom-auf-den-zinnen-kauernden-hades-reihe-für-reihe-zurückgeworfen-sammeln-sich-und-greifen-erneut-an.-ein-endloses-schauspiel.
     :END:

ATHENE, IASON, ASKLEPIOS erscheinen. HERMES, kniend, die Schlacht
betrachtend.

Die Götter vereinen die Kräfte und verwandeln die Toten in einer
gewaltigen Explosion in Schatten zurück.

**** Totenreich. Asphodeliengrund. Hinter den Zinnen der Hadesfestung.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-asphodeliengrund.-hinter-den-zinnen-der-hadesfestung.
     :END:

HADES, HERMES in lockeren Plausch verwickelt. ATHENE, IASON und
ASKLEPIOS erscheinen.

HADES hat die Herrschaft übers Totenreich verloren. Er verweigert ihnen
die Hilfe, verrät ihnen jedoch, dass die Argo asich unweit des Ufers des
Kokytos befindet. Er weist sie an, die Schatten aus dem Kokytos trinken
zu lassen, so dass sie sich erinnern und wieder stofflich werden. Er
zeigt Athene den genauen Ort. Hermes schließt sich ihnen an.

**** Totenreich. Asphodeliengrund. Ufer des Flusses Kokytos. Unzählige
Schatten in verschiedenen Stadien der Stofflichkeit wimmeln um sie
herum.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-asphodeliengrund.-ufer-des-flusses-kokytos.-unzählige-schatten-in-verschiedenen-stadien-der-stofflichkeit-wimmeln-um-sie-herum.
     :END:

ATHENE, IASON, ASKLEPIOS und HERMES erscheinen.

Sie erblicken das Bugspriet in einiger Entfernung.

**** Totenreich. Asphodeliengrund. Unweit des Flusses Kokytos. Ein
Bugspriet ragt aus der Erde. Unzählige Schatten wimmeln um ihn herum.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-asphodeliengrund.-unweit-des-flusses-kokytos.-ein-bugspriet-ragt-aus-der-erde.-unzählige-schatten-wimmeln-um-ihn-herum.
     :END:

ATHENE, IASON, ASKLEPIOS und HERMES.

Die Schatten fallen den Hermes an. Mithilfe seines schnellen Laufs legt
er das Schiff frei. Er zieht einen Graben zum Kokytos, so dass Wasser in
die ausgehobene Grube fließt. Da kein Wind herrscht, machen sich Athene
und Hermes auf, den Charon zu suchen, um ihn zu fragen, wie das Schiff
hierher gekommen ist.

**** Totenreich. Ufer des Styx.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-ufer-des-styx.
     :END:

CHARON, vom Rücken des ZERBERUS absteigend. Der Höllenhund tritt ans
Wasser heran und beginnt zu trinken.

Athene bittet Charon um seine Hilfe. Diese will er nur gewähren, wenn
Athene herausfindet, wie die Argo an ihre Position gebracht wurde.

**** Totenreich. Asphodeliengrund. Unweit des Flusses Kokytos an Bord
der Argo.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-asphodeliengrund.-unweit-des-flusses-kokytos-an-bord-der-argo.
     :END:

IASON, ASKLEPIOS.

Athene berichtet vom Treffen mit Charon. Hermes berichtet von Fußspuren,
die er gesehen hat. Asklepios schließt daraus, dass der Zerberus das
Schiff hergeschleppt hat. Athene bricht auf zu Charon, um ihm von ihrem
Fund zu berichten.

**** Totenreich. Asphodeliengrund. Unweit des Flusses Kokytos an Bord
der Argo. Einige Stunden später.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-asphodeliengrund.-unweit-des-flusses-kokytos-an-bord-der-argo.-einige-stunden-später.
     :END:

IASON, auf dem Deck liegend, ASKLEPIOS, in Gedanken. HERMES, zu den
Schatten hinunterblickend.

Charon erscheint auf dem Zerberus und zieht sie auf den Kokytos. Ihr
nächstes Ziel ist Kap Tainaron. Athene will sich dort um Arachne
kümmern.

**** Totenreich. Flusses Kokytos an Bord der Argo. Einige Stunden
später.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-flusses-kokytos-an-bord-der-argo.-einige-stunden-später.
     :END:

IASON, am Steuerrad. ASKLEPIOS, HERMES und ATHENE über die Reling
gelehnt. CHARON auf dem ZERBERUS am Ufer des Flusses das Schiff ziehend.

Hades erscheint am Ufer. Hermes schafft es, ihn zu besänftigen. Sie
nähern sich dem Ausgang, Wind ergreift die Segel. Charon auf Zerberus
verabschiedet sich, Athene, Asklepios, Hermes und Iason setzen ihren Weg
auf der Argo fort.

**** Kap Tainaron. Sturm und Brandung. Wellen erfassen die Argo.
     :PROPERTIES:
     :CUSTOM_ID: kap-tainaron.-sturm-und-brandung.-wellen-erfassen-die-argo.
     :END:

IASON, am Steuerruder. ATHENE, HERMES, sich an der Reling festhaltend.
ASKLEPIOS, die Segel festzurrend.

Sie erreichen Kap Tainaron. Hermes ist seekrank und beschließt, das
Schiff zu verlassen. Athene will Arachne aufsuchen. Hermes geht mit ihr.

*** NEUNTER GESANG -- Zurück im Hexenhain
    :PROPERTIES:
    :CUSTOM_ID: neunter-gesang-zurück-im-hexenhain
    :END:

**** Insel Samothrake. Vor dem Hexenhaus.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-vor-dem-hexenhaus.-3
     :END:

ATHENE, HERMES erscheinen.

Hermes beschließt, dem Tempel der (vernichteten) Kybele einen Besuch
abzustatten. Athene geht in das Hexenhaus.

**** Insel Samothrake. Hexenküche. Unaufgeräumtes Chaos.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-hexenküche.-unaufgeräumtes-chaos.
     :END:

PADMILOS auf einem Stuhl kippelnd, die Füße auf dem Tisch. Weiße
Strähnen führen ins Schlafzimmer. ATHENE betritt den Raum.

Hippolaya ist verschwunden. Arachne wirft sich die weißen Haare über die
Schulter. Athene bringt Padmilos, Arachne, Colydon auf die Argo.

**** Insel Samothrake. Verwaister Tempel tief in den Wäldern. Weiße
Haare ragen aus dem Inneren.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel-tief-in-den-wäldern.-weiße-haare-ragen-aus-dem-inneren.
     :END:

HERMES.

Hermes betrachtet die weißen Haare und den Eingang der Gruft. Er will
nur einen kurzen Blick wagen und verschwindet im Eingang.

**** Insel Samothrake. Verwaister Tempel tief in den Wäldern. Innerhalb
der Gruft. Ein schwaches Leuchten am Boden.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel-tief-in-den-wäldern.-innerhalb-der-gruft.-ein-schwaches-leuchten-am-boden.
     :END:

HERMES.

Ein scheußliches Monster schleicht durch die Gänge. Bestien-Hippolaya
eröffnet dem Hermes, dass sich Agdistis seine Haare zurückholen möchte.
Daraufhin tötet sie den Hermes.

**** Insel Samothrake. Verwaister Tempel tief in den Wäldern. Innerhalb
der Gruft am Altar des Attis.
     :PROPERTIES:
     :CUSTOM_ID: insel-samothrake.-verwaister-tempel-tief-in-den-wäldern.-innerhalb-der-gruft-am-altar-des-attis.
     :END:

Eine in Weiß gekleidete, leuchtende GESTALT erscheint.

Hera holt ihren Pfau zurück.

**** Ionisches Meer. Deck der Argo. Ruhige See.
     :PROPERTIES:
     :CUSTOM_ID: ionisches-meer.-deck-der-argo.-ruhige-see.
     :END:

IASON, am Steuerrad. ASKLEPIOS, neben ihm über das Meer blickend.
ATHENE, ARACHNE, COLYDON und PADMILOS erscheinen.

Hera erscheint und berichtet vom Tod des des Hermes und von ihrer
Vision, dass alle an Deck von Agdistis zerrissen werden. Agdistis
erscheint, die Sandalen des Hermes an den Füßen, wird von Colydon und
Iason besiegt und reißt den Colydon mit sich in die Tiefe.

**** Ionisches Meer. Deck der Argo. Ruhige See. Die ersten Sterne zeigen
sich am Firmament.
     :PROPERTIES:
     :CUSTOM_ID: ionisches-meer.-deck-der-argo.-ruhige-see.-die-ersten-sterne-zeigen-sich-am-firmament.
     :END:

IASON, am Steuerrad. ASKLEPIOS, an der Reling. ARACHNE kehrt an Deck
zurück.

**** Tage später. Deck der Argo. Ruhige See, die Sonne brennt.
     :PROPERTIES:
     :CUSTOM_ID: tage-später.-deck-der-argo.-ruhige-see-die-sonne-brennt.
     :END:

IASON, am Steuerrad. PADMILOS, über die Reling gelehnt.

**** Tage später. Meer. Deck der Argo. Sternenklare Nacht. Ein Seil ist
um das Steuerruder gewickelt.
     :PROPERTIES:
     :CUSTOM_ID: tage-später.-meer.-deck-der-argo.-sternenklare-nacht.-ein-seil-ist-um-das-steuerruder-gewickelt.
     :END:

ASKLEPIOS, über die Reling blickend.

**** Tage später. Meer. Deck der Argo. Brütende Hitze. Ein Seil ist um
das Steuerruder gelegt.
     :PROPERTIES:
     :CUSTOM_ID: tage-später.-meer.-deck-der-argo.-brütende-hitze.-ein-seil-ist-um-das-steuerruder-gelegt.
     :END:

ARACHNE, auf dem Deck liegend und in den Himmel starrend.

**** Tage später. Ein Meer aus Nebel. Deck der Argo. Feuchte und kühle
Luft.
     :PROPERTIES:
     :CUSTOM_ID: tage-später.-ein-meer-aus-nebel.-deck-der-argo.-feuchte-und-kühle-luft.
     :END:

IASON, allein an Deck und das Schiff führend.

**** Tage (oder bloß Stunden) später. Ein Meer aus Nebel. Deck der Argo.
     :PROPERTIES:
     :CUSTOM_ID: tage-oder-bloß-stunden-später.-ein-meer-aus-nebel.-deck-der-argo.
     :END:

ASKLEPIOS, allein an Deck.

**** Stunden (oder Tage) später. Ein Meer aus Nebel, ein Meer aus Fäden.
Deck der Argo.
     :PROPERTIES:
     :CUSTOM_ID: stunden-oder-tage-später.-ein-meer-aus-nebel-ein-meer-aus-fäden.-deck-der-argo.
     :END:

ASKLEPIOS, IASON, ARACHNE, PADMILOS, an Deck auf und abschreitend und
die Fäden betrachtend.

Sie erreichen die Insel der Moiren. Kurz darauf schlägt die Hexe
Hippolaya an Deck auf und schließt sich ihnen an.

*** ZEHNTER GESANG -- Drei Schwestern
    :PROPERTIES:
    :CUSTOM_ID: zehnter-gesang-drei-schwestern
    :END:

**** Unbekannte Insel in unbekannten Gewässern. Eine Hütte in der Mitte
der Insel. Fäden kommen aus dem Fenster, fächern sich in unzählige Fäden
auf und verlieren sich nach einiger Entfernung in dem Nebel, der die
Insel zu allen Seiten umgibt.
     :PROPERTIES:
     :CUSTOM_ID: unbekannte-insel-in-unbekannten-gewässern.-eine-hütte-in-der-mitte-der-insel.-fäden-kommen-aus-dem-fenster-fächern-sich-in-unzählige-fäden-auf-und-verlieren-sich-nach-einiger-entfernung-in-dem-nebel-der-die-insel-zu-allen-seiten-umgibt.
     :END:

IASON, ASKLEPIOS, HIPPOLAYA, ARACHNE, PADMILOS.

Sie springen einer nach dem anderen von Bord der im Sand gelandeten Argo
und setzen einen ersten Fuß auf die Insel. Hippolaya stellt sich vor die
Hütte und behauptet, von den wunderschönen Gesängen der Moiren bis
hierher gelockt worden zu sein. Die Moiren bitten sie hinein. Die
anderen stellt sie als ihre Begleiter vor, die ihr Schiff lenkten. Auch
sie dürfen die Hütte betreten.

**** Innerhalb der Hütte. Große Stube.
     :PROPERTIES:
     :CUSTOM_ID: innerhalb-der-hütte.-große-stube.
     :END:

HIPPOLAYA, IASON, ASKLEPIOS, ARACHNE und PADMILOS. Im Raum verteilt
sitzen DREI WEIBER. Ihre Körper sehen völlig normal aus, erst beim
zweiten Blick erkennt man, dass ihre Arme und Hände wie die Fangbeine
von Gottesanbeterinnen geformt sind.

Sie gelangen an das Moirenblut. Hippolaya wirft alle Moiren zu Boden und
zerstört das Spinnrad.

**** Insel der Moiren. Außerhalb der Hütte.
     :PROPERTIES:
     :CUSTOM_ID: insel-der-moiren.-außerhalb-der-hütte.
     :END:

IASON, ASKLEPIOS, HIPPOLAYA, ARACHNE, PADMILOS. Zur Argo eilend.

Hippolaya hüllt die Argo in eine schwarze Blase und verlangt das Blut
des Zeus. Widerwillig gibt Asklepios ihr das Fläschchen. Die Hexe rührt
ein Gegenmittel an und gibt es Asklepios. Das Tuch mit dem Moirenblut
und die Hälfte des vergifteten Zeusblutes behält sie. Sie verabschiedet
sich von den anderen und bleibt auf der Insel.

*** ELFTER GESANG -- Rückweg
    :PROPERTIES:
    :CUSTOM_ID: elfter-gesang-rückweg
    :END:

**** Tage (oder Wochen?) später. Offene See, jenseits des Nebels.
     :PROPERTIES:
     :CUSTOM_ID: tage-oder-wochen-später.-offene-see-jenseits-des-nebels.
     :END:

IASON, am Steuerruder und das Schiff führend. ASKLEPIOS, über die Reling
gebeugt und über das Meer blickend. ARACHNE, auf dem Deck liegend und in
den Himmel blickend. PADMILOS, hinter dem Iason auf der Reling sitzend
und in Gedanken versunken.

In der Ferne erblicken sie die Peloponnes und wundern sich, dass Athene
sie nicht abholt. Sie beschließen nach Kap Tainaron und in den Hades zu
segeln, um sich vom Totengott auf den Olymp bringen zu lassen. Athene
erscheint jedoch und verlangt die Phiole mit dem Gegenmittel. Hera
erscheint und bittet gemeinsam mit der Athene nach dem Gegenmittel.
Asklepios holt eine Phiole hervor und wirft sie ins Meer. Hera kann dies
verhindern und sie verschwinden auf den Olymp. Arachne verliert ihren
Glauben an die Götter und zieht sich zurück unter Deck. Asklepios holt
eine weitere Ampulle hervor, diesmal ist es das richtige Gegegngift, und
hält Iason an, Kurs auf den Olymp zu setzen. Iason setzt Kurs auf den
Hades, damit dieser sie hinauf in den Olymp bringt.

**** Pantheon auf dem Olymp. Kammer des Zeus hinter dem Thronsaal.
     :PROPERTIES:
     :CUSTOM_ID: pantheon-auf-dem-olymp.-kammer-des-zeus-hinter-dem-thronsaal.-2
     :END:

HERA, aufgeregt durch den Saal schreitend. ATHENE, über den ZEUS
gebeugt. Der Göttervater liegt in seinem Schweiße auf seinem Lager und
rührt sich nicht.

Iason und Asklepios erscheinen gemeinsam mit dem Hades. Asklepios
verabreicht Zeus das richtige Heilmittel. Zeus erwacht. Asklepios bittet
darum, zusammen mit Arachne nach Hypaipa gebracht zu werden. Hades
willigt ein.

**** Totenreich. Asphodeliengrund. Ufer des Flusses Kokytos an Bord der
Argo. Unzählige Schatten wandeln um das Schiff herum.
     :PROPERTIES:
     :CUSTOM_ID: totenreich.-asphodeliengrund.-ufer-des-flusses-kokytos-an-bord-der-argo.-unzählige-schatten-wandeln-um-das-schiff-herum.
     :END:

ARACHNE. PADMILOS.

Hades, Iason und Asklepios erscheinen. Iason kehrt ins Totenreich zurück
(Hades reicht ihm zuvor einen Schluck Wasser aus dem Fluss Lethe). Die
anderen bringt Hades nach Hypaipa.

*** ZWÖLFTER GESANG -- Hypaipa
    :PROPERTIES:
    :CUSTOM_ID: zwölfter-gesang-hypaipa
    :END:

**** Ein gutes Stück außerhalb der Stadt Hypaipa am Fuße des Berges
Aipos. Eine Straße schlängelt sich durch die karge Vegetation auf eine
Stadt zu. Ein Obelisk erhebt sich über alle anderen Gebäude in der
Ferne.
     :PROPERTIES:
     :CUSTOM_ID: ein-gutes-stück-außerhalb-der-stadt-hypaipa-am-fuße-des-berges-aipos.-eine-straße-schlängelt-sich-durch-die-karge-vegetation-auf-eine-stadt-zu.-ein-obelisk-erhebt-sich-über-alle-anderen-gebäude-in-der-ferne.
     :END:

HADES, ASKLEPIOS, ARACHNE und PADMILOS erscheinen.

Sie verabschieden sich von Hades. Asklepios willigt ein, dem Hades zu
folgen, sobald er Arachne bei ihrer neuen Herrin abgeliefert hat.
Padmilos fragt den Asklepios weiter nach Zeus aus. Asklepios muss
eingestehen, dass Zeus sich wie ein Arschloch aufgeführt hat.

**** Straße nach Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: straße-nach-hypaipa.
     :END:

ARACHNE, PADMILOS und ASKLEPIOS ziehen des Weges.

Padmilos quetscht den Asklepios über den Göttervater aus. Der Heiler
gesteht ein, dass Zeus “ein Arschloch” ist.

**** Straße nach Hypaipa. Nahe der Stadtmauer. Ein liegen gebliebener
Ochsenkarren blockiert die Straße.
     :PROPERTIES:
     :CUSTOM_ID: straße-nach-hypaipa.-nahe-der-stadtmauer.-ein-liegen-gebliebener-ochsenkarren-blockiert-die-straße.
     :END:

Ein HÄNDLER schwirrt aufgeregt um die Ochsen und den Wagen herum.
ARACHNE, ASKLEPIOS und PADMILOS nähern sich ihm.

Ixmos begegnet ihnen und lehnt jede Hilfe von ihnen ab. Um ein Haar
alarmiert er die Wachen.

**** Stadttor nach Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: stadttor-nach-hypaipa.
     :END:

Eine WACHE auf jeder Seite des breiten Durchgangs. ARACHNE, ASKLEPIOS
und PADMILOS nähern sich.

Sie erreichen das Stadttor. Die Wachen fragen nach ihrer Begegnung mit
Ixmos.

**** Handwerkerviertel der Stadt Hypaipa. Der Abend dämmert.
     :PROPERTIES:
     :CUSTOM_ID: handwerkerviertel-der-stadt-hypaipa.-der-abend-dämmert.
     :END:

ARACHNE, ASKLEPIOS und PADMILOS nähern sich einem gut in Schuss
gehaltenen Gebäude.

Sie erreichen das Haus der Orke.

**** Haus der Orke zu Hypaipa. Ein riesiger Raum mit hoher Decke. Alles
ist dunkel bis auf einen gewaltigen Webstuhl in der Mitte des Raumes,
der von einer einzelnen Kerze beleuchtet wird.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke-zu-hypaipa.-ein-riesiger-raum-mit-hoher-decke.-alles-ist-dunkel-bis-auf-einen-gewaltigen-webstuhl-in-der-mitte-des-raumes-der-von-einer-einzelnen-kerze-beleuchtet-wird.
     :END:

ORKE, die anderen hineinführend. PADMILOS. ARACHNE. ASKLEPIOS.

Arachne webt zum Beweis ihrer Fertigkeiten einen Faden aus den Flechten
des Attis. Asklepios verabschiedet sich. Orke überlässt Arachne den
Webstuhl für den Rest der Nacht.

**** Vor dem Haus der Orke zu Hypaipa. Tiefschwarze Nacht.
     :PROPERTIES:
     :CUSTOM_ID: vor-dem-haus-der-orke-zu-hypaipa.-tiefschwarze-nacht.
     :END:

ASKLEPIOS, aus dem Hause tretend.

Er rennt mit dem Gegenüber zusammen. Er zeigt seinen leeren Mund und den
Münzabdruck auf seiner Zunge. Ein Schatten beobachtet sie von den
Dächern aus und ergreift die Flucht. Asklepios beschließt, vorerst nicht
zum Hades zurückzukehren.

**** Haus der Orke zu Hypaipa. Einige Stunden später. Vor den Fenstern
tiefschwarze Nacht.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke-zu-hypaipa.-einige-stunden-später.-vor-den-fenstern-tiefschwarze-nacht.
     :END:

ORKE, am Webstuhl arbeitend. PADMILOS, lang ausgestreckt in einem Stuhl
sitzend. ARACHNE, in Gedanken und den gewebten Faden um einen Finger
wickelnd.

Statt schlafen zu gehen wie sie und Padmilos, befiehlt die Orke der
Arachne, ihre Arbeit am Webstuhl zu übernehmen.

**** Haus der Orke zu Hypaipa. Früher Morgen. Licht dringt durch die
Fenster.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke-zu-hypaipa.-früher-morgen.-licht-dringt-durch-die-fenster.
     :END:

ARACHNE, am Webstuhl eingeschlafen. ORKE kommt die Treppe herunter.

Orke erbleicht, als Padmilos ihr die in das Tuch eingewobene Signatur
zeigt. Er bringt Arachne in ihr Bett.

**** Haus der Orke am nächsten Morgen.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke-am-nächsten-morgen.
     :END:

ORKE am Webstuhl sitzend. PADMILOS beim Aufräumen der Küche. ARACHNE
kommt die Stufen herunter.

Arachne lästert den Göttern, die erboste Orke flüchtet zum Athene-Tempel
um die Gotteslästerung wieder reinzuwaschen.

**** Haus der Orke. Einige Stunden später.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-einige-stunden-später.
     :END:

PADMILOS, herumsitzend. ARACHNE, am Webstuhl und die Arbeit der Orke
weiterführend. Die Tür springt auf, herein tritt die ORKE, begleitet von
zwei starken MÄNNERN und einer FRAU in weißen, wallenden Gewändern.

Orke erscheint mit einer Frau in weißen Gewändern und zwei starken
Männern. Sie zerren die Arachne aus dem Haus.

**** Tempel der Athene zu Hypaipa. Der Kopf der Göttin ragt über die
Säulen hervor, dahinter ragt ein Obelisk in den Himmel.
     :PROPERTIES:
     :CUSTOM_ID: tempel-der-athene-zu-hypaipa.-der-kopf-der-göttin-ragt-über-die-säulen-hervor-dahinter-ragt-ein-obelisk-in-den-himmel.
     :END:

ARACHNE, von zwei Männern getragen, eine FRAU in weißen Gewändern und
ORKE erscheinen.

Sie zwingen Arachne gewaltsam, die Athene anzubeten. Stattdessen läuft
Arachne davon.

**** Haus der Orke. Eine Weile später. Der Altar der Athene ist völlig
zerstört.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-eine-weile-später.-der-altar-der-athene-ist-völlig-zerstört.
     :END:

PADMILOS, auf Knien die Trümmerteile zusammensuchend. ORKE kommt durch
die Tür.

Orke kehrt nach Hause zurück. Der Athene-Altar wurde von Arachne völlig
zerstört. Orke beschließt, Arachnes Schicksal in die Hände der Götter zu
legen.

**** Einige Zeit später auf den Dächern der Stadt Hypaipa. Tiefschwarze
Nacht.
     :PROPERTIES:
     :CUSTOM_ID: einige-zeit-später-auf-den-dächern-der-stadt-hypaipa.-tiefschwarze-nacht.
     :END:

ASKLEPIOS und der SCHEMEN, hockend, auf das Haus der Orke
hinunterblickend.

Sie beobachten, wie Orke spätnachts heimkehrt. Als der Schatten
erscheint, nimmt der Schemen die Verfolgung auf.

**** Vor dem Haus der Orke. Einige Tage später. Später Abend.
     :PROPERTIES:
     :CUSTOM_ID: vor-dem-haus-der-orke.-einige-tage-später.-später-abend.
     :END:

Eine ALTE FRAU erscheint wie aus dem Nichts.

Die alte Frau (Athene) erzählt von der lästerlichen Arachne und dass sie
sie von ihrem hohen Ross und ihrem blasphemischen Pfad abbringen will.

**** Haus der Orke.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.
     :END:

ORKE, die ALTE FRAU in das Haus führend. PADMILOS, mit einem Becher an
einem Tisch sitzend und sich zur Begrüßung erhebend.

Die Alte sieht sich die in ihre Kammer zurückgezogen lebende Arachne an.
Arachne folgt ihr hinunter und erkennt sie als Athene. Athene schlägt
ihr einen Wettstreit vor. Arachne nimmt an. Orke soll Boten nach ganz
Griechenland senden, damit sie allen von dem Wettstreit erzählen. Der
Wettstreit beginnt in einem Monat, zehn Tage soll jede weben und ihr
Stück auf dem Markte zu Hypaipa präsentieren.

*** DREIZEHNTER GESANG -- Der Wettbewerb
    :PROPERTIES:
    :CUSTOM_ID: dreizehnter-gesang-der-wettbewerb
    :END:

**** Über den Dächern der Stadt Hypaipa. Marktviertel.
     :PROPERTIES:
     :CUSTOM_ID: über-den-dächern-der-stadt-hypaipa.-marktviertel.
     :END:

ASKLEPIOS, sein SCHEMEN.

Asklepios und sein Schemen ergreifen Autolykos. Er trägt die Klinge
Hadesbrand bei sich. Asklepios nimmt die Klinge an sich. Autolykos
erfährt von Asklepios, dass Hermes wahrscheinlich tot ist. Er schwört,
seinen Vater zu finden und verschwindet über die Dächer der Stadt. Der
Schatten erhält seine Münze zurück.

**** Haus der Orke. Kammer der Arachne.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-kammer-der-arachne.
     :END:

ARACHNE, völlig abgemagert, im Bett liegend und die Decke anstarrend.
Die Tür öffnet sich einen Spalt weit. Eine FREMDE STIMME dringt an ihr
Ohr.

Die fremde Stimme eröffnet der Arachne, dass der Wettkampf beginnt.

**** Vor dem Haus der Orke. Dritter Tag des Wettkampfs.
     :PROPERTIES:
     :CUSTOM_ID: vor-dem-haus-der-orke.-dritter-tag-des-wettkampfs.
     :END:

ASKLEPIOS hält auf die Haustür zu.

Asklepios auf dem Weg zur Arachne.

**** Innerhalb des Hauses der Orke. Völlige Finsternis. Sämtliche
Fenster sind mit schwarzen Tüchern verhangen.
     :PROPERTIES:
     :CUSTOM_ID: innerhalb-des-hauses-der-orke.-völlige-finsternis.-sämtliche-fenster-sind-mit-schwarzen-tüchern-verhangen.
     :END:

PADMILOS, den ASKLEPIOS in das Haus führend. Am Webstuhl die völlig
ausgemergelte ARACHNE in Arbeitswut.

Padmilos nimmt ihn überrascht in Empfang und bittet ihn, sich die Orke
anzusehen. Die Arachne ist völlig abgemagert und der Arbeitswut am
Webstuhl verfallen.

**** Zimmer der Orke.
     :PROPERTIES:
     :CUSTOM_ID: zimmer-der-orke.
     :END:

ORKE, unter schweren Laken liegend, schwer atmend und die Decke
anstarrend.

Asklepios sieht sich die weggetretene und fast tote Orke an. Die Angst
vor den Göttern und der Gottestlästerlichkeit der Arachne haben sie ins
Delirium getrieben.

**** Haus der Orke. Erdgeschoss.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-erdgeschoss.
     :END:

ASKLEPIOS, den PADMILOS die Treppe hinunterführend. ARACHNE, völlig
ausgemergelt und in ihre Arbeit am Webstuhl vertieft.

Asklepios versucht ein letztes Wort an Arachne zu richten, vergebens. Er
wirft ihr die Klinge Hadesbrand vor die Füße und berichtet ihr, dass
Athene das Messer die ganze Zeit über bei sich trug. Er verabschiedet
sich von Padmilos. Arachne hebt die Klinge auf, betrachtet ihr
Spiegelbild darin, zerreißt den bisher gewebten Teppich und fängt von
Neuem an.

**** Haus der Orke. Eine Woche später.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-eine-woche-später.
     :END:

ARACHNE am Webstuhl arbeitend. PADMILOS, auf einem Stuhl daneben sitzend
und mit Tränen in den Augen und mit offenem Mund das Werk betrachtend.

Arachne stellt ihren Teppich fertig.

**** Agora zu Hypaipa am nächsten Morgen. Die Straßen voller Leute, ein
Durchkommen ist unmöglich. In der Mitte des Platzes ist eine Bühne mit
zwei großen Holzrahmen aufgebaut.
     :PROPERTIES:
     :CUSTOM_ID: agora-zu-hypaipa-am-nächsten-morgen.-die-straßen-voller-leute-ein-durchkommen-ist-unmöglich.-in-der-mitte-des-platzes-ist-eine-bühne-mit-zwei-großen-holzrahmen-aufgebaut.
     :END:

Ein REDNER mit Stab wandert auf der Bühne auf und ab, den Blick in
voller Konzentration auf den Boden gerichtet.

Die Teppiche werden enthüllt. Arachnes Teppich zeigt den Mord der Athene
an Zeus. Arachne wird zur Siegerin erklärt, Athene verwandelt sie in
eine Spinne. Hexe Hippolaya wirft eine dunkelrote Tinktur dazwischen.
Arachne verwandelt sich in eine riesige Spinnenbestie. Athene ergreift
die Flucht. Es kommt zur Panik. Padmilos erscheint, sieht die
Spinnenbestie grad noch davoneilend und beschließt, den Asklepios
aufzusuchen.

**** Schenke Zum Kalydonischen Eber zu Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: schenke-zum-kalydonischen-eber-zu-hypaipa.
     :END:

ASKLEPIOS, vor ihm stehen Krug und Krater, ansonsten ist die Schenke
menschenleer.

Asklepios beim Weine. Draußen hebt eine Panik an. Er beschließt, der
Sache nachzugehen.

*** VIERZEHNTER GESANG -- Bestiensturm
    :PROPERTIES:
    :CUSTOM_ID: vierzehnter-gesang-bestiensturm
    :END:

**** Draußen vor der Schenke Zum Kalydonischen Eber zu Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: draußen-vor-der-schenke-zum-kalydonischen-eber-zu-hypaipa.
     :END:

ASKLEPIOS, sich in alle Richtungen umsehend.

Asklepios sieht sich nach dem Schemen um. Er beschließt, die Agora
aufzusuchen.

**** Agora zu Hypaipa. Menschen verstopfen die Straßen soweit das Auge
reicht. In der Mitte des Platzes die zertrümmerten Überreste einer
Bühne.
     :PROPERTIES:
     :CUSTOM_ID: agora-zu-hypaipa.-menschen-verstopfen-die-straßen-soweit-das-auge-reicht.-in-der-mitte-des-platzes-die-zertrümmerten-überreste-einer-bühne.
     :END:

PADMILOS, sich durch die Reihen kämpfend.

Padmilos steckt in der Menschenmenge fest und erblickt die Spitze des
Gehstabs des Asklepios. Er beschließt, sich krabbelnd durch die
Menschenmenge und zu Asklepios zu durchkämpfen.

**** Agora zu Hypaipa. Einige Meter entfernt.
     :PROPERTIES:
     :CUSTOM_ID: agora-zu-hypaipa.-einige-meter-entfernt.
     :END:

ASKLEPIOS, sich am Rande der Menschenmenge aufhaltend.

Er lässt sich von einer Frau erklären, was passiert ist. Padmilos findet
ihn. Sie überlegen, wohin die Spinnenbestie geflohen sein könnte und
machen sich auf zum Athene-Tempel.

**** Athene-Tempel zu Hypaipa. Abenddämmerung. Über den Säulen ragt der
Kopf der Athenestatue empor, dahinter der Obelisk.
     :PROPERTIES:
     :CUSTOM_ID: athene-tempel-zu-hypaipa.-abenddämmerung.-über-den-säulen-ragt-der-kopf-der-athenestatue-empor-dahinter-der-obelisk.
     :END:

PADMILOS und ASKLEPIOS erscheinen und beobachten den Tempel aus einiger
Entfernung.

Die Spinnenbestie verwüstet den gesamten Tempel, zerstört die
Athene-Statue. Sie beschließen zu warten, bis das Biest sich beruhigt.

**** Athene-Tempel zu Hypaipa. Einige Stunden später. Nacht. Der Staub
hat sich gelegt.
     :PROPERTIES:
     :CUSTOM_ID: athene-tempel-zu-hypaipa.-einige-stunden-später.-nacht.-der-staub-hat-sich-gelegt.
     :END:

PADMILOS, eingenickt. ASKLEPIOS, auf seinen Stab gestützt und mit der
Müdigkeit kämpfend.

Aus dem Tempel ist nicht mehr zu hören. Asklepios schickt Padmilos fort,
die Stadtwache herbeizuholen. Als Padmilos verschwunden ist, erscheint
der Schemen. Asklepios hat eine Idee und bittet den Schemen, ihm in den
Tempel zu folgen.

**** Innerhalb des verwüsteten Athene-Tempels zu Hypaipa. Trümmer
allerortens.
     :PROPERTIES:
     :CUSTOM_ID: innerhalb-des-verwüsteten-athene-tempels-zu-hypaipa.-trümmer-allerortens.
     :END:

ASKLEPIOS, mit aller Vorsicht über die Trümmer schleichend und ich in
alle Richtungen umsehend. SCHEMEN, ihm ohne besondere Vorsicht folgend
und ein gutes Stück hinter ihm.

Die Spinnenbestie hockt über ihnen an der Decke. Asklepios stellt den
Schemen als Idmon vor. Wachen postieren sich vor dem Tempel.

**** Vor dem Athene-Tempel zu Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: vor-dem-athene-tempel-zu-hypaipa.
     :END:

WACHEN haben den Tempel umstellt. Eine Reihe BOGENSCHÜTZEN zielt auf den
Asklepios. Vor der Reihe steht ein HAUPTMANN, die Hand auf den Knauf
seines Schwertes gelegt. Neben ihm steht der PADMILOS. ASKLEPIOS steht
zwischen den Säulen.

Das Spinnenwesen packt sich den Schemen und klettert auf Anweisung des
Asklepios den Obelisken hinauf. Die ersten Pfeile fliegen. Der Hauptmann
beschließt, Brandpfeile einzusetzen.

**** Berg Olymp. Orakelhain.
     :PROPERTIES:
     :CUSTOM_ID: berg-olymp.-orakelhain.
     :END:

HERA und ATHENE am Orakelbecken. Im Wasser ist der zerstörte
Athene-Tempel zu sehen. Auf der Spitze des Obelisken wütet die
Spinnenbestie.

Zeus kommt hinzu. Hera belügt ihn, dass Asklepios das Spinnenmonster
erschaffen hätte. Zeus fragt Athene, ob dies stimmt, Athene bejaht. Zeus
macht sich auf nach Hypaipa, um selbst für Ordnung zu sorgen. Athene
beklagt sich bei Hera, dass sie sie in die Lüge gegenüber Zeus getrieben
hat. Sie macht sich auf nach Hypaipa, um dem Göttervater die Wahrheit zu
erzählen.

**** Athene-Tempel zu Hypaipa. Auf der Spitze des Obelisken wütet die
Spinnenbestie.
     :PROPERTIES:
     :CUSTOM_ID: athene-tempel-zu-hypaipa.-auf-der-spitze-des-obelisken-wütet-die-spinnenbestie.
     :END:

WACHEN. HAUPTMANN, PADMILOS hinter ihm. Kohlebecken werden
herangetragen.

Die Spinnenbestie schießt eine Netzflüssigkeit auf die Wachen ab und
begräbt sie dann unter sich. Sämtliche Wachen, nur Padmilos nicht,
kommen um. Die Spinnenbestie kommt auf Padmilos zu, verschont ihn
jedoch, als Athene erscheint. Es kommt zum Zweikampf zwischen Athene und
der Spinnenbestie, den Athene verliert. Sie verschwindet. Währenddessen
schafft es Asklepios, Padmilos mit sich in den Tempel zu nehmen. Die
Spinnenbestie verschwindet irgendwo zwischen den Häusern in der Stadt.

**** Innerhalb des verwüsteten Athene-Tempels zu Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: innerhalb-des-verwüsteten-athene-tempels-zu-hypaipa.
     :END:

ASKLEPIOS, PADMILOS, sich gegenseitig von dem weißen Zeugs befreiend.

Zeus erscheint. Asklepios warnt ihn vor Arachne. Asklepios glaubt nicht,
dass Zeus Arachne besiegen wird. Padmilos beschließt, sich dem Zeus
anzuschließen, um den letzten Kampf und den Sieg des Zeus (wie er denkt)
bezeugen zu können.

**** Gassen von Hypaipa. Nahe des Handwerkerviertels. Der Morgen
dämmert.
     :PROPERTIES:
     :CUSTOM_ID: gassen-von-hypaipa.-nahe-des-handwerkerviertels.-der-morgen-dämmert.
     :END:

ZEUS, durch die menschenleeren Gassen streifend. Um ihn herum
eingerissene Wände und eingestürzte Hütten.

Athene erscheint und will ihn warnen. Zeus erklärt, dass er schon alles
weiß und weist sie an, sich auf den Olymp zurückzuziehen. Am Ende der
Gasse findet er einen Spinnfaden. Er folgt ihm.

**** Handwerkerviertel zu Hypaipa. Morgendämmerung. Sämtliche Häuser
sind eingesponnen. Im Licht der aufgehenden Sonne schimmern sie wie
weißes Gold.
     :PROPERTIES:
     :CUSTOM_ID: handwerkerviertel-zu-hypaipa.-morgendämmerung.-sämtliche-häuser-sind-eingesponnen.-im-licht-der-aufgehenden-sonne-schimmern-sie-wie-weißes-gold.
     :END:

ZEUS, dem Spinnfaden folgend.

Zeus kommt an einigen eingesponnenen Häusern vorbei. Ein Pärchen
betrachtet eines der eingesponnenen Häuser und hält es für ein Geschenk
der Götter.

**** Haus der Orke. Früher Morgen. Das Haus liegt unter Netzen
verborgen.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-früher-morgen.-das-haus-liegt-unter-netzen-verborgen.
     :END:

Vor dem Haus hat sich eine Menschentraube gebildet. Auf dem Dach hockt
die SPINNENBESTIE und webt die herrlichsten Muster, als würde sie die
Menschen um sich herum gar nicht nicht wahrnehmen. ZEUS kommt dazu,
unter seiner Kapuze verborgen.

Zeus setzt sich zu den anderen und sieht der Spinnenbestie beim Weben
zu.

**** Haus der Orke. Früher Abend. Das Haus ist völlig eingesponnen.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-früher-abend.-das-haus-ist-völlig-eingesponnen.
     :END:

Menschentraube vor dem Haus. Immer weitere Menschen kommen hinzu. ZEUS
und der mittlerweile eingetroffene PADMILOS, sitzend und die
SPINNENBESTIE beim Weben betrachtend. Ein erstes Bild ist zu erkennen.
ASKLEPIOS kommt hinzu.

Der Anblick des Gewobenen nimmt auch den Asklepios gefangen.

**** Haus der Orke. Nacht. Die Netze leuchten silbern.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-nacht.-die-netze-leuchten-silbern.
     :END:

Immer größere MENSCHENTRAUBE vor dem Haus. ZEUS, PADMILOS und ASKLEPIOS,
im Gras sitzend. Auf dem Haus die SPINNENBESTIE, am dritten Bild webend.

Der Schemen Idmon stößt zu ihnen. Asklepios offenbart, dass er es war,
den er von den Toten auferweckte.

**** Haus der Orke. Drei Tage später. Nacht. Die Vorderseite ist
komplett eingesponnen und mit prächtig gewebten Bildern versehen.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-drei-tage-später.-nacht.-die-vorderseite-ist-komplett-eingesponnen-und-mit-prächtig-gewebten-bildern-versehen.
     :END:

Die MENSCHENMASSE hat sich auf die Seite des Hauses verlagert, um der
SPINNENBESTIE beim Bespinnen zuzusehen. Die ganze Stadt scheint sich um
das Haus versammelt zu haben. Erste Bewohner liegen entkräftet am Boden.
Niemand schafft es, sich dem Anblick zu entziehen. Niemand verlässt den
Platz, um etwas zu essen oder zu trinken. ZEUS, ASKLEPIOS, PADMILOS und
der SCHEMEN sitzen und betrachten das Werk.

Die um Zeus Sitzenden werden langsam wahnsinnig. Lieber wollen sie
verdursten, als dass sie Zeus ein Gewitter herbeibeschwören lassen.

**** Haus der Orke. Fünfter Tag. Die Rückseite des Hauses ist
eingesponnen, zwei der drei Bilder sind bereits fertiggestellt.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-fünfter-tag.-die-rückseite-des-hauses-ist-eingesponnen-zwei-der-drei-bilder-sind-bereits-fertiggestellt.
     :END:

Die MENSCHEN um ZEUS herum liegen am Boden. Die, die das Bewusstsein
noch nicht verloren haben, liegen mit offenen Augen am Boden. Die Toten
haben die Augen geschlossen, zumindest teilweise. ASKLEPIOS, PADMILOS am
Grunde. Der SCHEMEN ist nicht unter ihnen.

Alle um ihn herum liegen am Boden. Viele Tote dazwischen.

**** Haus der Orke. Siebter und letzter Tag. Nacht. Das Haus ist auf
drei Seiten vollständig mit Bildern versehen. Die Spinnenbestie ist beim
letzten Bild auf der letzten übriggebliebenen Seite.
     :PROPERTIES:
     :CUSTOM_ID: haus-der-orke.-siebter-und-letzter-tag.-nacht.-das-haus-ist-auf-drei-seiten-vollständig-mit-bildern-versehen.-die-spinnenbestie-ist-beim-letzten-bild-auf-der-letzten-übriggebliebenen-seite.
     :END:

Die ganze Stadt liegt am Boden um das Haus herum verteilt. ZEUS, als
einziger sitzend. Der SCHEMEN, neben ihm stehend und die SPINNENBESTIE
berachtend. ASKLEPIOS und PADMILOS irgendwo neben ihnen am Boden.

Die Spinnenbestie stellt ihr Werk fertig und stirbt. Sie verwandelt sich
in die Arachne zurück. Der Schemen trägt sie auf Händen. Hades erscheint
und nimmt die beiden mit sich. Wind kommt auf und wickelt die Kunstwerke
der Spinnenbestie auf. Sie verschwinden. Zeus lässt ein gewaltiges
Unwetter aufziehen, dessen Regen die Menschen wieder zum Leben erweckt.

*** EPILOGOS -- Der Aar am Firmamente
    :PROPERTIES:
    :CUSTOM_ID: epilogos-der-aar-am-firmamente
    :END:

**** Anhöhe außerhalb der Stadt Hypaipa.
     :PROPERTIES:
     :CUSTOM_ID: anhöhe-außerhalb-der-stadt-hypaipa.
     :END:

ASKLEPIOS, auf einem Stein am Wegrand sitzend.

Zeus erscheint dem Asklepios unerkannt. In der Ferne taucht der Hades
auf und erwartet den Asklepios. Zeus lässt Asklepios allein zurück.
Gerade, als Asklepios sich auf den Weg zum Totengott aufmacht, kommt
eine kleines Mädchen herbeigeeilt und teilt ihm etwas mit. Asklepios
lässt sich von dem Mädchen wegführen und lässt den Totengott allein
zurück.

** Historische Ereignisse
   :PROPERTIES:
   :CUSTOM_ID: historische-ereignisse
   :END:

-  [[file:untergang-der-stadt-kolophon.org][Untergang der Stadt Kolophon]]
-  [[file:ermordung-des-hades.org][Ermordung des Hades]]
-  [[file:aufstand-der-toten.org][Aufstand der Toten]]
-  [[file:ermordung-der-drei-richter.org][Ermordung der drei Richter]]
-  [[file:tod-des-hermes.org][Tod des Hermes]]
-  [[file:verstuemmelung-der-atropos.org][Verstümmelung der Atropos]]

** Ausführliches Personenverzeichnis
   :PROPERTIES:
   :CUSTOM_ID: ausführliches-personenverzeichnis
   :END:

[[file:agdistis.org][Agdistis]] · [[file:aiakos.org][Aiakos]] ·
[[file:aitnaios.org][Aitnaios]] · [[file:alkon.org][Alkon]] · [[file:apollon.org][Apollon]] ·
[[file:arachne.org][Arachne]] · [[file:asklepios.org][Asklepios]] ·
[[file:athene.org][Athene]] · [[file:atropos.org][Atropos]] · [[file:attis.org][Attis]] ·
[[file:autolykos.org][Autolykos]] · [[file:cassandros.org][Cassandros]] ·
[[file:charon.org][Charon]] · [[file:cheiron.org][Cheiron]] · [[file:colydon.org][Colydon]] ·
[[file:damistokles.org][Damistokles]] · [[file:echidna.org][Echidna]] ·
[[file:erebos.org][Erebos]] · [[file:eribotes.org][Eribotes]] ·
[[file:essokles.org][Essokles]] · [[file:eurymedon.org][Eurymedon]] ·
[[file:hades.org][Hades]] · [[file:harpokrates.org][Harpokrates]] · [[file:hera.org][Hera]] ·
[[file:herakles.org][Herakles]] · [[file:hermes.org][Hermes]] ·
[[file:hippolaya.org][Hippolaya]] · [[file:iason.org][Iason]] · [[file:idas.org][Idas]] ·
[[file:idmon.org][Idmon]] · [[file:ikariod.org][Ikariod]] · [[file:ixmos.org][Ixmos]] ·
[[file:kanthos.org][Kanthos]] · [[file:klotho.org][Klotho]] · [[file:klytios.org][Klytios]] ·
[[file:kronos.org][Kronos]] · [[file:kybele.org][Kybele]] · [[file:lachesis.org][Lachesis]] ·
[[file:minos.org][Minos]] · [[file:mopsos.org][Mopsos]] · [[file:okeanos.org][Okeanos]] ·
[[file:onnes.org][Onnes]] · [[file:orke.org][Orke]] · [[file:padmilos.org][Padmilos]] ·
[[file:peleus.org][Peleus]] · [[file:pondros.org][Pondros]] · [[file:poseidon.org][Poseidon]]
· [[file:rhadamanthys.org][Rhadamanthys]] · [[file:sisyphus.org][Sisyphus]] ·
[[file:teiresias.org][Teiresias]] · [[file:thanatos.org][Thanatos]] ·
[[file:thraphes.org][Thraphes]] · [[file:tiphys.org][Tiphys]] · [[file:zeus.org][Zeus]]

*** Orte, Länder, Flüsse
    :PROPERTIES:
    :CUSTOM_ID: orte-länder-flüsse
    :END:

[[file:aipos.org][Aipos]] · [[file:aeolische-strasse.org][Äolische Straße]] ·
[[file:bithynien.org][Bithynien]] · [[file:demeters-tropfen.org][Demeters Tropfen]] ·
[[file:festung-des-hades.org][Festung des Hades]] ·
[[file:hadesfestung.org][Hadesfestung]] · [[file:halle-der-richter.org][Halle der
Richter]] · [[file:herakleia-pontike.org][Herakleia Pontike]] ·
[[file:hexenhain.org][Hexenhain]] · [[file:hypaipa.org][Hypaipa]] ·
[[file:insel-der-moiren.org][Insel der Moiren]] · [[file:kap-tainaron.org][Kap
Tainaron]] · [[file:kokytos.org][Kokytos]] · [[file:kolophon.org][Kolophon]] ·
[[file:lethe.org][Lethe]] · [[file:lydien.org][Lydien]] · [[file:macedonia.org][Macedonia]] ·
[[file:myrina.org][Myrina]] · [[file:orakel-von-klaros.org][Orakel von Klaros]] ·
[[file:orakelhain-olymp.org][Orakelhain (Olymp)]] · [[file:olymp.org][Olymp]] ·
[[file:samothrake.org][Samothrake]] · [[file:sangarios.org][Sangarios]] ·
[[file:zum-kalydonischen-eber.org][Zum Kalydonischen Eber]]

*** Sonstige Begriffe
    :PROPERTIES:
    :CUSTOM_ID: sonstige-begriffe
    :END:

[[file:aether.org][Aether]] · [[file:agora.org][Agora]] · [[file:armageddon.org][Armageddon]]
· [[file:augentrost.org][Augentrost]] · [[file:blutschau.org][Blutschau]] ·
[[file:bugspriet.org][Bugspriet]] · [[file:eiche-von-dodona.org][Eiche von Dodona]] ·
[[file:euphrasia.org][Euphrasia]] · [[file:fach-weberei.org][Fach (Weberei)]] ·
[[file:fibel.org][Fibel]] · [[file:hadesbrand.org][Hadesbrand]] ·
[[file:hindinnenblut.org][Hindinnenblut]] · [[file:hoplit.org][Hoplit]] ·
[[file:ketos.org][Ketos]] · [[file:kolophonium.org][Kolophonium]] ·
[[file:krater.org][Krater]] · [[file:kriegergriff.org][Kriegergriff]] ·
[[file:lebensfaden.org][Lebensfaden]] · [[file:leviathan.org][Leviathan]] ·
[[file:moiren.org][Moiren]] · [[file:moirenblut.org][Moirenblut]] ·
[[file:mysterien.org][Mysterien]] · [[file:okeaniden.org][Okeaniden]] ·
[[file:pallas.org][Pallas]] · [[file:runkse.org][Runkse]] · [[file:schiff-weberei.org][Schiff
(Weberei)]] · [[file:schuetze-weberei.org][Schütze (Weberei)]] ·
[[file:schwarzer-koenig.org][Schwarzer König]] · [[file:zerberus.org][Zerberus]]

** Easter Eggs
   :PROPERTIES:
   :CUSTOM_ID: easter-eggs
   :END:

ZWÖLFTER GESANG -- Hypaipa

Haus der Orke

#+BEGIN_EXAMPLE
    Ich sollte es wohl lassen,
    aber den Göttern sei Dank
    ist mein Wille schwach.
    ALTE FRAU
    Der Exorzist. Warner Bros. 1973 und 2000 (neue Version).
#+END_EXAMPLE

EPILOGOS -- Der Aar am Firmamente

Anhöhe außerhalb der Stadt Hypaipa.

#+BEGIN_EXAMPLE
    Und meide er das fette Essen,
    es ist ihm nie sehr gut bekommen.
    WANDERER
    Monty Pythons Der Sinn des Lebens. Universal Pictures 1983.
#+END_EXAMPLE
