#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Die Ermordung des Hades

Die *Ermordung des* Hades fand statt kurz nach dem Eintreffen des
[[file:asklepios.org][Asklepios]] in der Stadt [[file:myrina.org][Myrina]].

** Die Klinge Hadesbrand
   :PROPERTIES:
   :CUSTOM_ID: die-klinge-hadesbrand
   :END:

Auf dem Weg nach Myrina überrascht die [[file:arachne.org][Arachne]] den
[[file:asklepios.org][Asklepios]] bei einem finsteren Ritual: Er ist gerade
damit beschäftigt, [[file:hindinnenblut.org][Hindinnenblut]] auf eine Klinge zu
träufeln. Asklepios behauptet, ein Operationsbesteck anzufertigen.

** In Myrina
   :PROPERTIES:
   :CUSTOM_ID: in-myrina
   :END:

In Myrina angekommen, wartet der Asklepios auf die Ankunft des Schemens
des [[file:idmon.org][Idmon]]. Stattdessen erscheint der [[file:hades.org][Hades]].
Als der Schemen versucht, den Hades mit der [[file:hadesbrand.org][Klinge
Hadesbrand]] abzustechen, schafft er es nicht, den Totengott zu
verwunden, da ein Toter den Hades nicht töten kann. Asklepios treibt die
Klinge daraufhin selbst in den Hades und tötet ihn. Die daraus
entstehende Schockwelle reißt alle zu Boden.

** Der Ansturm des Zerberus
   :PROPERTIES:
   :CUSTOM_ID: der-ansturm-des-zerberus
   :END:

Im [[file:totenreich.org][Totenreich]] angekommen, entsendet der Hades den
[[file:zerberus.org][Zerberus]], um den Asklepios zu töten.

** Der Aufstand der Toten
   :PROPERTIES:
   :CUSTOM_ID: der-aufstand-der-toten
   :END:

Im Hades kommt es daraufhin zum [[file:aufstand-der-toten.org][Aufstand der
Toten]].

** Motivation des Asklepios
   :PROPERTIES:
   :CUSTOM_ID: motivation-des-asklepios
   :END:

Asklepios möchte noch nicht aus dem Leben treten. Er hat sein Leben
dafür eingesetzt, die Menschen vor dem Totenreich zu bewahren und hat
das Gefühl, dass seine Aufgabe auf Erden noch nicht getan ist. In Myrina
will er dem Schemen des Idmon daher die Klinge Hadesbrand überreichen
und den Totengott von ihm töten lassen, da es unermessliches Unglück
bringt, einen Gott zu töten. Der Hades erscheint jedoch zuerst, so dass
es kein heimliches Attentat wird, in welchem der Totengott sein Leben
lässt.
