#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Hades

*Hades* ist ein Sohn des [[file:kronos.org][Kronos]] und der [[file:rhea.org][Rhea]].
Er ist der Herrscher über das Totenreich. Man nennt ihn auch: Der Starke
(Krateros).

** Äußere Erscheinung
   :PROPERTIES:
   :CUSTOM_ID: äußere-erscheinung
   :END:

Er trägt ein pechschwarzes Gewand, welches im Wind flattert wie
Dämonenflügel und alles Licht zu verschlucken scheint. Sein Gesicht ist
unter einer Kapuze verborgen. Seine Stimme hallt tief.

** Besondere Fähigkeiten
   :PROPERTIES:
   :CUSTOM_ID: besondere-fähigkeiten
   :END:

*** Nekromantisches Geschoss
    :PROPERTIES:
    :CUSTOM_ID: nekromantisches-geschoss
    :END:

Der Hades ist in der Lage, ein nekromantisches Geschoss zu verschießen.
Dieses raubt dem Opfer direkt die Lebensenergie.

*** Totenwahrnehmung
    :PROPERTIES:
    :CUSTOM_ID: totenwahrnehmung
    :END:

Hades ist in der Lage, tote Seelen zu spüren. Er kann jeden Toten
innerhalb seines Reiches aufspüren, sowie Seelen auf der Schwelle zum
Tode bereits wahrnehmen.

*** Totenbannung
    :PROPERTIES:
    :CUSTOM_ID: totenbannung
    :END:

Es ist die Totenbannung, welche die Toten in Schemengestalt im
Totenreich gefangen hält. Ein Toter könnte aus dem Fluss
[[file:kokytos.org][Kokytos]] trinken, sich seines verlorenen Lebens erinnern
und würde doch nicht wieder stofflich werden. Erst als die Totenbannung
durch die Ermordung des Hades gebannt ist, führt das Erinnern zur
Rückverstofflichung der Toten.

** Ereignisse in Arachneion-Pallashass
   :PROPERTIES:
   :CUSTOM_ID: ereignisse-in-arachneion-pallashass
   :END:

Der Hades trifft zum ersten Mal vor den Toren [[file:kolophon.org][Kolophons]]
auf den Heiler [[file:asklepios.org][Asklepios]]. Dieser hat den
[[file:goetter.org][Göttern]] schwer gefrevelt, darum möchte der Hades ihn mit
sich in den Hades führen. Asklepios erbittet sich eine Frist
[[file:arachne.org][Arachne]], die Tochter des [[file:idmon.org][Idmon]] in ihre neue
Heimat zu führen. Er hat es dem sterbenden Idmon versprochen, daher kann
der Hades ihm den Wunsch nicht abschlagen.

Zwei Wochen später überrascht der Hades den Asklepios in der Stadt
[[file:myrina.org][Myrina]]. Der Heiler hat sich nicht an die Abmachung
gehalten und sich auf den Weg nach Myrina gemacht. Als Hades ihn diesmal
zu sich holen möchte, erscheint plötzlich ein weiterer Schemen. Der
Asklepios reicht dem Schemen eine [[file:hadesbrand.org][verhexte Klinge]]. Der
Schemen versucht daraufhin, den Hades mit der Klinge zu töten. Da kein
Toter den Totengott töten kann, bleibt die Klinge in der Rüstung des
Hades stecken. Daraufhin stürzt sich Asklepios selbst auf ihn und
[[file:ermordung-des-hades.org][treibt ihm die Klinge in die Brust]].

Hades findet sich daraufhin im Totenreich wieder. Vor lauter Wut hetzt
er den [[file:zerberus.org][Zerberus]] auf den Asklepios. Durch Hades' Tod ist
der Bann über die Toten gebrochen, sie beginnen sich zu erinnern und
wieder körperliche Form anzunehmen. Sie versuchen, die Festung des Hades
zu stürmen, doch der Totengott ist in der Lage, Welle um Welle der
Angreifenden zurückzuwerfen. Bevor er jedoch unter der Last der Angriffe
zusammenbricht, erscheint [[file:athene.org][Athene]] und führt ihn in die
Festung.

Als die Sterblichen [[file:iason.org][Iason]] und Asklepios den Hades um Hilfe
bitten, den sterbenden Zeus zu retten, versagt Hades ihnen jede Hilfe.
Er erklärt sich jedoch später dazu bereit, sie auf den
[[file:olymp.org][Olymp]] zu bringen, um dem Zeus das Gegenmittel zu
verabreichen.

Zu guter Letzt erwartet der Hades den Asklepios außerhalb der Tore
Myrinas. Doch auch diesmal bleibt ihm der Asklepios verwehrt: Ein
kleines Mädchen erscheint, flüstert dem Heiler etwas ins Ohr, nimmt ihn
bei der Hand und führt ihn von der Straße und vom Hades fort.
