#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Hippolaya

Die Hexe *Hippolaya* war eine Geliebte des Heilers
[[file:asklepios.org][Asklepios]]. Sie lebt auf der [[file:samothrake.org][Insel
Samothrake]]. Hippolaya ist eine begnadete Alchimistin.

** Aussehen
   :PROPERTIES:
   :CUSTOM_ID: aussehen
   :END:

Eine alte Frau mit Haaren wie Spinnweben, behängt mit allerlei
Glitzerkram.

** Besondere Zauber und Talente
   :PROPERTIES:
   :CUSTOM_ID: besondere-zauber-und-talente
   :END:

*** Schockwelle
    :PROPERTIES:
    :CUSTOM_ID: schockwelle
    :END:

Hippolaya kann Schockwellen entfesseln.

*** Die Nacht
    :PROPERTIES:
    :CUSTOM_ID: die-nacht
    :END:

Hippolaya kann Räume verdunkeln.

*** Bestienform (Metamorphose)
    :PROPERTIES:
    :CUSTOM_ID: bestienform-metamorphose
    :END:

Hippolaya kann sich in eine schreckliche bleiche Bestie verwandeln. In
Bestiengestalt kann sie ihre Krallen ausfahren und ist sogar in der Lage
zu fliegen.

** Ereignisse in Arachneion-Pallashass
   :PROPERTIES:
   :CUSTOM_ID: ereignisse-in-arachneion-pallashass
   :END:

Asklepios sucht Hippolaya auf, um ein Gegenmittel zur Rettung des
vergifteten [[file:zeus.org][Zeus]] zu finden.

Hippolaya behauptet zunächst, dass es auf dieser Welt keine Rettung für
den Zeus gibt. Daraufhin wird sie gefesselt und von [[file:athene.org][Athene]]
misshandelt. Hippolaya schafft es jedoch, die Athene im Kampf zu
besiegen. Bevor die anderen zur [[file:insel-der-moiren.org][Insel der Moiren]]
aufbrechen, verschwindet Hippolaya. Sie tötet den Pfau der
[[file:hera.org][Hera]] und erweckt mit seinem Blut das [[file:agdistis.org][Monstrum
Agdistis]].

Auf der Insel der Moiren besorgt sie das [[file:moirenblut.org][Moirenblut]].
Sie entfesselt dazu einige Schockwellen. Eine der Schockwellen
[[file:verstuemmelung-der-atropos.org][reißt]] der [[file:moiren.org][Moire]]
[[file:atropos.org][Atropos]] beide Fangbeine ab. Anschließend zertrümmert sie
das Spinnrad der Moiren. Als sie zurück zur [[file:argo.org][Argo]] fliehen,
umschließt Hippolaya das Schiff mit einer dunklen Blase und fordert vom
Asklepios das Blut des Zeus.

Als Athene beim Wettbewerb die [[file:arachne.org][Arachne]] in eine Spinne
verwandelt, schleicht Hippolaya unerkannt durch das Publikum. Sie wirft
eine Phiole Zeusblut in den Verwandlungsstrahl der Athene, woraufhin das
Mädchen Arachne sich in eine gewaltige Spinnenbestie verwandelt.
