#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Ikas

*Ikas* ist ein thrakischer Heerführer. Seit der Seeschlacht gegen Euböa,
als ein Blitz vom Himmel in ihn hineinschoss und ihn vom Erdboden
verschluckte, gilt er als vermisst.

** Ereignisse in Titaneion-Titanenschlacht Episoda 1: Bestienborn
   :PROPERTIES:
   :CUSTOM_ID: ereignisse-in-titaneion-titanenschlacht-episoda-1-bestienborn
   :END:

*** Auf der Erde
    :PROPERTIES:
    :CUSTOM_ID: auf-der-erde
    :END:

Ikas erschlägt den euböischen Heerführer [[file:dronos.org][Dronos]]. Mit
seinen letzten Atemzügen klärt Dronos Ikas darüber auf, welch
schrecklichen Fehler er mit seinem Kampf gegen Euböa beging, da Euböa
unter [[file:zeus.org][Zeus']] persönlichem Schutz steht:

#+BEGIN_EXAMPLE
    Kein Fluch, den ich je sprechen könnt,
    wär schlimmer als der Zorn des Zeus.
    So spar dir nur dein tödlich Stechen,
    Zeus selbst holt mich hin in den Hades.
    DRONOS
    ERSTER GESANG – Der Tod des Ikas
#+END_EXAMPLE

Bevor Ikas den Todesstoß vollführen kann, schießt ein Blitz in den
Dronos und lässt ihn verschwinden. Als seine Kampfgefährten
[[file:pandrinos.org][Pandrinos]] und [[file:sandrias.org][Sandrias]] herbeieilen, die
die Szene beobachtet haben und sie für ein unmissverständliches Zeichen
der [[file:goetter.org][Götter]] halten, beschimpft Ikas sie als “Weiber” und
lästert dem Göttervater Zeus persönlich:

#+BEGIN_EXAMPLE
    Hörst du mich, Kronide?
    Diese Weiber schwafeln was von deinem Zorn,
    den ich erregt.
    Ein gutes Dutzend der Abanten
    hat Ikas dir heut schon zerschlagen
    und Ikas wird nicht ruhn noch rasten,
    bevor die See vom Blut getränkt.
    So dann, oh Göttervater groß:
    Solltest du zur Gnad mich trachten,
    so stopp mich nun, eh es zu spät.
    IKAS
    ERSTER GESANG – Der Tod des Ikas
#+END_EXAMPLE

Ein weiterer Blitz schießt vom Himmel. Ikas ist wie vom Erdboden
verschluckt und findet sich wenig später im [[file:tartarus.org][Tartarus]]
wieder.

*** Im Tartarus
    :PROPERTIES:
    :CUSTOM_ID: im-tartarus
    :END:

Im Tartarus angekommen, stößt Ikas auf eine [[file:gaia.org][alte Frau]]. Sie
schleppt einen riesigen Wanst mit sich herum, aus dem das Gebrüll von
Hekatoncheiren und Kyklopen zu vernehmen ist. Die alte Frau stellt sich
wenig später als [[file:gaia.org][Gaia]] heraus, der ihr Gatte
[[file:uranus.org][Uranus]] die [[file:hekatoncheiren.org][Hekatoncheiren]] und
[[file:kyklopen.org][Kyklopen]] in den Bauch getrieben hat. Da Gaia die
Nachstellungen des Gatten satt hat, bittet sie den Ikas, ihrem Sohn
[[file:kronos.org][Kronos]] eine [[file:hippe.org][Hippe]] zu bringen, um sich am
Vater zu rächen.

Ikas tut wie ihm befohlen und macht sich an den Aufstieg zur
Erdoberfläche, um dem Kronos die Waffe zu bringen. Zurück im Tartarus
lauert Kronos dem Vater auf und als dieser erscheint, springt er aus
seinem Versteck hervor und schlägt dem Uranus das Gemächt ab.

Unter den entsetzten Blicken der Gaia packt Kronos den Ikas und versucht
ihn im sprudelnden Blut und Samen des Uranus zu ertränken. Als er den
Totgeglaubten zur Seite wirft, erwacht dieser jedoch und hat die Kräfte
von [[file:giganten.org][Giganten]] und [[file:erinyen.org][Erinyen]] in sich vereint.

Ikas ist zu [[file:bestien-ikas.org][Bestien-Ikas]] geworden.
