#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Kybele (Mythos)

Der *Kybele-Mythos* beschreibt die Entstehung des [[file:attis.org][Attis]] und
der [[file:kybele.org][Kybele]] aus dem grausamen Zwitterwesen
[[file:agdistis.org][Agdistis]].

** Das Monstrum Agdistis
   :PROPERTIES:
   :CUSTOM_ID: das-monstrum-agdistis
   :END:

Agdistis war ein furchtbar anzuschauendes Monstrum. Eines Tages
beschlossen die Götter, das Monstrum zu töten.

Dazu ließ der Gott [[file:dionysos.org][Dionysos]] das Wasser eines Baches, aus
dem das Monstrum trank, zu Wein werden. Als der Agdistis daraufhin
einschlief, band Dionysos das Gemächt des schlafenden Agdistis an einem
Baum fest. Als Agdistis erwachte und aufsprang, entmannte er sich
selbst. Aus seinem zu Boden gefallenen Gemächt entsprang der Attis, das
kastrierte Monstrum selbst verwandelte sich in die feiste Kybele. Da
beide der gleichen Person entsprangen, übten beide eine unwiderstehliche
Anziehungskraft aufeinander aus.

** Die Hochzeit des Attis
   :PROPERTIES:
   :CUSTOM_ID: die-hochzeit-des-attis
   :END:

Obwohl beide lange Zeit glücklich durch die phrygischen Berge streiften,
entschied sich Attis dazu, eine andere Frau zu heiraten. Die vor
Eifersucht rasende Kybele erschien auf der Hochzeit und strafte alle
Versammelten mit Wahnsinn. Attis entmannte sich im Wahnsinn selbst und
verblutete an seinen schrecklichen Wunden.

** Der Betrug des Zeus
   :PROPERTIES:
   :CUSTOM_ID: der-betrug-des-zeus
   :END:

Kybele wandte sich an den Göttervater [[file:zeus.org][Zeus]], ihr ihren Attis
wieder zum Leben zu erwecken. Doch statt den Attis wiederzuerwecken,
sorgte Zeus lediglich dafür, dass der Leichnam des Attis nie mehr
verwesen sollte.

** Exil auf Samothrake
   :PROPERTIES:
   :CUSTOM_ID: exil-auf-samothrake
   :END:

Von den Göttern bitter enttäuscht, nahm Kybele den Leichname des Attis
daraufhin an sich und versteckte ihn in einen Altar in einer Höhle tief
in den Wäldern der [[file:samothrake.org][Insel Samothrake]].
