#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Orke

*Orke* ist eine legendäre Weberin aus der Stadt [[file:hypaipa.org][Hypaipa]].
Sie ist eine alte Bekannte des Heilers [[file:asklepios.org][Asklepios]].
Zeitlebens war sie äußerst fromm und betete zur Göttin
[[file:athene.org][Athene]].

** Ereignisse in Arachneion-Pallashass
   :PROPERTIES:
   :CUSTOM_ID: ereignisse-in-arachneion-pallashass
   :END:

Orke nimmt das Mädchen [[file:arachne.org][Arachne]] bei sich auf, um sie in
ihrer Webkunst zu unterweisen. Sie weigert sich zunächst, das
überragende Talent des Mädchens zu erkennen, merkt aber schon bald, dass
sie dem Mädchen nichts mehr beibringen kann. Aufgrund Orkes Frömmigkeit
und ihrer Verehrung der Athene, kommt es zu Spannungen zwischen ihr und
Arachne, die schließlich darin münden, dass die Arachne den Athene-Altar
im Haus der Orke zertrümmert. Alle Versuche, das Mädchen auf den Weg der
[[file:goetter.org][Götter]] zurückzuführen, zum Beispiel sie in einen
Athene-Tempel zu führen, schlagen fehl. Die Angst vor der Rache der
Götter, wegen Arachnes Ablehnung der Götter, macht die Orke schließlich
wahnsinnig. Sie endet als bettlägerige alte Frau, die von ihrer Umgebung
nichts mehr mitbekommt. Der Junge [[file:padmilos.org][Padmilos]] nimmt sich
ihrer an.
