#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Titaneion-Titanenschlacht Episoda 2: Kolossansturm
#+OPTIONS: toc:1

** @@html:<a name="personae">@@@@html:</a>@@Personae
   :PROPERTIES:
   :CUSTOM_ID: personae
   :END:

-  Monster und Menschen
-  [[file:bestien-ikas.org][Bestien-Ikas]]: Ehemaliger thrakischer Heerführer.
   Durch Kronos in eine Bestie verwandelt.
-  [[file:perdix.org][Perdix]]: Neffe des Daedalus. Genialer Erfinder.
-  [[file:pygmalion.org][Pygmalion]]: Kleinwüchsiger König von Paphos. Genialer
   Bildhauer.
-  [[file:ostreos.org][Ostreos]]: Sein oberster Diener.
-  [[file:askrinos.org][Askrinos der Freie]]: Gefeierter Lebemann und Liebhaber
   des Ostreos.
-  Protogenoi und Titanen
-  [[file:gaia.org][Gaia]]: Die Allmutter. Uranus trieb ihr die Kyklopen und
   Hekatoncheiren in den Leib.
-  [[file:uranus.org][Uranus]]: Verkörperung des Himmels. Gatte der Gaia. Im
   Auftrag der Gaia von Kronos mit einer Hippe entmannt.
-  [[file:kronos.org][Kronos]]: Der Krumme. Jüngster Sohn des Uranus und der
   Gaia. Hat die Kroniden verschlungen.
-  Sonstige Begriffe und Fabelwesen
-  [[file:kroniden.org][Kroniden]]: Kinder des Kronos.

   -  [[file:zeus.org][Zeus]]
   -  [[file:hades.org][Hades]]
   -  [[file:poseidon.org][Poseidon]]
   -  [[file:hera.org][Hera]]
   -  [[file:hestia.org][Hestia]]
   -  [[file:demeter.org][Demeter]]

-  [[file:uraniden.org][Uraniden]]: Kinder des Uranus.

   -  [[file:kronos.org][Kronos]]
   -  [[file:rhea.org][Rhea]]
   -  [[file:themis.org][Themis]]
   -  [[file:koios.org][Koios]]
   -  [[file:hyperion.org][Hyperion]]
   -  [[file:iapetos.org][Iapetos]]
   -  [[file:kreios.org][Kreios]]
   -  [[file:okeanos.org][Okeanos]]
   -  [[file:tethys.org][Tethys]]
   -  [[file:phoibe.org][Phoibe]]
   -  [[file:theia.org][Theia]]
   -  [[file:mnemosyne.org][Mnemosyne]]

-  Weitere [[file:goetter.org][Götter]], [[file:titanen.org][Titanen]],
   [[file:fabelwesen.org][Fabelwesen]].

** @@html:<a name="was-bisher-geschah">@@@@html:</a>@@Was bisher geschah
   :PROPERTIES:
   :CUSTOM_ID: was-bisher-geschah
   :END:

Der thrakische Heerführer Ikas wird vom Blitz getroffen und findet sich
im Tartarus wieder. Er begegnet der Allmutter Gaia, die ihn bittet,
ihrem Sohn Kronos eine Sichel zu bringen, um sie von den ständigen
Nachstellungen ihres Gatten Uranus zu erlösen.

Ikas tut wie ihm geheißen und übergibt dem Titanen die Waffe. Wieder im
Tartarus angekommen, entmannt Kronos den Uranus und versucht, Ikas im
heraussprudelnden Blut und Samen zu ertränken, doch statt zu versterben,
vereint Ikas die Kräfte des Uranusblutes in sich und verwandelt sich in
eine schreckliche Bestie.

Sein Versuch, sich an Kronos zu rächen, schlägt fehl: Kronos reißt ihm
die Flügel heraus und wirft ihn aus der Himmelsfestung zur Erde zurück.

Hades rettet Bestien-Ikas vor dem sicheren Tod, schwört Kronos zuvor
jedoch, mit dem Geretteten zurückzukehren und sich an ihm zu rächen.

Gaia, Uranus, Hades und Bestien-Ikas verbünden sich und machen sich auf
die Suche nach Daedalus, dem legendären Erfinder, um Bestien-Ikas ein
paar neue Flügel fertigen zu lassen.

Daedalus wird vom Dämonenheer des Kronos tödlich verwundet und übergibt
Bestien-Ikas und Hades eine Schriftrolle mit der Bitte, seinen Neffen
Perdix zu finden und ihm die Rolle zu übergeben. Da Perdix den Kopf des
Daedalus benötigen wird, reißt Bestien-Ikas dem sterbenden Daedalus den
Kopf ab und rettet sich in den Tartarus.

Gaia berichtet, dass Athene die letzte ihr bekannte Person ist, die
Perdix gesehen hat. Hades, Bestien-Ikas und die in der Zwischenzeit
hinzugestoßene Kronosgattin Rhea machen sich auf die Suche nach der
Göttin und durchsuchen die Schenken Athens.

Sie finden Athene und stellen zu ihrem Bedauern fest, dass die Göttin
sich nicht daran erinnern kann, wo sie den Perdix zum letzten Mal
gesehen hat. Zwischenzeitlich werden sie von Dämonen und Harpyien
angegriffen, welche die Rhea entführen.

Zurück im Tartarus befragt Hades den Kopf des Daedalus und erfährt von
zwei Laboren auf Zyprus. Aphrodite und ein kürzlich verstorbener
Priester des Kronos schließen sich ihnen an. Sie brechen in die Stadt
Paphos auf, in der sämtliche Frauen vertrieben oder gepfählt wurden.

Sie durchsuchen die Schenken nach Perdix und landen in der Schenke
Thermodonion. Der tote Kronospriester -- der in Wahrheit ein Spion des
Kronos ist -- löst sich von der Gruppe, um seinem wahren Herrn zu
berichten. Bestien-Ikas und Hades folgen ihm, können ihn jedoch nicht
finden.

In der Zwischenzeit wird die Schenke von Wachen angegriffen und
niedergebrannt. Athene und Aphrodite, die -- als Männer verkleidet -- in
der Schenke zurückgeblieben sind, werden von Perdix gerettet und in sein
geheimes Labor gebracht. Bestien-Ikas versucht, die Frauen aus der
brennenden Schenke zu retten, wird jedoch von den Wachen erschlagen.

Hades, der die anderen für tot hält, flieht in den Tartarus. Hades, Gaia
und Uranus beschließen, das Orakel von Delphi aufzusuchen, um
herauszufinden, ob ihr Kampf bereits zu Ende ist -- ebenso wie Kronos,
der in der Zwischenzeit seine Titanenbrüder um sich versammelt hat und
das Orakel befragen möchte, ob er sich noch immer vor der Rache des
Bestien-Ikas in Acht nehmen muss ...

** @@html:<a name="gesaengekatalog">@@@@html:</a>@@Gesängekatalog
   :PROPERTIES:
   :CUSTOM_ID: gesängekatalog
   :END:

*** @@html:<a name="erster-gesang">@@@@html:</a>@@ERSTER GESANG --
Orakelspruch und Kriegserklärung
    :PROPERTIES:
    :CUSTOM_ID: erster-gesang-orakelspruch-und-kriegserklärung
    :END:

**** Thronsaal in Paphos.
     :PROPERTIES:
     :CUSTOM_ID: thronsaal-in-paphos.
     :END:

Ein KLEINWÜCHSIGER bearbeitet eine Statue mit Hammer und Meißel.
OSTREOS, der oberste Kammerdiener, vor einer Säule. Diverse DIENER und
BEDIENSTETE halten sich im Hintergrund.

König Pygmalion zeigt sein überragendes Talent als Bildhauer und seinen
wirren Cahrakter. Bestien-Ikas wird herangeführt. König Pygmalion wird
wütend, als er feststellt, das Monster nicht in Stein hauen zu können.
Der Hauptmann der Wache berichtet von fünf Fremden am Stadttor und dem
Amazonen-Aufstand in der Schenke. König Pygmalion lässt die Figur, an
der er gerade gearbeitet hat, in den Nebenraum schaffen, um sie “zu
vollenden”. Niemand außer Ostreos weiß, was dies bedeutet.

**** Hang des Parnass. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: hang-des-parnass.-nacht.
     :END:

HADES, URANUS und GAIA erscheinen.

Sie stoßen auf den erstarrten Python. Sie vermuten Kronos in der Nähe.
Als sie weiterschleichen, erblicken sie die Titanen am Orakel.

**** Orakel von Delphi.
     :PROPERTIES:
     :CUSTOM_ID: orakel-von-delphi.
     :END:

KRONOS, MENOITIOS, KREIOS und ATLAS DER HARTE stehen um die THEMIS
versammelt.

Kronos will Themis dazu zwingen, ihm im Orakel abzulesen, ob der Ikas,
Athene, Aphrodite und der Hades noch am Leben sind. Gaia erscheint, kurz
darauf der Uranus. Uranus schlägt Kronos vor, die Themis zu verschonen,
dafür verrät Gaia -- als frühere Wächterin des Orakels -- ihm, was er
vom Orakel wissen möchte. Im Orakel sind der Bestien-Ikas im Thronsaal,
sowie Aphrodite und Athene gemeinsam mit einer Gestalt im schwarzen
Mantel zu sehen (Perdix). Anschließend erklärt Gaia den Titanen den
Krieg. Bei ihrer Flucht hetzt Kronos ihnen den Python auf den Hals. Gaia
schleudert den Python auf die Titanen. Kronos schwört:

“(An die Gaia gewandt:) So kümmern wir uns erst um ihn und dann seid ihr
im Tart'rus dran. (Er stürzt sich auf den Python und beginnt mit ihm zu
ringen.)”

Gaia und die anderen flüchten über den Hang des Parnass.

*** @@html:<a name="zweiter-gesang">@@@@html:</a>@@ZWEITER GESANG --
Triumph der Toten
    :PROPERTIES:
    :CUSTOM_ID: zweiter-gesang-triumph-der-toten
    :END:

**** Seitengasse mit Blick auf die qualmenden Überreste der Schenke
Thermodonion in Paphos. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: seitengasse-mit-blick-auf-die-qualmenden-überreste-der-schenke-thermodonion-in-paphos.-nacht.
     :END:

PERDIX, ATHENE, APHRODITE beobachten das Treiben um die Ruine herum aus
einiger Entfernung. WACHEN patrouillieren und durchsuchen die Trümmer.

Perdix nimmt einen Wachmann gefangen und fragt ihn über den Bestien-Ikas
aus. Der Wachmann behauptet, Bestien-Ikas sei im Klingenhagel gefallen.
Daraufhin tötet Perdix den Wachmann.

**** Ein paar Gassen später. Statuen verteilen sich über die Gasse.
     :PROPERTIES:
     :CUSTOM_ID: ein-paar-gassen-später.-statuen-verteilen-sich-über-die-gasse.
     :END:

ATHENE, APHRODITE und PERDIX schleichen um eine Ecke.

Aphrodite und Athene bewundern die fast lebensechten Statuen des Königs.

**** Thronsaal des Pygmalion.
     :PROPERTIES:
     :CUSTOM_ID: thronsaal-des-pygmalion.
     :END:

BESTIEN-IKAS in Ketten auf einem Podest. PYGMALION auf seinem Schemel
vor einem Steinblock. OSTREOS vor seiner Säule, diverse Bedienstete im
Hintergrund.

Askrinos erscheint und berichtet davon, dass Wachen getötet wurden. Er
nimmt den Bestien-Ikas ins Verhör. König Pygmalion erweist sich als
äußerst angetan von der Bestie. Zu einem vermeintlichen Komplott erfährt
Askrinos nichts.

**** Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: himmelsfeste.
     :END:

KRONOS, MENOITIOS, ATLAS DER HARTE -- den bewusstlosen KREIOS tragend --
kehren zurück.

Die Titanen kehren vom Kampf mit Python zurück. Sie planen einen
Anschlag Gaia, Uranus und Hades. Menoitios und Hyperion machen sich zum
Hang des Parnass auf. (Kronos warnt Iapetos im Scherze, dass sein Sohn
Menoitios sich nicht gegen ihn wende.) Kronos weist den Schatten an,
sich um den verletzten Kreios zu kümmern. Kreios soll die Himmelsfeste
während ihrer Abwesenheit bewachen. Kronos und Atlas machen sich nach
Paphos auf, Iapetos und Koios gehen mit dem Dämonenheer in den Tartarus.

**** Grabhügel außerhalb von Paphos. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: grabhügel-außerhalb-von-paphos.-nacht.
     :END:

DREI SCHATTEN schleichen durch die Dunkelheit. In der Ferne leuchten die
Laternen der patrouillierenden Wachen.

Sie durchsuchen die Gräber nach dem Leichnam des Ikas. Ein Grabräuber
taucht auf, gräbt eine Leiche aus und erschrickt. Wachen werden
angelockt und offenbaren ihm, das verbrannte Pferd des Wirtes der
Schenke Thermodonion als Köder vergraben zu haben. Sie führen ihn ab.
Wenig später werden Perdix, Athene und Aphrodite von Untoten angegriffen
(es sind die durch den Grabräuber geschändeten Leichen -- ihre Münzen
wurden ihnen aus den Mündern gestohlen). Ihnen gelingt die Flucht. Ein
paar von dem Tumult angelockten Wachen werden von den Untoten zerrissen.

*** @@html:<a name="dritter-gesang">@@@@html:</a>@@DRITTER GESANG -- Der
Raub des Daedalus
    :PROPERTIES:
    :CUSTOM_ID: dritter-gesang-der-raub-des-daedalus
    :END:

**** Thronsaal des Pygmalion.
     :PROPERTIES:
     :CUSTOM_ID: thronsaal-des-pygmalion.-1
     :END:

PYGMALION, mit Hammer und Meißel auf seinem Schemel. BESTIEN-IKAS,
kettenlos auf dem Podest. OSTREOS, vor seiner Säule. ASKRINOS, neben
ihm. Diverse BEDIENSTETE, DIENER und WACHEN im Hintergrund.

Pygmalion hat die Statue des Bestien-Ikas fertiggestellt. Sie soll in
die Stadt geschafft werden. Als Ostreos und Askrinos im Thronsaal allein
sind, reagiert Ostreos nicht auf die Avancen des Askrinos. Als Askrinos
gerade gehen will, sagt Ostreos zu ihm: “Der Tod zieht heut Nacht durch
die Stadt.”

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.
     :END:

KOIOS, IAPETOS, ein Heer von DÄMONEN anführend.

Iapetos und Koios finden den Kopf des Daedalus in der Ritze (die
Dämonen/Koios finden den Kopf in der Ritze). Der Kopf flüstert “Lecket
mich am Arsche.” Koios nimmt den Kopf mit sich.

**** Nymphäum zu Kourion auf Zyprus. Ein großes Wasserbecken in der
Mitte.
     :PROPERTIES:
     :CUSTOM_ID: nymphäum-zu-kourion-auf-zyprus.-ein-großes-wasserbecken-in-der-mitte.
     :END:

GAIA, URANUS, HADES, THEMIS erscheinen.

Gaia, Uranus, Hades und Themis retten sich ins Nymphäum auf Kourion.
Gaia hat vor, über die Nymphen weiterhin in Paphos wirken zu können und
sich gleichzeitig im Nymphäum verstecken zu können. Eine SCHWACHE STIMME
aus dem Wasserbecken weist sie an, sich die Stadt anzusehen.

**** Draußen vor dem Nymphäum. Nacht. Rotes Licht glimmt am Horizont. Um
sie herum Ruinen, menschenleere Straßen.
     :PROPERTIES:
     :CUSTOM_ID: draußen-vor-dem-nymphäum.-nacht.-rotes-licht-glimmt-am-horizont.-um-sie-herum-ruinen-menschenleere-straßen.
     :END:

GAIA und URANUS treten vor das Nymphäum.

Sie werden Zeugen einer Belagerung. Die Stadt ist größtenteils zerstört,
immer wieder steigen Feuerbälle in den Nachthimmel auf.

**** Innerhalb des Nymphäums.
     :PROPERTIES:
     :CUSTOM_ID: innerhalb-des-nymphäums.
     :END:

URANUS zieht die GAIA hinein. Der gegen eine Wand gelehnte HADES, die
über ihn gebeugte THEMIS.

Die schwache Stimme schiebt mit letzter Kraft das Wasserbecken zur Seite
und löst sich scheinbar auf. Unter dem Becken kommt ein Abstieg aus
unzähligen Stufen zum Vorschein. Wasser fließt über die Stufen. Sie
machen sich an den Abstieg.

*** @@html:<a name="vierter-gesang">@@@@html:</a>@@VIERTER GESANG --
Steinerne Schwüre
    :PROPERTIES:
    :CUSTOM_ID: vierter-gesang-steinerne-schwüre
    :END:

**** Geheimes Labor des Perdix unterhalb der Stadt Paphos.
     :PROPERTIES:
     :CUSTOM_ID: geheimes-labor-des-perdix-unterhalb-der-stadt-paphos.
     :END:

PERDIX, ATHENE, APHRODITE, einige AMAZONEN verteilen sich im Raum.

Perdix, Athene und Aphrodite beraten ihre nächsten Schritte. Perdix
erzählt von den tödlichen Instrumenten/Waffen, die er unter seinem
Mantel verborgen hält und von denen fünf stets auf die Menschen um ihn
herum gerichtet sind. Die Weiber legen ihre Männerverkleidung an. Alle
drei machen sich auf in die Schenke, in der der Wachen herumhängen, um
sich nach dem Bestien-Ikas umzuhören. Athene und Perdix geraten fast in
Disput über die Waffen des Perdix.

**** Vor der Schenke Söldners bester Schluck in Paphos. Nacht. Warmes
Licht fällt durch die Fenster.
     :PROPERTIES:
     :CUSTOM_ID: vor-der-schenke-söldners-bester-schluck-in-paphos.-nacht.-warmes-licht-fällt-durch-die-fenster.
     :END:

PERDIX, ATHENE und APHRODITE schleichen durch eine Seitengasse.

Perdix gibt den Weibern letzte Anweisungen. Vor der Schenke geraten zwei
betrunkene Wachen in Streit, gehen jedoch beide durch Selbstverschulden
und ohne weitere Schäden zu Boden. Athene hat es sehr eilig, in die
Schenke zu kommen und geht als Erste hinein (noch vor Perdix und
Aphrodite). Perdix befürchtet, dass er und Aphrodite gleich auf die
Athene sehr gut werden achten müssen.

**** Im Inneren der Schenke Söldners bester Schluck. Gestank nach
Schweiß und Fusel. Laute Männerstimmen.
     :PROPERTIES:
     :CUSTOM_ID: im-inneren-der-schenke-söldners-bester-schluck.-gestank-nach-schweiß-und-fusel.-laute-männerstimmen.
     :END:

PERDIX und APHRODITE betreten den Schankraum.

Die Athene trinkt bereits Branntwein, als Perdix und Aphrodite die
Schenke betreten. Perdix versucht, die Athene mit einer Phiole
Betäubungsmittel im Krug einzuschläfern, muss den Krug letztendlich aber
selber trinken, worauf er bewusstlos zu Boden geht. Aphrodite stellt
Athene zur Rede, ohne daran zu denken, ihre Stimme zu verstellen. Die
Männer erkennen sie als Weiber und stürzen sich auf sie. Athene bekommt
den Rädelsführer zu packen und kann sie freipressen. Die Männer erkennen
sie wieder als diejenigen, die die Schenke Thermodonion verwüstet haben.
Athene, Aphrodite und der bewusstlose Perdix flüchten.

**** Draußen vor der Schenke Söldners bester Schluck. Tumult dröhnt aus
dem Inneren.
     :PROPERTIES:
     :CUSTOM_ID: draußen-vor-der-schenke-söldners-bester-schluck.-tumult-dröhnt-aus-dem-inneren.
     :END:

ATHENE. APHRODITE. Der am Boden liegende PERDIX.

Aphrodite stößt auf die Statue des Bestien-Ikas. Perdix erlangt das
Bewusstsein zurück. Sie schließen aus der Statue, dass der Bestien-Ikas
sich in der Burg und bei König Pygmalion aufhalten muss. Als der Perdix
feststellt, dass der Mond bald am höchsten Punkt stehen wird, ergreift
er panikartig die Flucht. Athene und Aphrodite sind zunächst irritiert,
folgen ihm aber kurz darauf.

**** Ein paar Gassen weiter.
     :PROPERTIES:
     :CUSTOM_ID: ein-paar-gassen-weiter.
     :END:

ATHENE, APHRODITE, den PERDIX einholend.

Athene stellt Perdix zur Rede, erfährt aber nicht, wovor er sich so
fürchtet. Zuvor hören sie das ersterbende Geschrei ihrer Verfolger sowie
ein dämonisches Grollen.

**** Freier Platz in Paphos am nächsten Morgen.
     :PROPERTIES:
     :CUSTOM_ID: freier-platz-in-paphos-am-nächsten-morgen.
     :END:

Dutzende erschlagene Männer liegen herum. Eine Menschenmenge hat sich
gebildet. Aufgeregtes Gemurmel. Zwei GROSSE GESTALTEN IN SCHWARZEN
MÄNTELN mischen sich unter das Volk.

Atlas und Kronos betrachten die toten Männer. Sie vermuten, dass
Bestien-Ikas hinter der Gewalt steckt. Sie beschließen, später
wiederzukommen, um nach Spuren zu suchen.

**** Thronsaal des Pygmalion.
     :PROPERTIES:
     :CUSTOM_ID: thronsaal-des-pygmalion.-2
     :END:

OSTREOS weist einige Diener ein. ASKRINOS betritt den Saal in großer
Aufregung.

Askrinos berichtet Ostreos von den Toten auf dem Platz und den toten
Wachen auf dem Friedhof. Ostreos zeigt sich von den Toten auf dem Platz
nicht beeindruckt. Askrinos erfährt etwas von einem Geheimnis des
Königs, erfährt aber nicht welches. Auch der zwischenzeitlich
eingetroffene Pygmalion lässt sich sein Geheimnis nicht entlocken.
Askrinos spielt mit dem Gedanken, sich dem König als Modell für eine
Statue anzubieten. Weder Pygmalion noch Ostreos nehmen seinen Vorschlag
ernst. Der Gedanke scheint Askrinos jedoch ernst zu sein.

*** @@html:<a name="fuenfter-gesang">@@@@html:</a>@@FÜNFTER GESANG -- In
giftig, tiefen Wässern
    :PROPERTIES:
    :CUSTOM_ID: fünfter-gesang-in-giftig-tiefen-wässern
    :END:

**** Unter dem Nymphäum zu Kourion.
     :PROPERTIES:
     :CUSTOM_ID: unter-dem-nymphäum-zu-kourion.
     :END:

GAIA, URANUS, HADES, THEMIS, die Wasserstufen hinabsteigend. Über ihnen
toben noch immer die Erschütterungen der Einschläge.

Unter dem Nymphäum stoßen Gaia, Uranus, Hades und Themis auf einen
geschändeten Brunnen. Erinnyen hausen dort unten und berichten von der
Rachewut des Skylos, der die Stadt vernichten will für den Verrat des
Königs Stesenor, der den Persern 150 Schiffe überließ. Gaia schlägt vor,
den Stesenor an Skylos auszuliefern, um ein Blutvergießen zu verhindern.
Die Erinnyen weisen sie darauf hin, dass die Stadtbewohner einen letzten
Ausfall planen. Über ihnen verstummen die Erschütterungen. Die Erinnyen
behaupten, dass sich die Heere wohl schon gegenüberstehen. Gaia
beschließt, sich selbst in die Schlacht gegen Skylos zu stürzen. Gaia
kann die Erinnyen überreden, ihr bzw. Bestien-Ikas beizustehen, da seine
Rachewut um einiges größer als die des Skylos sein dürfte (er hasst die
Titanen). Zitat: “Er trägt eure ungeborenen Schwestern in sich.”

**** Streitmacht des Skylos vor den Toren Kourions.
     :PROPERTIES:
     :CUSTOM_ID: streitmacht-des-skylos-vor-den-toren-kourions.
     :END:

Auf der anderen Seite baut sich ein Heer aus halb verhungerten, kranken
oder halb verdursteten STADTBEWOHNERN auf. Darunter ALTE, FRAUEN und
KINDER. SKYLOS und sein Hauptmann DELOS in voller Schlachtmontur.

Man erfährt, dass Skylos die Brunnen hat vergiften lassen. Skylos will
alle bis zum kleinsten Kind töten. Delos bittet die Götter voller
Verzweiflung insgeheim um Vergebung. Sie rücken vor zum Angriff.

**** Zusammengerotteter Haufen der Bewohner Kourions vor den
Stadtmauern.
     :PROPERTIES:
     :CUSTOM_ID: zusammengerotteter-haufen-der-bewohner-kourions-vor-den-stadtmauern.
     :END:

Sie stehen ungeordnet herum und sehen das feindliche Heer auf sich
zumarschieren.

Gaia, Uranus, Themis und Hades tauchen mitten im Heer der Stadtbewohner
auf. Uranus entfesselt einen Sturmregen über dem Heer des Skylos, in dem
die gesamte Armee verschwidnet. Als die Männer des Skylos am Boden sind,
beschließen die Stadtbewohner, sie niederzumachen. Gaia will dies
verhindern und verwandelt sich in ihre RIESENGESTALT. Nachdem sie die
angreifenden Stadtbewohner vertrieben hat, kehrt sie zurück und bricht
zusammen. Hades bringt sie in den Tartarus. (Zuvor schießen die Erinnyen
auf das Heer des Skylos zu. Der Versuch, die Erinnyen mit geworfenen
Steinen anzulocken, schläft gehl. Die Erinnyen gehen im folgenden
Sturmregen des Uranus unter.)

*** @@html:<a name="sechster-gesang">@@@@html:</a>@@SECHSTER GESANG --
Heimlichtuerische Nächte
    :PROPERTIES:
    :CUSTOM_ID: sechster-gesang-heimlichtuerische-nächte
    :END:

**** Ausgang der Schenke Zum Goldenen Talente in Paphos. Die Nacht ist
erst wenige Stunden alt.
     :PROPERTIES:
     :CUSTOM_ID: ausgang-der-schenke-zum-goldenen-talente-in-paphos.-die-nacht-ist-erst-wenige-stunden-alt.
     :END:

KRONOS und ATLAS treten durch den Ausgang auf die Straße.

Kronos und Atlas treten aus einer Schenke, in der sie von dem Lösegeld
(#eine# Münze) erzählt haben, das sie auf Hinweise auf den Bestien-Ikas
ausgesetzt haben. Wenig später tritt schon ein Schatten an sie heran und
berichtet von der steinernen Statue des Bestien-Ikas, die er auf dem
Platz gesehen haben will, auf dem die toten Männer lagen. Der Schatten
schließt daraus, dass König Pygmalion den Bestien-Ikas aus Stein
geschlagen haben könnte und sich der Bestien-Ikas aus diesem Grund
irgendwo im Palast aufhalten muss.

**** Prachtgasse zum Palast zu Paphos.
     :PROPERTIES:
     :CUSTOM_ID: prachtgasse-zum-palast-zu-paphos.
     :END:

Tiefschwarze Nacht. WACHEN stehen vor dem Tor und auf den Zinnen.
PERDIX, APHRODITE und ATHENE lugen um eine Häuserecke.

Die Wachen auf und vor der Burg bewegen sich nicht.

**** Kanalisation zu Paphos.
     :PROPERTIES:
     :CUSTOM_ID: kanalisation-zu-paphos.
     :END:

ATHENE. APHRODITE. PERDIX. Um sie herum tropft und tröpfelt es.

Perdix pinkelt in das Waschwasser des Königs. Sie steigen zum Kerker
hinauf.

**** Dunkler Gang.
     :PROPERTIES:
     :CUSTOM_ID: dunkler-gang.
     :END:

PERDIX. ATHENE. APHRODITE. Fackeln spenden ein schwaches Licht.

Sie verstecken sich un belauschen den Kronos und den Atlas in der
Dunkelheit. (Zuerst kommen sie an einigen erstarrten Gefangenen vorbei.)
Sie beschließen, den beiden in die oberen Stockwerke zu folgen. Perdix
montiert sich ein Rohr auf den Arm.

**** Gang zu den Kerkeranlagen.
     :PROPERTIES:
     :CUSTOM_ID: gang-zu-den-kerkeranlagen.
     :END:

PERDIX, ATHENE, APHRODITE schleichen durch die Tür zum Kerker. Vor ihnen
liegen zwei tote Wachen in ihrem eigenen Blute.

Sie folgen der Spur der toten Wachen.

**** Erdgeschoss der Burg zu Paphos.
     :PROPERTIES:
     :CUSTOM_ID: erdgeschoss-der-burg-zu-paphos.
     :END:

PERDIX. ATHENE. APHRODITE. Eine Vielzahl toter WACHEN.

Sie schleichen an weiteren Wachen vorbei. HJinter einer Tür meinen sie,
den Bestien-Ikas, Kronos und Atlas zu hören. Perdix beginnt damit, mit
seiner ROHR-ARMBRUST + WASSERPFEILEN die Lichter auf dem Gang
auszuschießen. Athene soll hineinstürmen und die Titanen fällen.

**** Gerichtsraum neben dem Thronsaal.
     :PROPERTIES:
     :CUSTOM_ID: gerichtsraum-neben-dem-thronsaal.
     :END:

KRONOS. ATLAS. BESTIEN-IKAS, in Ketten.

Bestien-Ikas schafft es, die Ketten aus der Wand zu reißen und stürzt
sich auf sie. Kronos hält Bestien-Ikas' Zeitstrahl an und lässt ihn
erstarren. Gerade, als sie den Raum verlassen wollen, prescht Athene in
den Raum und rennt den Kronos um. Perdix kommt hinterher und zielt mit
dem Roh auf seinem Arm auf den Atlas, der noch den Bestien-Ikas auf den
Armen trägt. Nach kurzer Verhanadlung darf Atlas den Kronos mit sich
nehmen und Athene und Perdix erhalten den Bestien-Ikas zurück. Kurz
nachdem Kronos und Atlas den Raum verlassen haben, ertönt auf dem Gang
vor der Tür der Schrei der Aphrodite.

**** Thronsaal vor dem Gerichtsraum.
     :PROPERTIES:
     :CUSTOM_ID: thronsaal-vor-dem-gerichtsraum.
     :END:

ATLAS. KRONOS, die kreischende und strampelnde APHRODITE über der
Schulter tragend.

Kronos und Atlas entführen die Aphrodite. Athene zerstreitet sich mit
Perdix und lässt ihn zurück (trennt sich von ihm), da sie Perdix die
Schuld an Aphrodites Entführung gibt, da er sie vom finalen Schlag
zurückgehalten hat.

*** @@html:<a name="siebter-gesang">@@@@html:</a>@@SIEBTER GESANG -- Die
Kraft des Kronos
    :PROPERTIES:
    :CUSTOM_ID: siebter-gesang-die-kraft-des-kronos
    :END:

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-1
     :END:

URANUS, die GAIA tragend. HADES. THEMIS.

Uranus, Themis, Hades entdecken, dass der Kopf des Daedalus nicht mehr
in der ritze im Tartarus steckt. Hades macht sich auf, unsichtbar in der
Himmelsfeste zu spionieren. (Gaia ist noch immer bewusstlos. Solange
wollen Uranus und Themis im Taratarus warten.)

**** Gang zum Kerker in der Burg zu Paphos.
     :PROPERTIES:
     :CUSTOM_ID: gang-zum-kerker-in-der-burg-zu-paphos.
     :END:

Einige tote WACHEN. PYGMALION, über die Toten blickend. OSTREOS.
ASKRINOS.

Sie betrachten die toten Wachen. Askrinos vermutet einen Menschen hinter
der Tat. Askrinos bietet an, sich in den Untergrund von Paphos
einzuschleusen, um nach dem oder den Mördern zu suchen. Der König
akzeptiert. Als der König verschwunden ist, kommt Askrinos wieder auf
die Bildhauereri des Königs zu sprechen. Als Ostreos ihm deutliche
Hinweise zu geben versucht, die letzte Wahrheit aber noch immer nicht
ruasrücken will, stürmt Askrinos wütend hinaus und verspricht, sich dem
König als Modell/Vorlage anzubieten, um die Wahrheit zu erfahren (die
endgültige Wahrheit).

**** Geheimes Labor des Perdix.
     :PROPERTIES:
     :CUSTOM_ID: geheimes-labor-des-perdix.
     :END:

Einige AMAZONEN. PERDIX. BESTIEN-IKAS, noch immer die losgerissenen
Ketten an den Handgelenken.

Perdix führt den Ikas in sein Labor, um das Maß für die neuen Schwingen
zu nehmen. Unterwegs versucht er, dem Bestien-Ikas einen kurzen Blick in
die Rolle des Daedalus abzuluchsen. Bestien-Ikas verweigert ihm diese
Bitte vehement (“Erst die Schwingen.”). Darüber hinaus erzählt Perdix
dem Bestien-Ikas, dass sie (Perdix und die Amazonen) planen, König
Pygmalion abzusetzen (= zu ermorden) und die Stadt zu übernehmen. Paphos
soll die erste Stadt werden, die von einer Frau regiert wird.
Bestien-Ikas hält nicht allzu viel von dem Plan.

**** Werkstatt des Perdix.
     :PROPERTIES:
     :CUSTOM_ID: werkstatt-des-perdix.
     :END:

PERDIX. BESTIEN-IKAS.

Perdix nimmt Maß am Bestien-Ikas. Als die Nattern nach ihm schnappen,
lässt er Bestien-Ikas selbst Maß anlegen. Er empfiehlt Bestien-Ikas zu
lernen, die Nattern zu beherrschen und im Kampf einzusetzen. Sie kommen
kurz auf die Frau des Daedalus zu sprechen und dass niemand je von ihr
gehört zu haben scheint.

**** Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: himmelsfeste.-1
     :END:

KRONOS, sich in Albträumen windend.

Kronos windet sich in Albträumen vom Bestien-Ikas. Atlas kommt
herbeigeeilt und berichtet von dem Kopf, den Iapetos und Koios aus dem
Tartarus mitgebracht haben. Kronos will sich den erwachten Kreios
betrachten.

**** Anderer Teil der Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: anderer-teil-der-himmelsfeste.
     :END:

KOIOS. KREIOS. HYPERION. IAPETOS. MENOITIOS. Der SCHATTEN. Sie stehen um
etwas herum. Unzählige DÄMONEN flattern umher. APHRODITE, in Ketten
gelegt. KRONOS und ATLAS kommen hinzu.

Die Titanen haben nicht die geringste Ahnung, zu welchem Zweck der Kopf
sich in der Ritze befand. Sie vermuten, dass die Aphrodite etwas weiß
und drohen ihr, sie zu foltern. Sie gewähren der Aphrodite eine Nacht
Bedenkzeit. Der Hades hat alles unsichtbar beobachtet. Für seine
Verdienste bei der Pflege des Kreios verwandelt Kronos den Schatten in
einen gewaltigen Schattenkoloss und lässt ihn auf die Stadt Paphos los,
damit er seine Kräfte ausprobieren kann.

*** @@html:<a name="achter-gesang">@@@@html:</a>@@ACHTER GESANG -- Das
Wesen der Macht
    :PROPERTIES:
    :CUSTOM_ID: achter-gesang-das-wesen-der-macht
    :END:

**** Dunkle Gasse in Paphos. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: dunkle-gasse-in-paphos.-nacht.
     :END:

Heftiger Regen. Ein SCHATTEN kauert in einer Ecke und tarnt sich.
Langsame und gleichmäßige Schritte nähern sich. Ein weiterer SCHATTEN
taucht auf und bleibt stehen.

Askrinos verhört einen möglichen Informanten. Drei Nächte und drei Tage
will er ihm gewähren, dem Askrinos zu berichten, was er wissen will.
Wenn er es schafft, will er den Informanten zu einem reichen Mann
machen.

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-2
     :END:

URANUS, über der GAIA kauernd. THEMIS. HADES erscheint.

Hades berichtet von dem, was er in der Himmelsfeste gesehen hat. Als sie
fast schon die Hoffnung verlieren, erwacht die Gaia und hält eine
ergreifende Ansprache. Sie beschließen, nach Paphos zu gehen und nach
dem Bestien-Ikas zu suchen -- selbst, falls er tot sein sollte.

**** Geheimes Labor des Perdix.
     :PROPERTIES:
     :CUSTOM_ID: geheimes-labor-des-perdix.-1
     :END:

Ein mächtiges Donnern bringt das Labor zum Erbeben. PERDIX.
BESTIEN-IKAS. Einige AMAZONEN.

Die Erde bebt. Bestien-Ikas stürzt sich mit seinen soeben fertig
gewordenen und ungetzesteten Schwingen auf das, was immer die
Erschütterungen verursacht.

**** Stadt Paphos. Marktplatz.
     :PROPERTIES:
     :CUSTOM_ID: stadt-paphos.-marktplatz.
     :END:

Reges Treiben. MARKTBESUCHER.

Der Schattenkoloss hält auf Paphos zu. Bestien-Ikas erscheint in der
Ferne.

**** Paphos. An der Stadtmauer.
     :PROPERTIES:
     :CUSTOM_ID: paphos.-an-der-stadtmauer.
     :END:

SCHATTENKOLOSS, auf die Stadtmauer einschlagend. BESTIEN-IKAS, auf ihn
zufliegend.

Der Schattenkoloss schmettert den Bestien-Ikas gegen die Stadtmauer. Der
Bestien-Ikas fällt regungslos zu Boden.

**** Straße nach Paphos. Abenddämmerung.
     :PROPERTIES:
     :CUSTOM_ID: straße-nach-paphos.-abenddämmerung.
     :END:

Drei versteinerte DIRNEN. GAIA, URANUS, THEMIS, HADES erscheinen.

Sie erblicken den Schattenkoloss und stürmen vor zum Angriff.

**** Innerhalb der zerschmetterten Stadtmauern der Stadt Paphos.
     :PROPERTIES:
     :CUSTOM_ID: innerhalb-der-zerschmetterten-stadtmauern-der-stadt-paphos.
     :END:

HADES. URANUS. THEMIS. GAIA. Der SCHATTENKOLOSS mit dem Rücken zu ihnen.

Sie kämpfen gegen den Schattenkoloss. Hades setzt seinen
Nekromantengriff ein, die Stadtbewohner attackieren den Schattenkoloss
mit ihren Kriegsmaschinen, Gaia in ihrer Riesengestalt und können den
Schattenkoloss schließlich vertreiben. Während des Nekromantengriffs
ging ein Teil der verdorbenen Macht auf den Hades über. Er hat sich in
den Neuen Hades verwandelt und stellt sich gegen die anderen (“Kronos
ist mein neuer Herr.”) Als er die anderen angreifen will, wird er von
zwei Speeren der Stadtbewohner durchbohrt und flieht. Der Mob geht
direkt auf die anderen los. Sie ergreifen die Flucht. Uranus will sich
ihnen in den Weg stellen, als ein steinerner Bestien-Ikas erscheint und
den Mob vertreibt. Während sie fliehen, stoßen sie auf den Perdix und
den zerschmetterten Bestien-Ikas. Der Stein-Ikas rennt an Uranus und der
Themis vorbei und hinter Gaia, Perdix und den Bestien-Ikas hinterher.
Als die drei im Wald verschwinden trennen sie sich. Gaia, Perdix,
Bestien-Ikas, Stein-Bestien-Ikas verschwinden im Wald, Uranus und Themis
bleiben in der Stadt zurück.

*** @@html:<a name="neunter-gesang">@@@@html:</a>@@NEUNTER GESANG --
Durch das schwarze Todesdunkel
    :PROPERTIES:
    :CUSTOM_ID: neunter-gesang-durch-das-schwarze-todesdunkel
    :END:

**** Burgberg über Paphos. Nacht. Blick über die Stadt.
     :PROPERTIES:
     :CUSTOM_ID: burgberg-über-paphos.-nacht.-blick-über-die-stadt.
     :END:

PYGMALION. OSTREOS.

Pygmalion wünscht sich, den Schattenkoloss aus Stein zu hauen. Askrinos
weiß nichts Neues zu berichten. Als Askrinos weg ist, erscheint Ostreos
und fragt, was Askrinos als Belohnung für sein Tun verlangt. Pygmalion
erzählt ihm, dass der Askrinos sich aus Stein hauen lassen möchte und
sich nicht von dem Gedanken abbringen ließ. Pygmalion spricht mit
Ostreos über seine Zweifel an seinem königlichen Leben. Am liebsten
würde er sich selber aus Stein hauen “und das alles beenden.” (“Es ist
die Überflüssigkeit, Ostreos, die uns ins Verderben reißt.”)

**** Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: himmelsfeste.-2
     :END:

KRONOS. ATLAS. APRHODITE, in Ketten. DAEDALUS-KOPF, von der Faust des
KRONOS herabbaumelnd.

Kronos versucht mit Hilfe des Daedalus-Kopfes aus der Aphrodite
herauszubekommen, was sie über den Kopf weiß. Als sie sich weiterhin
weigert, bindet er den Bart des Kopfes im Nacken der Aphrodite zusammen
und lässt ihn ihr vom Halse baumeln wie eine Kette.

**** Anderer Teil der Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: anderer-teil-der-himmelsfeste.-1
     :END:

KRONOS. ATLAS. Weitere TITANEN.

Atlas stellt den Kronos über den Kopf und sein hartes Vorgehen gegenüber
Aphrodite zur Rede. Der Schattenkoloss kehrt zurück und verwandelt sich
in den Schatten zurück. Kronos offenbart, dass er seine Finger im spiel
hatte, als der Hades den Nekromantengriff einsetzte. Er bezeichnet den
Neuen Hades als sein Gegenstück zum Bestien-Ikas.

**** Wald vor den zerstörten Mauern der Stadt Paphos.
     :PROPERTIES:
     :CUSTOM_ID: wald-vor-den-zerstörten-mauern-der-stadt-paphos.
     :END:

URANUS. THEMIS.

Sie treffen auf Pan, einen Sohn des Kronos. Pan sagt, er und sein Vater
seien zerstritten miteinander. Die bewachsene Statue des Stein-Ikas
steht herum. Er will sich ihnen anschließen. Er zeigt ihnen den Gang, in
dem Gaia, Perdix und der Bestien-Ikas verschwunden sind. Nachdem Themis
und Uranus den geheimen Gang betreten haben, lässt Pan dein Eingang mit
zufallen.

**** Unterirdischer Gang unter der Stadtmauer.
     :PROPERTIES:
     :CUSTOM_ID: unterirdischer-gang-unter-der-stadtmauer.
     :END:

Völlige Finsternis. URANUS. THEMIS. Das Flötenspiel des Pan dringt von
draußen herein.

Themis wird von Visionen geplagt und wird ohnmächtig. Uranus trägt sie
durch die Dunkelheit. Sie werden von Untoten attackiert. Uranus schafft
es, sie aus dem Gang nach draußen zu retten.

**** Grabhügel zu Paphos. Helllichter Tag.
     :PROPERTIES:
     :CUSTOM_ID: grabhügel-zu-paphos.-helllichter-tag.
     :END:

URANUS, die bewusstlose THEMIS tragend. UNTOTE starren ihm aus der Gruft
hinter zerschmetterten Toren entgegen.

Sie beschließen, Gaia, Perdix und Bestien-Ikas zu suchen. Dazu müssen
sie zurück in den Wald. Themis beklagt die Rachsucht aller Parteien.
Uranus will sich an Pan rächen, falls er ihm über den Weg laufen sollte.

*** @@html:<a name="zehnter-gesang">@@@@html:</a>@@ZEHNTER GESANG --
Nicht vorhandene Verschwörungen
    :PROPERTIES:
    :CUSTOM_ID: zehnter-gesang-nicht-vorhandene-verschwörungen
    :END:

**** Dunkle Gasse in Paphos. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: dunkle-gasse-in-paphos.-nacht.-1
     :END:

Heftiger Regen. Ein SCHATTEN kauert hinter einem verrammelten
Marktstand. Gleichmäßige Schritte nähern sich. Ein weiterer SCHATTEN
taucht auf und bleibt stehen.

Askrinos trifft seinen Informanten. Nachdem der Informant ihm berichtet,
dass es keine Verschwörung in der Stadt gibt (vielmehr hält der Untote
für die Übeltäter), lässt Askrinos ihn töten. Mit seinen letzten Worten
schwört der Informant, sich an ihm zu rächen. Egal, ob tot, lebendig
oder untot.

** @@html:<a name="personenverzeichnis">@@@@html:</a>@@Ausführliches
Personenverzeichnis
   :PROPERTIES:
   :CUSTOM_ID: ausführliches-personenverzeichnis
   :END:

[[file:aphrodite.org][Aphrodite]] · [[file:athene.org][Athene]] · [[file:atlas.org][Atlas]] ·
[[file:bestien-ikas.org][Bestien-Ikas]] · [[file:briareos.org][Briareos]] ·
[[file:daedalus.org][Daedalus]] · [[file:demeter.org][Demeter]] · [[file:gaia.org][Gaia]] ·
[[file:gyges.org][Gyges]] · [[file:hades.org][Hades]] · [[file:hera.org][Hera]] ·
[[file:hestia.org][Hestia]] · [[file:hyperion.org][Hyperion]] · [[file:iapetos.org][Iapetos]]
· [[file:ikas.org][Ikas]] · [[file:koios.org][Koios]] · [[file:kottos.org][Kottos]] ·
[[file:kreios.org][Kreios]] · [[file:kronos.org][Kronos]] ·
[[file:kronospriester.org][Kronospriester]] · [[file:menoitios.org][Menoitios]] ·
[[file:mnemosyne.org][Mnemosyne]] · [[file:okeanos.org][Okeanos]] ·
[[file:perdix.org][Perdix]] · [[file:phoibe.org][Phoibe]] · [[file:poseidon.org][Poseidon]] ·
[[file:rhea.org][Rhea]] · [[file:schatten-des-kronospriesters.org][Schatten des
Kronospriesters]] · [[file:tethys.org][Tethys]] · [[file:theia.org][Theia]] ·
[[file:themis.org][Themis]] · [[file:uranus.org][Uranus]] · [[file:zeus.org][Zeus]]

*** Tiere, Bestien, Fabelwesen
    :PROPERTIES:
    :CUSTOM_ID: tiere-bestien-fabelwesen
    :END:

[[file:python.org][Python]]

*** Orte, Länder, Flüsse
    :PROPERTIES:
    :CUSTOM_ID: orte-länder-flüsse
    :END:

[[file:athen.org][Athen]] · [[file:attika.org][Attika]] ·
[[file:himmelsfestung-des-uranus.org][Himmelsfeste des Uranus]] ·
[[file:olymp.org][Olymp]] · [[file:orakel-von-delphi.org][Orakel von Delphi]] ·
[[file:paphos.org][Paphos]] · [[file:parnass.org][Parnass]] · [[file:salamis.org][Salamis]] ·
[[file:tartarus.org][Tartarus]] · [[file:thermodon.org][Thermodon (Fluss)]] ·
[[file:thermodonion.org][Thermodonion]] · [[file:thrakien.org][Thrakien]] ·
[[file:zyprus.org][Zyprus]]

** @@html:<a name="easter-eggs">@@@@html:</a>@@Easter Eggs
   :PROPERTIES:
   :CUSTOM_ID: easter-eggs
   :END:

*** ZWEITER GESANG -- Triumph der Toten
    :PROPERTIES:
    :CUSTOM_ID: zweiter-gesang-triumph-der-toten-1
    :END:

Der Titel ist eine Anspielung auf ein
[[https://de.wikipedia.org/wiki/Triumph_of_Death][Album]] der
schweizerischen Extreme-Metal-Band
[[https://de.wikipedia.org/wiki/Hellhammer][Hellhammer]]:

#+BEGIN_EXAMPLE
    Hellhammer. Triumph of Death. Prowlin’ Death Records 1983.
#+END_EXAMPLE

*** DRITTER GESANG -- Der Raub des Daedalus
    :PROPERTIES:
    :CUSTOM_ID: dritter-gesang-der-raub-des-daedalus-1
    :END:

Innerhalb des Nymphäums.

#+BEGIN_EXAMPLE
    Das also ist des Beckens Kern!
    URANUS

    Goethe. Faust I.
#+END_EXAMPLE

** @@html:<a name="zitate">@@@@html:</a>@@Zitate
   :PROPERTIES:
   :CUSTOM_ID: zitate
   :END:

*** ZWEITER GESANG -- Triumph der Toten Grabhügel außerhalb von Paphos.
Nacht.
    :PROPERTIES:
    :CUSTOM_ID: zweiter-gesang-triumph-der-toten-grabhügel-außerhalb-von-paphos.-nacht.
    :END:

#+BEGIN_EXAMPLE
    Schnell, voran zum Klingenhack!
    DRITTE WACHE
#+END_EXAMPLE

** @@html:<a name="vorsaetzliche-verstoesse">@@@@html:</a>@@Vorsätzliche
Verstöße gegen Rechtschreibung & Grammatik
   :PROPERTIES:
   :CUSTOM_ID: vorsätzliche-verstöße-gegen-rechtschreibung-grammatik
   :END:

/Too much to mention .../

** @@html:<a name="fahrlaessige-verstoesse">@@@@html:</a>@@Fahrlässige
Verstöße gegen Rechtschreibung, Formatierung, Grammatik, Logik
   :PROPERTIES:
   :CUSTOM_ID: fahrlässige-verstöße-gegen-rechtschreibung-formatierung-grammatik-logik
   :END:

*** 1. Auflage
    :PROPERTIES:
    :CUSTOM_ID: auflage
    :END:

-  S. 89

#+BEGIN_QUOTE
  +Uranus+ URANUS (sie eine Weile betrachtend, dann kopfschüttelnd).
#+END_QUOTE

Fehler: Formatierung.

-  S. 256

#+BEGIN_QUOTE
  (Er macht auf dem Absatz kehrt und marschiert aus dem Raum. Hauptmann
  der Wache ab.)
#+END_QUOTE

Fehler: Sie stehen auf dem Burgberg. Der Burgberg ist kein geschlossener
Raum.

-  S. 260

#+BEGIN_QUOTE
  KRONOS, ATLAS, +APRHODITE+ APHRODITE, in Ketten. DAEDALUS-KOPF, von
  der Faust des KRONOS herabbaumelnd.
#+END_QUOTE

Fehler: Typo.

** @@html:<a name="offene-handlungsstraenge">@@@@html:</a>@@Offene
Handlungsstränge
   :PROPERTIES:
   :CUSTOM_ID: offene-handlungsstränge
   :END:

-  Athenes Rache an Zeus und Verbleib der Athene.
-  Entführung der Rhea.
-  Schlacht bei Kourion/Streitmacht des Skylos.
-  Entführung der Aphrodite.
-  Neuer Hades.
-  Daedalus' Letzter Wille (Schriftrolle).
-  Askrinos' Aufklärung der Verschwörung und sein Wunsch nach
   Unsterblichkeit.
-  Uranus' Rache an Pan.
-  Uranus' und Themis' Suche nach Gaia, Perdix und Bestien-Ikas.
-  Erwachen der Toten in Paphos.
-  Verschlingung der Kroniden.
-  Hekatoncheiren und Kyklopen im Leib der Gaia.
