#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Titaneion-Titanenschlacht Episoda 1: Bestienborn
#+OPTIONS: toc:1

** Personae
   :PROPERTIES:
   :CUSTOM_ID: personae
   :END:

-  [[file:menschen.org][Menschen]]
-  [[file:ikas.org][Ikas]]: Thrakischer Heerführer.
-  [[file:pandrinos.org][Pandrinos]]: Hauptmann des Ikas.
-  [[file:sandrias.org][Sandrias]]: Weiterer Kampfgefährte des Ikas.
-  [[file:protogenoi.org][Protogenoi]] und [[file:titanen.org][Titanen]]
-  [[file:gaia.org][Gaia]]: Die Allmutter. Uranus trieb ihr die Kyklopen und
   Hekatoncheiren in den Leib.
-  [[file:uranus.org][Uranus]]: Verkörperung des Himmels. Gatte der Gaia.
-  [[file:kronos.org][Kronos]]: Der Krumme. Jüngster Sohn des Uranus und der
   Gaia. Vom Vater verstoßen.
-  Sonstige Begriffe und [[file:fabelwesen.org][Fabelwesen]]
-  [[file:kyklopen.org][Kyklopen]]: Einäugige Riesen.
-  [[file:hekatoncheiren.org][Hekatoncheiren]]: Riesen mit hundert Armen und
   fünfzig Köpfen.
-  [[file:kroniden.org][Kroniden]]: Kinder des Kronos.

   -  [[file:zeus.org][Zeus]]
   -  [[file:hades.org][Hades]]
   -  [[file:poseidon.org][Poseidon]]
   -  [[file:hera.org][Hera]]
   -  [[file:hestia.org][Hestia]]
   -  [[file:demeter.org][Demeter]]

-  [[file:uraniden.org][Uraniden]]: Kinder des Uranus.

   -  [[file:kronos.org][Kronos]]
   -  [[file:rhea.org][Rhea]]
   -  [[file:themis.org][Themis]]
   -  [[file:koios.org][Koios]]
   -  [[file:hyperion.org][Hyperion]]
   -  [[file:iapetos.org][Iapetos]]
   -  [[file:kreios.org][Kreios]]
   -  [[file:okeanos.org][Okeanos]]
   -  [[file:tethys.org][Tethys]]
   -  [[file:phoibe.org][Phoibe]]
   -  [[file:theia.org][Theia]]
   -  [[file:mnemosyne.org][Mnemosyne]]

-  [[file:kronion.org][Kronion]]: Sohn des Kronos (z. B. Zeus).
-  [[file:uranion.org][Uranion]]: Sohn des Uranus (z. B. Kronos).
-  Weitere [[file:goetter.org][Götter]], [[file:titanen.org][Titanen]],
   [[file:fabelwesen.org][Fabelwesen]].

** Gesängekatalog
   :PROPERTIES:
   :CUSTOM_ID: gesängekatalog
   :END:

*** ERSTER GESANG -- Der Tod des Ikas
    :PROPERTIES:
    :CUSTOM_ID: erster-gesang-der-tod-des-ikas
    :END:

**** Meerenge bei Salamis. Seeschlacht.
     :PROPERTIES:
     :CUSTOM_ID: meerenge-bei-salamis.-seeschlacht.
     :END:

IKAS DER THRAKER. PANDRINOS. Beide in voller Schlachtmontur.

Seeschlacht gegen Euböa.

**** Euböische Trireme.
     :PROPERTIES:
     :CUSTOM_ID: euböische-trireme.
     :END:

IKAS und DRONOS im Zweikampf. Das halbe Meer steht in Flammen.

IKAS erschlägt den DRONOS, lästert den Göttern, wird von einem Blitz
erschlagen und verschwindet.

**** Verlassener Teil des Tartarus. Stille.
     :PROPERTIES:
     :CUSTOM_ID: verlassener-teil-des-tartarus.-stille.
     :END:

Der am Boden liegende IKAS. Eine ALTE FRAU mit dickem Bauch erscheint.

IKAS findet sich im Tartarus wieder. Die alte Frau erteilt ihm den
Auftrag, ihrem Sohn Kronos ein Hippe zu bringen, damit er den Uranus
entmannen kann. Die alte Frau entpuppt sich als Gaia. Ikas macht sich
mithilfe der Hippe an den Aufstieg aus dem Tartarus.

*** ZWEITER GESANG -- Die Entmannung des Uranus
    :PROPERTIES:
    :CUSTOM_ID: zweiter-gesang-die-entmannung-des-uranus
    :END:

**** Erde.
     :PROPERTIES:
     :CUSTOM_ID: erde.
     :END:

Der vor einem Busch liegende KRONOS.

Ikas findet den Kronos und erzählt ihm vom Plan der Gaia. Sie springen
in den Tartarus hinunter.

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.
     :END:

IKAS. KRONOS. Sie landen schwer im Tartarus.

Kronos entmannt Uranus und hält den Ikas unter das tropfende Blut. Ikas
trinkt das Blut des Uranus und verwandelt sich in eine schreckliche
Bestie. Aphrodite entsteigt dem Gemächt des Uranus. Ikas macht sich auf,
Kronos zu suchen, Aphrodite folgt ihm. Es kommt zu mehreren
Prophezeiungen. Uranus schmäht den Kronos.

*** DRITTER GESANG -- Die Verschlingung der Kroniden
    :PROPERTIES:
    :CUSTOM_ID: dritter-gesang-die-verschlingung-der-kroniden
    :END:

**** Himmelsfeste des Uranus.
     :PROPERTIES:
     :CUSTOM_ID: himmelsfeste-des-uranus.
     :END:

KRONOS. Sämtliche Kroniden: ZEUS, POSEIDON, HADES, HESTIA, DEMETER,
HERA.

Kronos verschlingt die Kroniden. Aphrodite erscheint und warnt ihn
Bestien-Ikas. Bestien-Ikas erscheint und wirft sich auf ihn. Kronos
reißt ihm die Flügel heraus und zerstört die Hippe. Er wirft
Bestien-Ikas durch die Wolkendecke. Hades kann fliehen und schwört, mit
dem Bestien-Mann zurückzukehren. Aphrodite entwischt ihm ebenso. Kronos
schwört, ein Heer aus Titanen aufzustellen. Kronos denkt, dass Hades es
ist, der ihn verrät.

**** Freier Fall zwischen Himmel und Erde
     :PROPERTIES:
     :CUSTOM_ID: freier-fall-zwischen-himmel-und-erde
     :END:

Der stürzende BESTIEN-IKAS. HADES.

Hades errettet den Bestien-Ikas. Hades schwört Rache.

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-1
     :END:

HADES trägt den bewusstlosen BESTIEN-IKAS.

Hades erzählt Gaia, was im Himmel vorgefallen ist. Uranus kommt dazu und
schwört, ein besserer “Mensch” zu werden. Uranus schlägt vor, sich an
Daedalus zu wenden. Daedalus hockt im Kerker, dorthin Hades und
Bestien-Ikas auf.

*** VIERTER GESANG -- Die Befreiung des Daedalus
    :PROPERTIES:
    :CUSTOM_ID: vierter-gesang-die-befreiung-des-daedalus
    :END:

**** Kerker in Euböa.
     :PROPERTIES:
     :CUSTOM_ID: kerker-in-euböa.
     :END:

DAEDALUS in Ketten. Sein wahnsinniges Lachen hallt durch die finsteren
Gänge.

Bestien-Ikas befreit den Daedalus.

**** Geheimes Labor des Daedalus irgendwo in Attika.
     :PROPERTIES:
     :CUSTOM_ID: geheimes-labor-des-daedalus-irgendwo-in-attika.
     :END:

DAEDALUS. BESTIEN-IKAS setzt ihn auf den Boden. HADES noch immer
unsichtbar.

Bestien-Ikas bringt Daedalus in sein Geheimlabor. Es kommt zu
Unterhaltungen über die Götter und wie sie die Menschen ständig
kleinzuhalten versuchen. Hades schöpft Verdacht, die Ablehnung der
Götter und Titanen durch den Bestien-Ikas scheint ihm zu glaubhaft. Er
beschließt, Gaia zu berichten.

*** FÜNFTER GESANG -- Erste Titanenheerschau und Orakelspruch
    :PROPERTIES:
    :CUSTOM_ID: fünfter-gesang-erste-titanenheerschau-und-orakelspruch
    :END:

**** Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: himmelsfeste.
     :END:

Versammlung der Kinder des Uranus und der Gaia: KRONOS, OKEANOS,
HYPERION, KREIOS, KOIOS, IAPETOS, RHEA, TETHYS, THEMIS, PHOIBE, THEIA,
MNEMOSYNE.

Kronos berichtet seinen Titanengeschwistern von dem Vorfall mit
Bestien-Ikas und erbittet ihre Unterstützung. [[file:kreios.org][Kreios]] will
erst Gewissheit, ob es überhaupt zum Kampfe kommen wird (= ob der
Bestien-Ikas überhaupt noch lebt). Okeanos schlägt vor, Themis das
Orakel befragen zu lassen. Themis verwehrt Kronos ihre Unterstützung,
will ihm jedoch den Orakelblick als letzte Hilfe gewähren.

**** Hang des Parnass. Weg zum Orakel von Delphi. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: hang-des-parnass.-weg-zum-orakel-von-delphi.-nacht.
     :END:

Versammlung der Kinder des Uranus und der Gaia. PYTHON, eine geflügelte
Schlange und Bewacher des Orakels.

Am Python vorbei führt Themis die Titanen zum Orakel.

**** Orakel von Delphi. Nacht.
     :PROPERTIES:
     :CUSTOM_ID: orakel-von-delphi.-nacht.
     :END:

Sämtliche Kinder des Uranus und der Gaia.

Kronos sieht den Ikas mit Metallflügeln. Er sieht sich im Orakelbecken
mit einem seltsamen Wesen ringen (Dampf etc.). Götter kämpfen. Er
erblickt ein Laboratorum, Flügel mit Wachs hängen an der Wand. Sie
erkennen den Daedalus und hören den doppeltönigen Wind. Sie schließen
daraus, dass sich das gezeigte Labor auf Attika befinden muss. Auch
Bestien-Ikas ist im Labor zu sehen, die Flügel nur noch Stümpfe. Er
fragt jeden einzelnen Titanen nach seiner Unterstützung.

Es schließen sich ihm an: * [[file:kreios.org][Kreios]] *
[[file:iapetos.org][Iapetos]] * [[file:koios.org][Koios]] * [[file:hyperion.org][Hyperion]] *
[[file:atlas.org][Atlas der Harte]] * [[file:menoitios.org][Menoitios]]

Es verwehren ihre Hilfe: * [[file:okeanos.org][Okeanos]] * [[file:theia.org][Theia]] *
[[file:themis.org][Themis]] * [[file:rhea.org][Rhea]] * [[file:mnemosyne.org][Mnemosyne]] *
[[file:tethys.org][Tethys]] * [[file:phoibe.org][Phoibe]]

Rhea schwört, sich gegen Kronos zu erheben und sich seinen Gegnern
anzuschließen. Kronos beschwört und entsendet sein Dämonenheer nach
Attika.

*** SECHSTER GESANG -- Die Enthauptung des Daedalus
    :PROPERTIES:
    :CUSTOM_ID: sechster-gesang-die-enthauptung-des-daedalus
    :END:

**** Geheimes Labor des Daedalus.
     :PROPERTIES:
     :CUSTOM_ID: geheimes-labor-des-daedalus.
     :END:

DAEDALUS. BESTIEN-IKAS.

Dämonen überfallen das Labor. Daedalus wird tödlich getroffen und gibt
Bestien-Ikas und Hades eine Rolle mit einer Zeichnung mit, die sie
seinem Neffen Perdix bringen sollen. Als sie gehen wollen, weist er sie
daraufhin, dass Perdix seinen Kopf brauchen wird. Statt den Leichnam
mitzunehmen, reißt Bestien-Ikas dem Daedalus den Kopf ab und nimmt
diesen mit sich. Hades und Bestien-Ikas können im letzten Moment
fliehen.

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-2
     :END:

HADES und BESTIEN-IKAS, Kopf und Schriftrolle unter dem Arm, erscheinen.

Gaia überreicht Bestien-Ikas das Schwarze Vlies des Thrakischen Widders.
Gaia erwähnt, dass Athene sich inkognito in Athen in den Schenken
aufhält, seit sie mit Zeus gebrochen hat. Rhea erscheint und schließt
sich ihnen an. Den Kopf des Daedalus verstauen sie in einer Felsspalte
im Tartarus.

*** SIEBTER GESANG -- Die Urgewalt der Athene und finsterstes Schwören
    :PROPERTIES:
    :CUSTOM_ID: siebter-gesang-die-urgewalt-der-athene-und-finsterstes-schwören
    :END:

**** Schenke Zum Titanischen Trunke in Athen.
     :PROPERTIES:
     :CUSTOM_ID: schenke-zum-titanischen-trunke-in-athen.
     :END:

Bande lustiger Gesellen. Ein überaus kräftig gewachsenes Mannsweib. Eine
Eule im Gebälk.

Sie stoßen auf Athene, die sich gleich in einer zünftigen Rauferei
befindet. Ihre Eule Glaukos schicht sie fort, nachdem sie sie in den
Kampf geschicht hat. Bestien-Ikas fragt sie nach Perdix aus, muss ihm im
Gegenzug schwören, dass sie sich an Zeus rächen darf. Als Bestien-Ikas
ihr die Hand zum Schwur reicht, kommt seine Klauenhand zum Vorschein.
Bevor Athene die Lage eskalieren lassen kann, schläfert Hades sie ein
und trägt sie auf ihr Zimmer.

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-3
     :END:

GAIA hinkt mit gebeugtem Kreuz durch die Felsenklüfte. Das Gebrüll der
Hekatoncheiren und Kyklopen in ihrem Wanst ist zu vernehmen.

Kronos erscheint und stellt Gaia zur Rede. Er findet den Kopf des
Daedalus. Uranus und Gaia entsagen sich des Kronos, der Kronos entsagt
sich seiner Eltern und schwört Rache. Den Kopf des Daedalus lässt er
zurück. Aphrodite erscheint, sie such den Ikas. Die gedrückte Stimmung
droht sie zu vertreiben. Sie beschließen, auf die Rückkehr des Ikas zu
warten.

**** Eine finstere Seitengasse in Athen.
     :PROPERTIES:
     :CUSTOM_ID: eine-finstere-seitengasse-in-athen.
     :END:

BESTIEN-IKAS. RHEA. HADES, die bewusstlose ATHENE über der Schulter
tragend.

Athene erwacht. Sie versuchen, sie zu überzeugen, sich auf ihre Seite zu
stellen. Das Bestien-Ikas das Versprechen an Daedalus erfüllen will,
rührt sie dermaßen an, dass sie sich auf ihre Seite schlägt. Rhea mus
schwören, dass Athene ihren Sohn Zeus töten darf. Hades muss schwören,
ihr bei ihrer Rache an Zeus zu helfen. Erst nach langem Wehren willigt
der Totengott ein. Athene hat vergessen, wo sie den Perdix
zurückgelassen hat. Sie hofft, bei einem kräftigen Schluck die
Erinnerung wiederzufinden. Sie wirft sich die beim Schwur ohnmächtig
gewordene Rhea über die Schulter. Sie machen sich auf zum nächsten
Wirtshaus.

**** Schenke Quelle des Lyäus in Athen.
     :PROPERTIES:
     :CUSTOM_ID: schenke-quelle-des-lyäus-in-athen.
     :END:

HADES. BESTIEN-IKAS. ATHENE, die bewusstlose RHEA über der Schulter
tragend. Einige SCHENKENBESUCHER. SCHANKWIRT.

Sie fangen an zu trinken, die Lage gerät ein wenig außer Kontrolle. Sie
verplappern sich, wer sie alle sind und was ihre Mission ist. Der
Schankwirt bekommt spitze Ohren und will sie an den Kronos verraten.
Nachdem Rhea, Athene und Ikas bewusstlos sind, schleppt Hades sie alle
auf ihre Zimmer.

*** ACHTER GESANG -- Verrat und Harpyiensturm
    :PROPERTIES:
    :CUSTOM_ID: achter-gesang-verrat-und-harpyiensturm
    :END:

**** Tempel des Kronos zu Athen. Nacht. Kurz vor Sonnenaufgang.
     :PROPERTIES:
     :CUSTOM_ID: tempel-des-kronos-zu-athen.-nacht.-kurz-vor-sonnenaufgang.
     :END:

Zwei finstere Schatten stehen sich zwischen Säulen gegenüber.

Der Gastwirt berichtet einem Priester des Kronos von den Gästen in
seiner Schenke. Daraufhin erscheint Kronos selbst. Der Priester stürzt
ins Becken, der Schankwirt führt Kronos in sein Gasthaus, in dem er den
Hades und die anderen eingeschlossen hat.

**** Gästezimmer der Schenke Quelle des Lyäus in Athen.
     :PROPERTIES:
     :CUSTOM_ID: gästezimmer-der-schenke-quelle-des-lyäus-in-athen.
     :END:

HADES steht an der Tür. BESTIEN-IKAS erwacht.

Hades und Bestien-Ikas finden sich eingeschlossen in einem Zimmer
wieder. Ikas reißt die Tür heraus.

**** Flur der Schenke.
     :PROPERTIES:
     :CUSTOM_ID: flur-der-schenke.
     :END:

HADES. BESTIEN-IKAS.

Sie befreien Rhea und Athene. Kronos greift sie an, wirft den Kopf des
Schankwirtes ihnen vor die Füße und erwürft fast die Rhea. Kronos
flieht, die Schenke liegt in Trümmern. Sie beschließen, nach unten zu
gehen, damit Athene ihren Schluck bekommt. Hades nimmt den Kopf des
Schankwirts an sich.

**** Verwüstete Schenke Quelle des Lyäus in Athen.
     :PROPERTIES:
     :CUSTOM_ID: verwüstete-schenke-quelle-des-lyäus-in-athen.
     :END:

ATHENE. HADES. RHEA. BESTIEN-IKAS. Der Raum liegt unter Staub und
Trümmern.

Hades befragt den Kopf des Schankwirtes. Rhea nimmt Reißaus vor dem
schrecklichen Anblick. Der Kopf verrät, dass er dem Kronos nicht
verraten konnte, was Hades und die anderen vorhatten. Ihm wurde der Kopf
abgerissen, da Kronos “keine Zeugen gebrauchen” kann. Athene gibt dem
Kopf von seinem eigenen Brannt zu trinken. Draußen ertönt der Schrei der
Rhea. Menschen rufen “Harpyien!” Sie stürmen nach draußen.

**** Straße vor der Schenke Quelle des Lyäus in Athen.
     :PROPERTIES:
     :CUSTOM_ID: straße-vor-der-schenke-quelle-des-lyäus-in-athen.
     :END:

Harpyien und Dämonen toben, Menschen werden zerrissen, in die Lüfte
entführt, Feuer brennen. HADES, ATHENE, BESTIEN-IKAS stürzen nach
draußen.

Harpyien greifen die Stadt an. Athene Balken verfehlt sein Ziel, es
kommt zum Streit. Die Götter gestehen, dass es ihn nicht darum geht, die
Menschen zu retten, sondern um die Macht und dass sie nicht Händen der
Titanen, sondern nur in Götterhande gehört.

**** Schlachtenerzitternde Stadt Athen.
     :PROPERTIES:
     :CUSTOM_ID: schlachtenerzitternde-stadt-athen.
     :END:

DÄMONENHORDEN. Sterbende Stadtbewohner. Drei kaum auszumachende
GESTALTEN reißen Schneise um Schneise in die Bestienmassen.

Harpyien entführen die Rhea. Menschen werden gepackt und aus großer Höhe
zu Boden fallen gelassen. Es gelingt Hades, Athene und Bestien-Ikas, den
Bestienansturm zurückzuwerfen.

**** Ausläufer der Stadt Athen mit Blick auf das Ägäische Meer. Im
Stadtinneren nichts als Berge voller Leichen.
     :PROPERTIES:
     :CUSTOM_ID: ausläufer-der-stadt-athen-mit-blick-auf-das-ägäische-meer.-im-stadtinneren-nichts-als-berge-voller-leichen.
     :END:

HADES, ATHENE, BESTIEN-IKAS von Kopf bis Fuß mit Blut und schwarzer
Masse überzogen.

Bestien-Ikas offenbart den Göttern, dass sie darauf angewiesen sind, von
den Menschen verehrt zu werden. Die Götter reagieren darauf
unentschlossen, wissen nicht, wie ernst sie die Sache nehmen sollen.

*** NEUNTER GESANG -- Nach Paphos
    :PROPERTIES:
    :CUSTOM_ID: neunter-gesang-nach-paphos
    :END:

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-4
     :END:

Ein einsamer SCHATTEN.

Der Kronos-Priester findet sich im Tartarus wieder. Er trifft auf Gaia.
In seinem Kopf ertönt die Stimme des Kronos, der ihn als Spion einsetzen
will. Er bietet seine Dienste den anderen an und schließt sich ihnen an,
in Paphos nach dem Perdix zu suchen. Hades befragt den Kopf des Daedalus
nach dem Labor, in dem Athene den Perdix stehen sieht. Er berichtet von
zwei Laboren, eins auf Salamis und eins in Paphos. Der Schatten wird ob
des Anblickes ohnmächtig. Aphrodite erscheint und macht sich als Erste
nach Paphos auf. Athene, der Schatten, Hades und Bestien-Ikas brechen
nach Paphos auf.

**** Küste bei Paphos. Tag. Gute Sicht und gutes Wetter. Wellen.
     :PROPERTIES:
     :CUSTOM_ID: küste-bei-paphos.-tag.-gute-sicht-und-gutes-wetter.-wellen.
     :END:

Ein FISCHER holt Netze ein. Sie sind größtenteils leer.

Aphrodite erscheint und versucht, den traurigen Fischer zu trösten. Es
gelingt ihr nicht. Die anderen erscheinen zwischendurch. Zum Abschied
schenkt sie dem Fischer einen goldenen Apfel, damit er bis ans Ende
seines Lebens mit seiner Frau glücklich wird.

**** Straße nach Paphos.
     :PROPERTIES:
     :CUSTOM_ID: straße-nach-paphos.
     :END:

Gruppe leicht bekleideter DIRNEN am Wegesrand. HADES, ATHENE,
BESTIEN-IKAS, APHRODITE und der SCHATTEN.

Drei Dirnen bedrängen sie obszön. Aphrodite versteinert sie schließlich
und ist entsetzt ob ihrer Tat.

**** Stadtmauer zu Paphos.
     :PROPERTIES:
     :CUSTOM_ID: stadtmauer-zu-paphos.
     :END:

ATHENE, HADES, BESTIEN-IKAS, APHRODITE und der SCHATTEN nähern sich.
Einige WACHEN stellen sich ihnen in den Weg.

Die Wachen greifen sie an. Sie fliehen in die Stadt.

**** Stadt Paphos. Marktplatz.
     :PROPERTIES:
     :CUSTOM_ID: stadt-paphos.-marktplatz.
     :END:

Treiben und Gedränge. HADES, ATHENE, APHRODITE, BESTIEN-IKAS und der
SCHATTEN stürzen in das Gedränge. Die EINWOHNER beäugen die
Neuankömmlinge kritisch.

Die Blicke der Stadtbewohner folgen lediglich Athene und Aphrodite. In
der Ferne erblicken sie gepfählte Frauen. Die Stadtbewohner und
herbeieilende Wachen stürmen auf sie zu. Hades teleportiert sie gerade
noch rechtzeitig davon.

**** Stadt Paphos. Dunkle Seitengasse.
     :PROPERTIES:
     :CUSTOM_ID: stadt-paphos.-dunkle-seitengasse.
     :END:

HADES, ATHENE, BESTIEN-IKAS, APHRODITE, und der SCHATTEN erscheinen.

Sie beschließen, eine Schenke aufzusuchen, um nach Perdix zu fragen. Ein
Schatten fliegt über sie hinweg. Sie verkleiden die Weiber in ein paar
Stofffetzen, damit sie in der Schenke nicht erkannt werden. Ein paar
Gassen weiter erblicken sie eine Schenke.

**** Schenke Thermodonion in Paphos.
     :PROPERTIES:
     :CUSTOM_ID: schenke-thermodonion-in-paphos.
     :END:

Der Schankraum ist brechend voll. HADES, ATHENE, BESTIEN-IKAS, APHRODITE
und der SCHATTEN treten durch die Tür.

Athene geht sofort zur Theke und wird von Hades zurückgeholt, ehe sie
sich verplappern kann. Der Schatten geht vor die Tür, um Luft zu
schnappen. Bestien-Ikas folgt ihm, da sie ihm nicht trauen. Athene wird
von einem Betrunkenen angemacht. Als er die dicken Arme sieht, lässt er
von ihr ab. Hades will nachsehen, wo der Schatten und der Ikas bleiben.
Eine Gestalt im schwarzen Mantel betritt die Schenke und verschwindet in
der Menschenmenge. Wachen erscheinen und suchen nach Ikas, Athene,
Aphrodite und Hades. Sie werden von der Menschenmenge ausgelacht. Es
kommt zum Kampf, in welchem sich die Schenkenbesucher als Amazonen
entpuppen. Die Gestalt im schwarzen Mantel ermöglicht Athene und
Aphrodite die Flucht durch eine Falltür.

**** Seitengasse in der Nähe der Schenke Thermodonion in Paphos.
     :PROPERTIES:
     :CUSTOM_ID: seitengasse-in-der-nähe-der-schenke-thermodonion-in-paphos.
     :END:

BESTIEN-IKAS sucht die Gegend nach dem Schatten ab.

Er stößt auf den Hades. Sie geben sie Suche nach dem Schatten auf. Als
sie zur Schenke zurückkehren, werden sie Zeuge des Angriffs der Wachen
auf das Gebäude. Sie zünden die Schenke an. Der Bestien-Ikas wird von
den Wachen überwältigt beim Versuch, die Schenke zu stürmen. Hades hält
sich zurück. Er wird Zeuge, wie die Schenke brennend zusammenstürzt.
Überzeugt, dass Athene und Aphrodite tot sein müssen, verschwindet er in
den Tartarus.

*** ZEHNTER GESANG -- Titanendämmerung
    :PROPERTIES:
    :CUSTOM_ID: zehnter-gesang-titanendämmerung
    :END:

**** Langer Gang unter der Schenke. Dunkelheit.
     :PROPERTIES:
     :CUSTOM_ID: langer-gang-unter-der-schenke.-dunkelheit.
     :END:

ATHENE. APHRODITE. GESTALT IM SCHWARZEN MANTEL. Einige Amazonen fleuchen
umher, ihre Schritte hallen durch die Finsternis.

Athene und Aphrodite finden sich im unterirdischen Labor des Perdix
wieder. Es ist das Labor, welches Athene in ihren Visionen gesehen hat.
Die Gestalt im schwarzen Mantel entpuppt sich als Perdix. Sie berichten
von dem Perdix von der Rolle des Daedalus und dass der Ikas sie bei sich
hatte. Perdix macht sich auf die Suche nach Ikas. Sie erfahre von
Pygmalion, der alle Frauen wegen den drei Dirnen vor der Stadt pfählen
ließ. Nachdem Perdix verschwunden ist, begeben sich auch Athene und
Aphrodite auf die Suche nach dem Ikas.

**** Nacht. Geheimer Ausgang irgendwo außerhalb von Paphos.
     :PROPERTIES:
     :CUSTOM_ID: nacht.-geheimer-ausgang-irgendwo-außerhalb-von-paphos.
     :END:

ATHENE und APHRODITE treten daraus hervor. Vor ihnen liegt der Blick
über das Meer.

Perdix hockt im Baum über ihnen. Sie blicken in die Ferne. Athene
schwört ihrer Trinksucht ab.

**** Tartarus.
     :PROPERTIES:
     :CUSTOM_ID: tartarus.-5
     :END:

GAIA. Gebrüll der Hekatoncheiren und Kyklopen aus ihrem Wanste.

Hades lässt die Hoffnung fahren und berichtet der Gaia. Uranus kommt
herbei und schlägt vor, das Delphische Orakel zu befragen. Sie brechen
zum Orakel auf, um zu erfahren, ob noch Hoffnung besteht. Gaia möchte
sich an Themis für den Verrat rächen, den sie beging, als sie Kronos den
Blick ins Becken erlaubte.

**** Himmelsfeste.
     :PROPERTIES:
     :CUSTOM_ID: himmelsfeste.-1
     :END:

KRONOS. Der SCHATTEN. Einige weitere Titanen im Hintergrund.

Der Schatten berichtet dem Schatten vom Einsturz der Schenke. Kronos ist
mit den Informationen unzufrieden und schlägt den Schatten nieder.
Menoitios schlägt vor, das Orakel von Delphi aufzusuchen. Kronos denkt
darüber nach, eine der anderen Titaninnen ans Orakel zu stellen. Sie
brechen auf. Kronos, Menoitios, [[file:kreios.org][Kreios]] und Atlas brechen
auf.

** Historische Ereignisse
   :PROPERTIES:
   :CUSTOM_ID: historische-ereignisse
   :END:

-  [[file:entmannung-des-uranus.org][Entmannung des Uranus]]
-  [[file:geburt-der-aphrodite.org][Geburt der Aphrodite]]
-  [[file:machtergreifung-des-kronos.org][Machtergreifung des Kronos]]
-  [[file:verschlingung-der-kroniden.org][Verschlingung der Kroniden]]

** Ausführliches Personenverzeichnis
   :PROPERTIES:
   :CUSTOM_ID: ausführliches-personenverzeichnis
   :END:

[[file:aphrodite.org][Aphrodite]] · [[file:athene.org][Athene]] · [[file:atlas.org][Atlas]] ·
[[file:bestien-ikas.org][Bestien-Ikas]] · [[file:briareos.org][Briareos]] ·
[[file:daedalus.org][Daedalus]] · [[file:demeter.org][Demeter]] · [[file:dronos.org][Dronos]]
· [[file:gaia.org][Gaia]] · [[file:gyges.org][Gyges]] · [[file:hades.org][Hades]] ·
[[file:hera.org][Hera]] · [[file:hestia.org][Hestia]] · [[file:hyperion.org][Hyperion]] ·
[[file:iapetos.org][Iapetos]] · [[file:ikas.org][Ikas]] · [[file:koios.org][Koios]] ·
[[file:kottos.org][Kottos]] · [[file:kreios.org][Kreios]] · [[file:kronos.org][Kronos]] ·
[[file:kronospriester.org][Kronospriester]] · [[file:menoitios.org][Menoitios]] ·
[[file:mnemosyne.org][Mnemosyne]] · [[file:okeanos.org][Okeanos]] ·
[[file:pandrinos.org][Pandrinos]] · [[file:perdix.org][Perdix]] · [[file:phoibe.org][Phoibe]]
· [[file:poseidon.org][Poseidon]] · [[file:rhea.org][Rhea]] · [[file:sandrias.org][Sandrias]]
· [[file:schatten-des-kronospriesters.org][Schatten des Kronospriesters]] ·
[[file:tethys.org][Tethys]] · [[file:theia.org][Theia]] · [[file:themis.org][Themis]] ·
[[file:uranus.org][Uranus]] · [[file:zeus.org][Zeus]]

*** Tiere, Bestien, Fabelwesen
    :PROPERTIES:
    :CUSTOM_ID: tiere-bestien-fabelwesen
    :END:

[[file:glaukos.org][Glaukos]] · [[file:python.org][Python]]

*** Orte, Länder, Flüsse
    :PROPERTIES:
    :CUSTOM_ID: orte-länder-flüsse
    :END:

[[file:athen.org][Athen]] · [[file:attika.org][Attika]] · [[file:euböa.org][Euböa]] ·
[[file:himmelsfeste-des-uranus.org][Himmelsfeste des Uranus]] ·
[[file:olymp.org][Olymp]] · [[file:orakel-von-delphi.org][Orakel von Delphi]] ·
[[file:paphos.org][Paphos]] · [[file:parnass.org][Parnass]] ·
[[file:quelle-des-lyaeus.org][Quelle des Lyäus (Schenke)]] ·
[[file:salamis-insel.org][Salamis (Insel)]] · [[file:salamis-zypern.org][Salamis
(Zypern)]] · [[file:tartarus.org][Tartarus]] · [[file:thermodonion.org][Thermodonion
(Schenke)]] · [[file:thrakien.org][Thrakien]] · [[file:zum-titanischen-trunke.org][Zum
Titanischen Trunke (Schenke)]] · [[file:zyprus.org][Zyprus]]

*** Sonstige Begriffe
    :PROPERTIES:
    :CUSTOM_ID: sonstige-begriffe
    :END:

[[file:abanten.org][Abanten]] · [[file:trireme.org][Trireme]]

** Easter Eggs
   :PROPERTIES:
   :CUSTOM_ID: easter-eggs
   :END:

ERSTER GESANG -- Der Tod des Ikas

Verlassener Teil des Tartarus

#+BEGIN_EXAMPLE
    Und dann erst dieser große starke Bizeps!
    ALTE FRAU

    Hercules – Die legendären Reisen: Frei wie der Wind. Renaissance Pictures/NBCUniversal 1995-1999.
#+END_EXAMPLE

NEUNTER GESANG -- Nach Paphos

Schenke Thermodonion in Paphos

#+BEGIN_EXAMPLE
    Wenn ihr leben wollt,
    kommt mit mir.
    GESTALT IM SCHWARZEN MANTEL

    Terminator 2 – Tag der Abrechnung. TriStar Pictures 1991.
#+END_EXAMPLE

ZEHNTER GESANG -- Titanendämmerung

Himmelsfeste

#+BEGIN_EXAMPLE
    Willst du wohl still sein!
    KRONOS

    Hercules – Die legendären Reisen: Daedalus großer Irrtum. Renaissance Pictures/NBCUniversal 1995-1999.
#+END_EXAMPLE

** Vorsätzliche Verstöße gegen Rechtschreibung & Grammatik
   :PROPERTIES:
   :CUSTOM_ID: vorsätzliche-verstöße-gegen-rechtschreibung-grammatik
   :END:

/Too much to mention .../

** Fahrlässige Verstöße gegen Rechtschreibung & Grammatik
   :PROPERTIES:
   :CUSTOM_ID: fahrlässige-verstöße-gegen-rechtschreibung-grammatik
   :END:

1. Auflage

-  S. 171

#+BEGIN_QUOTE
  (Sie +bald+ ballt die Faust.)
#+END_QUOTE

Fehler: Typo.

** Siehe auch
   :PROPERTIES:
   :CUSTOM_ID: siehe-auch
   :END:

-  [[file:titaneion-1-unterschiede-originalmythos.org][Unterschiede zum
   Originalmythos]]
