#+SETUPFILE: ../org-templates/level-0.org
#+TITLE: Der Untergang der Stadt Kolophon

Der *Untergang der Stadt Kolophon* beschreibt die Vernichtung der
[[file:kolophon.org][Stadt Kolophon]] durch die Entfesselung und anschließende
Bekämpfung des [[file:ketos.org][Ketos]] durch den Gott
[[file:poseidon.org][Poseidon]].

** Der Angriff der Persischen Flotte
   :PROPERTIES:
   :CUSTOM_ID: der-angriff-der-persischen-flotte
   :END:

Auf dem Weg aus der Stadt Kolophon beobachten der Heiler
[[file:asklepios.org][Asklepios]], [[file:arachne.org][Arachne]], der Junge
[[file:padmilos.org][Padmilos]] und die [[file:colydon.org][Ziege Colydon]], wie sich
die Persische Flotte über das Meer nähert.

** Die Entfesselung des Ketos
   :PROPERTIES:
   :CUSTOM_ID: die-entfesselung-des-ketos
   :END:

Unten an der Küste versammelt sich bereits das Heer Kolophons, als der
Gott Poseidon erscheint. Er wird von den Brandpfeilen der Perser zum
Rückzug ins Meer gezwungen. Daraufhin entfesselt er den Ketos, ein
schreckliches Seeungeheuer mit dutzenden Fangarmen und messerscharfen
Zähnen. Der Ketos vernichtet zwar die Persische Flotte, walzt
gleichzeitig aber auch die Stadt Kolophon nieder.

Als Poseidon daraufhin
[[file:poseidon/#die-rasenden-rosse-des-poseidon.org][seine rasenden Rosse]]
auf die Bestie loslässt, geht diese auf den Gott los. Die Flutwellen
überschwemmen die Stadt Kolophon und vernichten diese. Als Asklepios,
Arachne, Padmilos und die Ziege Colydon die Flucht antreten, sehen sie
gerade noch, wie Poseidon und die Bestie im Zweikampf im Meer versinken.

** Das Leuchten der Okeaniden
   :PROPERTIES:
   :CUSTOM_ID: das-leuchten-der-okeaniden
   :END:

Am nächsten Morgen beobachtet der Junge Padmilos, wie das ganze Meer von
den [[file:okeaniden.org][Töchtern]] des [[file:okeanos.org][Okeanos]] erleuchtet
wird. Sie dringen an die Wasseroberfläche und ziehen all die Toten und
Ertrunkenen mit sich hinunter in die Tiefe.
